//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP8SocketIO18SocketEngineClient_-Protocol.h"

@interface _TtC8SocketIO14SocketIOClient : NSObject <_TtP8SocketIO18SocketEngineClient_>
{
    // Error parsing type: , name: socketURL
    // Error parsing type: , name: engine
    // Error parsing type: , name: needLockWhenCleanup
    // Error parsing type: , name: needRetainWebSocket
    // Error parsing type: , name: status
    // Error parsing type: , name: forceNew
    // Error parsing type: , name: handleQueue
    // Error parsing type: , name: nsp
    // Error parsing type: , name: config
    // Error parsing type: , name: reconnects
    // Error parsing type: , name: reconnectWait
    // Error parsing type: , name: logType
    // Error parsing type: , name: anyHandler
    // Error parsing type: , name: currentReconnectAttempt
    // Error parsing type: , name: handlers
    // Error parsing type: , name: reconnecting
    // Error parsing type: , name: currentAck
    // Error parsing type: , name: reconnectAttempts
    // Error parsing type: , name: ackHandlers
    // Error parsing type: , name: waitingPackets
}

- (void).cxx_destruct;
- (id)init;
- (void)parseEngineBinaryData:(id)arg1;
- (void)parseEngineMessage:(id)arg1;
- (void)engineDidOpenWithReason:(id)arg1;
- (void)engineDidErrorWithReason:(id)arg1;
- (void)engineDidCloseWithReason:(id)arg1;
- (void)dealloc;

@end

