//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AEModule.h"

@class AEManagedValue;

@interface AEBlockModule : AEModule
{
    CDUnknownBlockType _sampleRateChangedBlock;
    CDUnknownBlockType _rendererChannelCountChangedBlock;
    AEManagedValue *_processBlockValue;
    AEManagedValue *_isActiveBlockValue;
}

@property(retain, nonatomic) AEManagedValue *isActiveBlockValue; // @synthesize isActiveBlockValue=_isActiveBlockValue;
@property(retain, nonatomic) AEManagedValue *processBlockValue; // @synthesize processBlockValue=_processBlockValue;
@property(copy, nonatomic) CDUnknownBlockType rendererChannelCountChangedBlock; // @synthesize rendererChannelCountChangedBlock=_rendererChannelCountChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType sampleRateChangedBlock; // @synthesize sampleRateChangedBlock=_sampleRateChangedBlock;
- (void).cxx_destruct;
- (void)rendererDidChangeNumberOfChannels;
- (void)rendererDidChangeSampleRate;
@property(copy, nonatomic) CDUnknownBlockType isActiveBlock; // @dynamic isActiveBlock;
@property(copy, nonatomic) CDUnknownBlockType processBlock; // @dynamic processBlock;
- (id)initWithRenderer:(id)arg1 processBlock:(CDUnknownBlockType)arg2;

@end

