//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AFSubResDownloadConfig, NSArray, NSDate, NSDictionary, NSNumber, NSString;
@protocol AFCMSResorceDataItemsProtocol;

@protocol AFCMSResourceDataProtocol <NSObject>
+ (_Bool)bizDownload;
@property(nonatomic) _Bool isEmptyBucket;
@property(copy, nonatomic) NSString *evt;
@property(copy, nonatomic) NSString *appKey;
@property(retain, nonatomic) NSNumber *priority;
@property(copy, nonatomic) NSString *resURL;
@property(retain, nonatomic) NSDate *endDate;
@property(retain, nonatomic) NSDate *startDate;
@property(copy, nonatomic) NSString *type;
@property(copy, nonatomic) NSString *testDataID;
@property(copy, nonatomic) NSString *testID;
@property(copy, nonatomic) NSString *dataID;
- (AFSubResDownloadConfig *)downloadConfig;
- (long long)fillResult;
- (void)fillBizData:(NSArray *)arg1;
- (void)fillBaseData:(NSDictionary *)arg1;
- (NSString *)uniqueIdentifier;
- (NSArray<AFCMSResorceDataItemsProtocol> *)dataItems;
- (id)initWithResCode:(NSString *)arg1;

@optional
+ (NSDictionary *)defaultMainResData;
@end

