//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol IUCAFStatService;

@interface AFCMSInnerStatHelper : NSObject
{
    id <IUCAFStatService> _statService;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <IUCAFStatService> statService; // @synthesize statService=_statService;
- (void).cxx_destruct;
- (id)createStatProperties:(id)arg1 resData:(id)arg2 properties:(id)arg3;
- (id)createStatProperties:(id)arg1 dataItem:(id)arg2 properties:(id)arg3;
- (id)createStatProperties:(id)arg1 dataId:(id)arg2 mainRes:(id)arg3 properties:(id)arg4;
- (id)buildMidStatWithResDataItems:(id)arg1;
- (id)buildMidStatStr:(id)arg1;
- (void)onStat:(id)arg1 arg1:(id)arg2 args:(id)arg3;
- (void)statCost:(id)arg1 cost:(double)arg2;
- (void)statError:(id)arg1 message:(id)arg2;
- (void)statCMSMainResRequestFail:(id)arg1;
- (void)statCMSMainResRequestNetworkFail;
- (void)statCMSMainResRequestFinish;
- (void)statCMSMainResStartRequest:(_Bool)arg1;
- (void)statCMSClose:(id)arg1 dataItem:(id)arg2 properties:(id)arg3;
- (void)statCMSClick:(id)arg1 dataItem:(id)arg2 properties:(id)arg3;
- (void)statCMSDisplay:(id)arg1 dataItem:(id)arg2 properties:(id)arg3;
- (void)statDownloadResult:(id)arg1 dataId:(id)arg2 mainRes:(id)arg3 properties:(id)arg4;
- (void)statStartDownload:(id)arg1 dataId:(id)arg2 mainRes:(id)arg3 properties:(id)arg4;
- (void)statCMSReceive:(id)arg1 dataItem:(id)arg2 properties:(id)arg3;

@end

