//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface AFCMSABTestData : NSObject
{
    NSString *_testId;
    NSString *_dataId;
}

@property(copy, nonatomic) NSString *dataId; // @synthesize dataId=_dataId;
@property(copy, nonatomic) NSString *testId; // @synthesize testId=_testId;
- (void).cxx_destruct;

@end

