//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface AgoraRtmRemoteInvitation : NSObject
{
    NSString *_callerId;
    NSString *_content;
    NSString *_response;
    NSString *_channelId;
    long long _state;
}

@property(nonatomic) long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
@property(copy, nonatomic) NSString *response; // @synthesize response=_response;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *callerId; // @synthesize callerId=_callerId;
- (void).cxx_destruct;

@end

