//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AgoraBeautyOptions : NSObject
{
    float _lighteningLevel;
    float _smoothnessLevel;
    float _rednessLevel;
    unsigned long long _lighteningContrastLevel;
}

@property(nonatomic) float rednessLevel; // @synthesize rednessLevel=_rednessLevel;
@property(nonatomic) float smoothnessLevel; // @synthesize smoothnessLevel=_smoothnessLevel;
@property(nonatomic) float lighteningLevel; // @synthesize lighteningLevel=_lighteningLevel;
@property(nonatomic) unsigned long long lighteningContrastLevel; // @synthesize lighteningContrastLevel=_lighteningContrastLevel;
- (id)init;

@end

