//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AgoraRtmKit, NSMutableArray;
@protocol AgoraRtmCallDelegate;

@interface AgoraRtmCallKit : NSObject
{
    _Bool _destroying;
    _Bool _isDispatchedMainQueue;
    AgoraRtmKit *_rtmKit;
    id <AgoraRtmCallDelegate> _callDelegate;
    struct IRtmCallManager *_rtmCallManager;
    struct RtmCallEventHandlerIosImpl *_callHandler;
    NSMutableArray *_localObjects;
    NSMutableArray *_remoteObjects;
}

+ (id)sharedCallDelegateExecutionQueue;
@property(retain) NSMutableArray *remoteObjects; // @synthesize remoteObjects=_remoteObjects;
@property(retain) NSMutableArray *localObjects; // @synthesize localObjects=_localObjects;
@property _Bool isDispatchedMainQueue; // @synthesize isDispatchedMainQueue=_isDispatchedMainQueue;
@property _Bool destroying; // @synthesize destroying=_destroying;
@property(nonatomic) struct RtmCallEventHandlerIosImpl *callHandler; // @synthesize callHandler=_callHandler;
@property(nonatomic) struct IRtmCallManager *rtmCallManager; // @synthesize rtmCallManager=_rtmCallManager;
@property(nonatomic) __weak id <AgoraRtmCallDelegate> callDelegate; // @synthesize callDelegate=_callDelegate;
@property __weak AgoraRtmKit *rtmKit; // @synthesize rtmKit=_rtmKit;
- (void).cxx_destruct;
- (void)dealloc;
- (void)refuseRemoteInvitation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)acceptRemoteInvitation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cancelLocalInvitation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendLocalInvitation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithRtmKit:(id)arg1;
- (void)dispatchRemoteInvitationFailure:(id)arg1 errorCode:(long long)arg2;
- (void)dispatchLocalInvitationFailure:(id)arg1 errorCode:(long long)arg2;
- (id)getRemoteInvitationObject:(id)arg1;
- (id)getLocalInvitationObject:(id)arg1;
- (void)clearRemoteInvitationObject:(id)arg1;
- (void)clearLocalInvitationObject:(id)arg1;
- (void)executeDelegateBlock:(CDUnknownBlockType)arg1;

@end

