//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AgoraChannelStats : NSObject
{
    long long _duration;
    long long _txBytes;
    long long _rxBytes;
    long long _txAudioBytes;
    long long _txVideoBytes;
    long long _rxAudioBytes;
    long long _rxVideoBytes;
    long long _txKBitrate;
    long long _rxKBitrate;
    long long _txAudioKBitrate;
    long long _rxAudioKBitrate;
    long long _txVideoKBitrate;
    long long _rxVideoKBitrate;
    long long _lastmileDelay;
    long long _txPacketLossRate;
    long long _rxPacketLossRate;
    long long _userCount;
    double _cpuAppUsage;
    double _cpuTotalUsage;
}

@property(nonatomic) double cpuTotalUsage; // @synthesize cpuTotalUsage=_cpuTotalUsage;
@property(nonatomic) double cpuAppUsage; // @synthesize cpuAppUsage=_cpuAppUsage;
@property(nonatomic) long long userCount; // @synthesize userCount=_userCount;
@property(nonatomic) long long rxPacketLossRate; // @synthesize rxPacketLossRate=_rxPacketLossRate;
@property(nonatomic) long long txPacketLossRate; // @synthesize txPacketLossRate=_txPacketLossRate;
@property(nonatomic) long long lastmileDelay; // @synthesize lastmileDelay=_lastmileDelay;
@property(nonatomic) long long rxVideoKBitrate; // @synthesize rxVideoKBitrate=_rxVideoKBitrate;
@property(nonatomic) long long txVideoKBitrate; // @synthesize txVideoKBitrate=_txVideoKBitrate;
@property(nonatomic) long long rxAudioKBitrate; // @synthesize rxAudioKBitrate=_rxAudioKBitrate;
@property(nonatomic) long long txAudioKBitrate; // @synthesize txAudioKBitrate=_txAudioKBitrate;
@property(nonatomic) long long rxKBitrate; // @synthesize rxKBitrate=_rxKBitrate;
@property(nonatomic) long long txKBitrate; // @synthesize txKBitrate=_txKBitrate;
@property(nonatomic) long long rxVideoBytes; // @synthesize rxVideoBytes=_rxVideoBytes;
@property(nonatomic) long long rxAudioBytes; // @synthesize rxAudioBytes=_rxAudioBytes;
@property(nonatomic) long long txVideoBytes; // @synthesize txVideoBytes=_txVideoBytes;
@property(nonatomic) long long txAudioBytes; // @synthesize txAudioBytes=_txAudioBytes;
@property(nonatomic) long long rxBytes; // @synthesize rxBytes=_rxBytes;
@property(nonatomic) long long txBytes; // @synthesize txBytes=_txBytes;
@property(nonatomic) long long duration; // @synthesize duration=_duration;

@end

