//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AgoraRtcEngineDelegate-Protocol.h"

@class AgoraLiveChannelConfig, AgoraLivePublisher, AgoraLiveSubscriber, AgoraRtcEngineKit, NSMutableDictionary, NSString;
@protocol AgoraLiveDelegate, AgoraLivePublisherDelegate, AgoraLiveSubscriberDelegate;

@interface AgoraLiveKit : NSObject <AgoraRtcEngineDelegate>
{
    id <AgoraLiveDelegate> _delegate;
    AgoraRtcEngineKit *_engineKit;
    AgoraLiveChannelConfig *_channelConfig;
    AgoraLivePublisher *_publisher;
    AgoraLiveSubscriber *_subscriber;
    unsigned long long _uid;
    NSString *_channelId;
    NSString *_appId;
    long long _vid;
    NSMutableDictionary *_remoteStreamMediaStats;
    id <AgoraLivePublisherDelegate> _publisherDelegate;
    id <AgoraLiveSubscriberDelegate> _subscriberDelegate;
}

+ (void)destroy;
+ (id)sharedLiveKitWithAppId:(id)arg1;
+ (id)getSdkVersion;
@property(nonatomic) __weak id <AgoraLiveSubscriberDelegate> subscriberDelegate; // @synthesize subscriberDelegate=_subscriberDelegate;
@property(nonatomic) __weak id <AgoraLivePublisherDelegate> publisherDelegate; // @synthesize publisherDelegate=_publisherDelegate;
@property(retain, nonatomic) NSMutableDictionary *remoteStreamMediaStats; // @synthesize remoteStreamMediaStats=_remoteStreamMediaStats;
@property(nonatomic) long long vid; // @synthesize vid=_vid;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
@property unsigned long long uid; // @synthesize uid=_uid;
@property(retain, nonatomic) AgoraLiveSubscriber *subscriber; // @synthesize subscriber=_subscriber;
@property(retain, nonatomic) AgoraLivePublisher *publisher; // @synthesize publisher=_publisher;
@property(retain, nonatomic) AgoraLiveChannelConfig *channelConfig; // @synthesize channelConfig=_channelConfig;
@property(retain, nonatomic) AgoraRtcEngineKit *engineKit; // @synthesize engineKit=_engineKit;
@property(nonatomic) __weak id <AgoraLiveDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)rtcEngine:(id)arg1 streamInjectedStatusOfUrl:(id)arg2 uid:(unsigned long long)arg3 status:(unsigned long long)arg4;
- (void)rtcEngineTranscodingUpdated:(id)arg1;
- (void)rtcEngine:(id)arg1 streamUnpublishedWithUrl:(id)arg2;
- (void)rtcEngine:(id)arg1 streamPublishedWithUrl:(id)arg2 errorCode:(long long)arg3;
- (void)rtcEngine:(id)arg1 didVideoMuted:(_Bool)arg2 byUid:(unsigned long long)arg3;
- (void)rtcEngine:(id)arg1 didAudioMuted:(_Bool)arg2 byUid:(unsigned long long)arg3;
- (void)rtcEngine:(id)arg1 didOfflineOfUid:(unsigned long long)arg2 reason:(unsigned long long)arg3;
- (void)rtcEngine:(id)arg1 didJoinedOfUid:(unsigned long long)arg2 elapsed:(long long)arg3;
- (long long)getMediaTypeByStat:(int)arg1;
- (void)rtcEngine:(id)arg1 firstRemoteVideoFrameOfUid:(unsigned long long)arg2 size:(struct CGSize)arg3 elapsed:(long long)arg4;
- (void)rtcEngine:(id)arg1 videoSizeChangedOfUid:(unsigned long long)arg2 size:(struct CGSize)arg3 rotation:(long long)arg4;
- (void)rtcEngine:(id)arg1 tokenPrivilegeWillExpire:(id)arg2;
- (void)rtcEngineRequestToken:(id)arg1;
- (void)rtcEngine:(id)arg1 networkQuality:(unsigned long long)arg2 txQuality:(unsigned long long)arg3 rxQuality:(unsigned long long)arg4;
- (void)rtcEngine:(id)arg1 didLeaveChannelWithStats:(id)arg2;
- (void)rtcEngine:(id)arg1 reportRtcStats:(id)arg2;
- (void)rtcEngine:(id)arg1 didRejoinChannel:(id)arg2 withUid:(unsigned long long)arg3 elapsed:(long long)arg4;
- (void)rtcEngine:(id)arg1 didJoinChannel:(id)arg2 withUid:(unsigned long long)arg3 elapsed:(long long)arg4;
- (void)rtcEngineConnectionDidLost:(id)arg1;
- (void)rtcEngineConnectionDidInterrupted:(id)arg1;
- (void)rtcEngine:(id)arg1 didOccurError:(long long)arg2;
- (void)rtcEngine:(id)arg1 didOccurWarning:(long long)arg2;
- (int)replyJoinPublisherInvitationToOwner:(unsigned long long)arg1;
- (int)inviteJoinPublisherToUser:(unsigned long long)arg1;
- (int)stopPreview;
- (int)startPreview:(struct UIView *)arg1 renderMode:(unsigned long long)arg2;
- (id)stringOfEncryptionMode:(long long)arg1;
- (int)renewToken:(id)arg1;
- (int)leaveChannel;
- (int)joinChannelByToken:(id)arg1 channelId:(id)arg2 config:(id)arg3 uid:(unsigned long long)arg4;
- (void)log:(id)arg1;
- (id)getRtcEngineKit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

