//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AgoraVideoSourceProtocol-Protocol.h"

@class AgoraRtcEngineKit, NSString;
@protocol AgoraVideoFrameConsumer;

@interface AgoraRtcDefaultCamera : NSObject <AgoraVideoSourceProtocol>
{
    long long _position;
    id <AgoraVideoFrameConsumer> _myConsumer;
    AgoraRtcEngineKit *_engineKit;
}

@property(nonatomic) __weak AgoraRtcEngineKit *engineKit; // @synthesize engineKit=_engineKit;
@property(nonatomic) __weak id <AgoraVideoFrameConsumer> myConsumer; // @synthesize myConsumer=_myConsumer;
@property(nonatomic) long long position; // @synthesize position=_position;
- (void).cxx_destruct;
- (long long)bufferType;
- (void)shouldDispose;
- (void)shouldStop;
- (void)shouldStart;
- (_Bool)shouldInitialize;
@property(retain) id <AgoraVideoFrameConsumer> consumer;
- (id)initWithPosition:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

