//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;
@protocol NSCoding;

@protocol AliCacheInterface <NSObject>
- (void)trimToTime:(double)arg1 withBlock:(void (^)(void))arg2;
- (void)trimToTime:(double)arg1;
- (void)trimToBytes:(unsigned long long)arg1 withBlock:(void (^)(void))arg2;
- (void)trimToBytes:(unsigned long long)arg1;
- (void)trimToCount:(unsigned long long)arg1 withBlock:(void (^)(void))arg2;
- (void)trimToCount:(unsigned long long)arg1;
- (void)totalByteWithBlock:(void (^)(unsigned long long))arg1;
- (unsigned long long)totalByte;
- (void)totalCountWithBlock:(void (^)(unsigned long long))arg1;
- (unsigned long long)totalCount;
- (void)removeAllObjectsWithBlock:(void (^)(void))arg1;
- (NSArray *)allkeys;
- (void)removeAllObjects;
- (void)removeObjectForKey:(NSString *)arg1 withBlock:(void (^)(NSString *))arg2;
- (void)removeObjectForKey:(NSString *)arg1;
- (void)setObject:(id <NSCoding>)arg1 forKey:(NSString *)arg2 options:(unsigned long long)arg3 withBlock:(void (^)(void))arg4;
- (void)setObject:(id <NSCoding>)arg1 forKey:(NSString *)arg2 options:(unsigned long long)arg3;
- (void)objectForKey:(NSString *)arg1 skipMemory:(_Bool)arg2 withBlock:(void (^)(NSString *, id <NSCoding>))arg3;
- (void)objectForKey:(NSString *)arg1 withBlock:(void (^)(NSString *, id <NSCoding>))arg2;
- (id <NSCoding>)objectForKey:(NSString *)arg1 skipMemory:(_Bool)arg2;
- (id <NSCoding>)objectForKey:(NSString *)arg1;
- (void)containsObjectForKey:(NSString *)arg1 withBlock:(void (^)(NSString *, _Bool))arg2;
- (_Bool)containsObjectForKey:(NSString *)arg1;
@end

