//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AliDBRemoteConfig : NSObject
{
    _Bool _useOldDatabase;
    long long _slowSQLThresholdMS;
}

+ (id)sharedInstance;
@property(nonatomic) long long slowSQLThresholdMS; // @synthesize slowSQLThresholdMS=_slowSQLThresholdMS;
@property(nonatomic) _Bool useOldDatabase; // @synthesize useOldDatabase=_useOldDatabase;
- (void)handleConfigChanged:(id)arg1;
- (void)loadConfig;

@end

