//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString;

@protocol AliMonitorInterface <NSObject>
- (void)endWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 measureName:(NSString *)arg3;
- (void)beginWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 measureName:(NSString *)arg3;
- (void)commitWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 value:(double)arg3;
- (void)commitWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 dimensionValueSet:(NSDictionary *)arg3 value:(double)arg4;
- (void)commitWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 dimensionValueSet:(NSDictionary *)arg3 measureValueSet:(NSDictionary *)arg4;
- (_Bool)registerWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 measureSet:(NSArray *)arg3 dimensionSet:(NSArray *)arg4 isCommitDetail:(_Bool)arg5;
- (_Bool)registerWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 measureSet:(NSArray *)arg3 isCommitDetail:(_Bool)arg4;
- (_Bool)registerWithModule:(NSString *)arg1 monitorPoint:(NSString *)arg2 dimensionSet:(NSArray *)arg3 isCommitDetail:(_Bool)arg4;
- (void)commitWithPage:(NSString *)arg1 monitorPoint:(NSString *)arg2 value:(double)arg3 arg:(NSString *)arg4;
- (void)commitWithPage:(NSString *)arg1 monitorPoint:(NSString *)arg2 value:(double)arg3;
- (void)commitFailWithPage:(NSString *)arg1 monitorPoint:(NSString *)arg2 errorCode:(NSString *)arg3 errorMsg:(NSString *)arg4 arg:(NSString *)arg5;
- (void)commitFailWithPage:(NSString *)arg1 monitorPoint:(NSString *)arg2 errorCode:(NSString *)arg3 errorMsg:(NSString *)arg4;
- (void)commitSuccessWithPage:(NSString *)arg1 monitorPoint:(NSString *)arg2 arg:(NSString *)arg3;
- (void)commitSuccessWithPage:(NSString *)arg1 monitorPoint:(NSString *)arg2;
@end

