//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CNRmbMessageInfo : NSObject
{
    _Bool _isSortedRmb;
    NSString *_appId;
    NSString *_serviceId;
    NSString *_pushId;
    NSString *_msgData;
    long long _seq;
}

+ (id)rmbInfoWithAppId:(id)arg1 serviceId:(id)arg2 pushId:(id)arg3 msgData:(id)arg4;
@property(nonatomic) long long seq; // @synthesize seq=_seq;
@property(nonatomic) _Bool isSortedRmb; // @synthesize isSortedRmb=_isSortedRmb;
@property(retain, nonatomic) NSString *msgData; // @synthesize msgData=_msgData;
@property(retain, nonatomic) NSString *pushId; // @synthesize pushId=_pushId;
@property(retain, nonatomic) NSString *serviceId; // @synthesize serviceId=_serviceId;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (id)description;
- (id)convertMsgDataToDict;
- (id)toMessageDict;
- (id)initWithAppId:(id)arg1 serviceId:(id)arg2 pushId:(id)arg3 msgData:(id)arg4;
- (void)dealloc;

@end

