//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MJRefreshComponent.h"

@class NSMutableDictionary, UIActivityIndicatorView, UIImageView, UILabel;

@interface MJRefreshRighter : MJRefreshComponent
{
    double _ignoredScrollViewContentInsetRight;
    long long _lastRefreshCount;
    double _lastRightDelta;
    UILabel *_statelbl;
    UIImageView *_arrowImageView;
    UIActivityIndicatorView *_indicator;
    NSMutableDictionary *_stateLblTextDictM;
}

+ (id)righterWithRefreshingTarget:(id)arg1 refreshingAction:(SEL)arg2;
+ (id)righterWithRefreshingBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableDictionary *stateLblTextDictM; // @synthesize stateLblTextDictM=_stateLblTextDictM;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UILabel *statelbl; // @synthesize statelbl=_statelbl;
@property(nonatomic) double lastRightDelta; // @synthesize lastRightDelta=_lastRightDelta;
@property(nonatomic) long long lastRefreshCount; // @synthesize lastRefreshCount=_lastRefreshCount;
@property(nonatomic) double ignoredScrollViewContentInsetRight; // @synthesize ignoredScrollViewContentInsetRight=_ignoredScrollViewContentInsetRight;
- (void).cxx_destruct;
- (void)setTitle:(id)arg1 forState:(long long)arg2;
- (void)updateStateAttrTextWithState:(long long)arg1;
- (double)happenOffsetX;
- (double)widthForContentBreakView;
- (void)endRefreshingWithNoMoreData;
- (void)endRefreshing;
- (void)setState:(long long)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)willMoveToSuperview:(id)arg1;

@end

