//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSRecursiveLock;

@interface NetworkDemote : NSObject
{
    int dnsDemote;
    int demote2Http;
    _Bool httpsDemote;
    int spdyVipErrorLimited;
    _Bool _canPrebuiltConnections;
    _Bool _canLazyStartWhiteACCSConnection;
    _Bool _canInitWithRequest;
    _Bool _canInitWithWhiteHostsRequest;
    int _spdyLinkHoldTimeRate;
    int _spdyCreateConnectionTimeout;
    NSArray *_layzStartWhiteHosts;
    NSDictionary *_whiteHosts;
    NSMutableArray *_URLPrefixBlackList;
    NSRecursiveLock *_whiteLock;
    NSRecursiveLock *_blackLock;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSRecursiveLock *blackLock; // @synthesize blackLock=_blackLock;
@property(retain, nonatomic) NSRecursiveLock *whiteLock; // @synthesize whiteLock=_whiteLock;
@property(retain, nonatomic) NSMutableArray *URLPrefixBlackList; // @synthesize URLPrefixBlackList=_URLPrefixBlackList;
@property(retain, nonatomic) NSDictionary *whiteHosts; // @synthesize whiteHosts=_whiteHosts;
@property(nonatomic) _Bool canInitWithWhiteHostsRequest; // @synthesize canInitWithWhiteHostsRequest=_canInitWithWhiteHostsRequest;
@property(nonatomic) _Bool canInitWithRequest; // @synthesize canInitWithRequest=_canInitWithRequest;
@property(retain) NSArray *layzStartWhiteHosts; // @synthesize layzStartWhiteHosts=_layzStartWhiteHosts;
@property(nonatomic) _Bool canLazyStartWhiteACCSConnection; // @synthesize canLazyStartWhiteACCSConnection=_canLazyStartWhiteACCSConnection;
@property(nonatomic) _Bool canPrebuiltConnections; // @synthesize canPrebuiltConnections=_canPrebuiltConnections;
@property(nonatomic) int spdyCreateConnectionTimeout; // @synthesize spdyCreateConnectionTimeout=_spdyCreateConnectionTimeout;
@property(nonatomic) int spdyLinkHoldTimeRate; // @synthesize spdyLinkHoldTimeRate=_spdyLinkHoldTimeRate;
- (void).cxx_destruct;
- (void)unAlwaysSpdyDemote;
- (void)alwaysSpdyDemote;
- (_Bool)isDemote2HTTP;
- (void)unDemote2HTTP;
- (void)demote2HTTP;
- (void)unHTTPSDemote;
- (void)httpsDemote;
- (_Bool)isHTTPSDemote;
- (void)unDNSDemote;
- (void)dnsDemote;
- (_Bool)isDNSDemote:(id)arg1;
- (void)networkDemoteSPDY;
- (void)unDemoteSPDY;
- (_Bool)isDemoteSPDY;
- (_Bool)isBlackHost:(id)arg1;
- (_Bool)isWhiteHost:(id)arg1;
- (void)dealloc;
- (id)init;

@end

