//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (UCAF_NSHash_AdditionalHashingAlgorithms)
- (id)ucaf_SHA256;
- (id)ucaf_SHA1;
- (id)ucaf_MD5;
@end

