//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (UCAFBase64)
+ (id)ucaf_dataFromhBase64EncodedData:(id)arg1;
+ (id)ucaf_dataFromBase64String:(id)arg1;
+ (id)ucaf_base64DataWithBase64EncodedString:(id)arg1;
- (id)ucaf_base64EncodedStringWithSeparateLines:(_Bool)arg1;
- (id)ucaf_base64EncodedString;
- (id)ucaf_base64Base64Encoding;
@end

