//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (UCAFNSJSON)
- (id)ucaf_JSONStringWithOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)ucaf_JSONStringWithError:(id *)arg1;
- (id)ucaf_JSONString;
- (id)ucaf_JSONDataWithOptions:(unsigned long long)arg1 error:(id *)arg2;
- (id)ucaf_JSONDataWithError:(id *)arg1;
- (id)ucaf_JSONData;
@end

