//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (ucafsafe)
- (void)ucaf_safeSetObject:(id)arg1 forKey:(id)arg2;
- (void)ucaf_safeAddEntriesFromDictionary:(id)arg1;
- (void)ucaf_safeRemoveObjectForKey:(id)arg1;
@end

