//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol NWKLauncherMock;

@interface NWInitialization : NSObject
{
    id <NWKLauncherMock> _nwkLaucherInstance;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <NWKLauncherMock> nwkLaucherInstance; // @synthesize nwkLaucherInstance=_nwkLaucherInstance;
- (void).cxx_destruct;
@property(readonly) double lastLaunchTime;
@property(readonly) double launchTime;
@property(readonly, copy) NSString *launchURL;
@property(readonly, copy) NSString *startType;
- (id)init;

@end

