//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol OS_dispatch_queue;

@interface NWNettypeReportManager : NSObject
{
    NSObject<OS_dispatch_queue> *_reportQueue;
    NSMutableSet *_reportedNetworkSet;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableSet *reportedNetworkSet; // @synthesize reportedNetworkSet=_reportedNetworkSet;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *reportQueue; // @synthesize reportQueue=_reportQueue;
- (void).cxx_destruct;
- (void)onNetworkInfoChanged;
- (void)retportUT;
- (id)currentNetworkId;
- (id)init;

@end

