//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Aisles, NSString;

@interface NWRacePolicy : NSObject
{
    int _pingSuccessCount;
    int _pingTimeoutCount;
    NSString *_ip;
    NSString *_path;
    Aisles *_aisles;
    NSString *_localIP;
}

@property(nonatomic) int pingTimeoutCount; // @synthesize pingTimeoutCount=_pingTimeoutCount;
@property(nonatomic) int pingSuccessCount; // @synthesize pingSuccessCount=_pingSuccessCount;
@property(retain, nonatomic) NSString *localIP; // @synthesize localIP=_localIP;
@property(retain, nonatomic) Aisles *aisles; // @synthesize aisles=_aisles;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *ip; // @synthesize ip=_ip;
- (void).cxx_destruct;
- (id)description;
- (id)initWithDict:(id)arg1;

@end

