//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPAccountProtocol-Protocol.h"

@class NSDictionary, NSString;
@protocol OPAccountDelegate, OPAccountLoginPluginProtocol;

@interface OPAccountLoginPlugin : NSObject <OPAccountProtocol>
{
    _Bool _isCancel;
    id <OPAccountDelegate> _delegate;
    unsigned long long _accountType;
    unsigned long long _logerStatus;
    NSDictionary *_userInfo;
    id <OPAccountLoginPluginProtocol> _pluginObject;
}

+ (id)pluginWithName:(id)arg1;
+ (void)addPlugin:(id)arg1;
+ (id)pluginList;
@property(nonatomic) _Bool isCancel; // @synthesize isCancel=_isCancel;
@property(retain, nonatomic) id <OPAccountLoginPluginProtocol> pluginObject; // @synthesize pluginObject=_pluginObject;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) unsigned long long logerStatus; // @synthesize logerStatus=_logerStatus;
@property(readonly, nonatomic) unsigned long long accountType; // @synthesize accountType=_accountType;
@property(nonatomic) __weak id <OPAccountDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)loginCompleteWithOpenId:(id)arg1 token:(id)arg2 userInfo:(id)arg3;
- (void)loginFail:(id)arg1;
- (void)loginCancel;
- (void)raiseLogInViewState:(unsigned long long)arg1;
- (void)raiseLogInResult:(unsigned long long)arg1 error:(id)arg2;
- (void)raiseLoginInStart;
- (void)raiseLogerStatusChanged;
- (void)updateLogerStatus:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool isThirdPartyLogingIn;
- (void)cancelLogIn;
- (void)logoutWithUserInfo:(id)arg1;
- (void)logInFromViewController:(id)arg1 userInfo:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

