//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol OPAccountProtocol;

@protocol OPAccountDelegate <NSObject>
- (void)account:(id <OPAccountProtocol>)arg1 logInViewState:(unsigned long long)arg2;
- (void)account:(id <OPAccountProtocol>)arg1 logOutEndWithResult:(unsigned long long)arg2 withError:(NSError *)arg3;
- (void)account:(id <OPAccountProtocol>)arg1 logInEndWithResult:(unsigned long long)arg2 withError:(NSError *)arg3;
- (void)accountLogInStart:(id <OPAccountProtocol>)arg1;
- (void)account:(id <OPAccountProtocol>)arg1 logerStatusChanged:(unsigned long long)arg2;
@end

