//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPAccountDelegate-Protocol.h"

@class NSString;
@protocol OPAccountLoginManagerDelegate, OPAccountProtocol;

@interface OPAccountLoginManager : NSObject <OPAccountDelegate>
{
    id <OPAccountLoginManagerDelegate> _delegate;
    unsigned long long _loggerStatus;
    id <OPAccountProtocol> _currentAccount;
}

@property(retain, nonatomic) id <OPAccountProtocol> currentAccount; // @synthesize currentAccount=_currentAccount;
@property(nonatomic) unsigned long long loggerStatus; // @synthesize loggerStatus=_loggerStatus;
@property(nonatomic) __weak id <OPAccountLoginManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)account:(id)arg1 logInViewState:(unsigned long long)arg2;
- (void)account:(id)arg1 logOutEndWithResult:(unsigned long long)arg2 withError:(id)arg3;
- (void)account:(id)arg1 logInEndWithResult:(unsigned long long)arg2 withError:(id)arg3;
- (void)accountLogInStart:(id)arg1;
- (void)account:(id)arg1 logerStatusChanged:(unsigned long long)arg2;
- (void)cancelLogIn;
- (void)logOut;
- (void)loginWithMobile:(id)arg1 withSmsCode:(id)arg2 withUserInfo:(id)arg3;
- (void)logInFromViewController:(id)arg1 withLoginAccountClass:(Class)arg2 withUserInfo:(id)arg3;
- (void)logInFromViewController:(id)arg1 withPlugin:(id)arg2 withUserInfo:(id)arg3;
- (_Bool)isThirdPartyLogingIn;
- (_Bool)isLogOut;
- (_Bool)isLogin;
- (_Bool)verifyAccountData;
- (void)setupLoginStatus;
- (id)currentTicket;
- (id)currentUserProfile;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

