//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, OPActionSheetData, UIButton, UITableView;

@interface OPActionSheet : UIView <UITableViewDelegate, UITableViewDataSource>
{
    CDUnknownBlockType _clickBottomItem;
    CDUnknownBlockType _clickSheetItem;
    OPActionSheetData *_sheetData;
    UITableView *_sheetTable;
    UIButton *_bottomBtn;
    unsigned long long _cellCount;
    double _sectionFooterViewHeight;
}

@property(nonatomic) double sectionFooterViewHeight; // @synthesize sectionFooterViewHeight=_sectionFooterViewHeight;
@property(nonatomic) unsigned long long cellCount; // @synthesize cellCount=_cellCount;
@property(nonatomic) __weak UIButton *bottomBtn; // @synthesize bottomBtn=_bottomBtn;
@property(nonatomic) __weak UITableView *sheetTable; // @synthesize sheetTable=_sheetTable;
@property(retain, nonatomic) OPActionSheetData *sheetData; // @synthesize sheetData=_sheetData;
@property(copy, nonatomic) CDUnknownBlockType clickSheetItem; // @synthesize clickSheetItem=_clickSheetItem;
@property(copy, nonatomic) CDUnknownBlockType clickBottomItem; // @synthesize clickBottomItem=_clickBottomItem;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)actionSheetOnClickBottomItem:(id)arg1;
- (void)actionSheet:(id)arg1 clickItemAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)dissmiss;
- (void)showWithView:(id)arg1;
- (void)setupSelfView;
- (void)dealloc;
- (id)initWithSheetData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

