//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPAlertStyleBackground : NSObject
{
    _Bool _blur;
    _Bool _canDismiss;
    float _alpha;
}

@property(nonatomic) float alpha; // @synthesize alpha=_alpha;
@property(nonatomic) _Bool canDismiss; // @synthesize canDismiss=_canDismiss;
@property(nonatomic) _Bool blur; // @synthesize blur=_blur;

@end

