//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPAlertButtonItem : NSObject
{
    _Bool _disable;
    NSString *_title;
    CDUnknownBlockType _shouldClick;
    CDUnknownBlockType _clicked;
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) CDUnknownBlockType clicked; // @synthesize clicked=_clicked;
@property(copy, nonatomic) CDUnknownBlockType shouldClick; // @synthesize shouldClick=_shouldClick;
@property(nonatomic) _Bool disable; // @synthesize disable=_disable;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

