//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class OPAlertStyle;

@interface OPAlertStyleCache : NSObject
{
    OPAlertStyle *_styleNormal;
    OPAlertStyle *_styleTitleOnly;
    OPAlertStyle *_styleContentOnly;
}

@property(retain, nonatomic) OPAlertStyle *styleContentOnly; // @synthesize styleContentOnly=_styleContentOnly;
@property(retain, nonatomic) OPAlertStyle *styleTitleOnly; // @synthesize styleTitleOnly=_styleTitleOnly;
@property(retain, nonatomic) OPAlertStyle *styleNormal; // @synthesize styleNormal=_styleNormal;
- (void).cxx_destruct;

@end

