//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, OPAccountTicket, OPAccountUserProfile;

@protocol OPCAccountLoginExtraTaskProtocl <NSObject>
- (void)cancel;
- (void)resumeTaskWithAccountTicket:(OPAccountTicket *)arg1 withUserProfile:(OPAccountUserProfile *)arg2 withInfo:(NSDictionary *)arg3 withCompletion:(void (^)(id, _Bool, NSError *))arg4;
@end

