//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPCAudioPlayHelper : NSObject
{
}

+ (id)stringFromTimeInterval:(double)arg1;
+ (_Bool)isInFuture:(id)arg1;
+ (_Bool)isYesterday:(id)arg1;
+ (_Bool)isToday:(id)arg1;
+ (id)profileDirectory;

@end

