//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPCAccountCenter : NSObject
{
}

+ (void)commonRequest:(id)arg1 method:(id)arg2 urlParams:(id)arg3 headers:(id)arg4 body:(id)arg5 completedHandler:(CDUnknownBlockType)arg6;
+ (id)defaultAccountCenter;
- (void)destroyAbandon:(id)arg1 withST:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)destroyApply:(id)arg1 withST:(id)arg2 withVcode:(id)arg3 withSmsRequestId:(id)arg4 completedHandler:(CDUnknownBlockType)arg5;
- (void)destroyCheck:(id)arg1 withST:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)unbindAccount:(id)arg1 withST:(id)arg2 withThirdPartyName:(id)arg3 completedHandler:(CDUnknownBlockType)arg4;
- (void)bindAccount:(id)arg1 withST:(id)arg2 withThirdPartyName:(id)arg3 withThirdPartyToken:(id)arg4 completedHandler:(CDUnknownBlockType)arg5;
- (void)getAccountBinding:(id)arg1 withST:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)checkSecuritySms:(id)arg1 withST:(id)arg2 withSmsRequestId:(id)arg3 withCode:(id)arg4 completedHandler:(CDUnknownBlockType)arg5;
- (void)sendSecuritySms:(id)arg1 withST:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)getVistorList:(id)arg1 st:(id)arg2 withCursor:(id)arg3 withSize:(long long)arg4 completedHandler:(CDUnknownBlockType)arg5;
- (void)auditComment:(id)arg1 completedHandler:(CDUnknownBlockType)arg2;
- (void)verifySTWithUserInfo:(id)arg1 st:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)getWechatUserInfo:(id)arg1 completedHandler:(CDUnknownBlockType)arg2;
- (void)bindMobileWithCode:(id)arg1 mobile:(id)arg2 uid:(id)arg3 st:(id)arg4 completedHandler:(CDUnknownBlockType)arg5;
- (void)checkSmsCode:(id)arg1 mobile:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)sendVoiceCode:(id)arg1 completedHandler:(CDUnknownBlockType)arg2;
- (void)sendSmsCode:(id)arg1 completedHandler:(CDUnknownBlockType)arg2;
- (void)checkMobile:(id)arg1 completedHandler:(CDUnknownBlockType)arg2;
- (void)editUserProfile:(id)arg1 st:(id)arg2 userInfo:(id)arg3 completedHandler:(CDUnknownBlockType)arg4;
- (void)getUserProfile:(id)arg1 withucid:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)getUserInfos:(id)arg1 withucid:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)logout:(id)arg1 withServerTicket:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)loginWithThirdPartyAccount:(id)arg1 withToken:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)refreshCaptcha:(CDUnknownBlockType)arg1;
- (void)loginWithMobile:(id)arg1 smsCode:(id)arg2 completedHandler:(CDUnknownBlockType)arg3;
- (void)sendSmsCodeForLogin:(id)arg1 captchaId:(id)arg2 captchaCode:(id)arg3 completedHandler:(CDUnknownBlockType)arg4;
- (_Bool)newV2;
- (id)smsCodeForApple;
- (id)userProfileForApple;

@end

