//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface OPCImageManager : NSObject
{
    NSMutableDictionary *_serverDict;
    NSMutableSet *_cacheKeySet;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableSet *cacheKeySet; // @synthesize cacheKeySet=_cacheKeySet;
@property(retain, nonatomic) NSMutableDictionary *serverDict; // @synthesize serverDict=_serverDict;
- (void).cxx_destruct;
- (id)getServerItemWithKey:(id)arg1;
- (long long)urlSizeScale:(struct CGSize)arg1;
- (id)imageUrlWithOriUrl:(id)arg1 ImageSize:(struct CGSize)arg2 cutType:(long long)arg3 qualityType:(long long)arg4;
- (id)imageUrlWithOriUrl:(id)arg1 ImageSize:(struct CGSize)arg2;
- (void)saveCacheKeyData;
- (void)onApplicationDidEnterBackgroundNotification:(id)arg1;
- (id)cacheKeyFilePath;
- (double)findCacheImageWidthWithPreffix:(id)arg1 size:(struct CGSize)arg2;
- (void)unRegisterServerItemWithKey:(id)arg1;
- (void)registerServerItem:(id)arg1;
- (void)clearCacheKey;
- (id)sdCacheKeyWithURL:(id)arg1;
- (void)configSDCacheKey;
- (void)setupDiskCacheFiles;
- (void)addNotification;
- (void)dealloc;
- (id)init;

@end

