//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPCImageServerItem : NSObject
{
    NSString *_source;
    NSString *_target;
    NSString *_opListKey;
}

+ (id)serverItemWithSource:(id)arg1 target:(id)arg2 opListKey:(id)arg3;
+ (id)serverItemWithSource:(id)arg1;
@property(copy, nonatomic) NSString *opListKey; // @synthesize opListKey=_opListKey;
@property(copy, nonatomic) NSString *target; // @synthesize target=_target;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
- (void).cxx_destruct;

@end

