//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPAccountLoginInterface-Protocol.h"

@class NSMutableArray, NSString;
@protocol OPCAccountLoginExtraTaskProtocl;

@interface OPCLoginInterface : NSObject <OPAccountLoginInterface>
{
    NSMutableArray *_extraTasks;
    id <OPCAccountLoginExtraTaskProtocl> _currentExcutingTask;
}

@property(nonatomic) __weak id <OPCAccountLoginExtraTaskProtocl> currentExcutingTask; // @synthesize currentExcutingTask=_currentExcutingTask;
@property(retain, nonatomic) NSMutableArray *extraTasks; // @synthesize extraTasks=_extraTasks;
- (void).cxx_destruct;
- (void)executeExtraTaskIfNeedWithAccountTicket:(id)arg1 withUserProfile:(id)arg2 withInfo:(id)arg3 withTaskIndex:(long long)arg4 withCompletion:(CDUnknownBlockType)arg5;
- (void)addTaskForLoginCompleted:(id)arg1;
- (id)logoutWithCompleteHandler:(CDUnknownBlockType)arg1;
- (id)loginByThirdAccountWithOpenId:(id)arg1 token:(id)arg2 loginPlugin:(id)arg3 userInfo:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)loginByMobile:(id)arg1 smsCode:(id)arg2 userInfo:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (_Bool)debugRegister;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

