//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIView;

@interface OPCornerPopViewItem : NSObject
{
    double _height;
    UIView *_itemView;
    NSString *_title;
    CDUnknownBlockType _clickAction;
}

@property(copy, nonatomic) CDUnknownBlockType clickAction; // @synthesize clickAction=_clickAction;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *itemView; // @synthesize itemView=_itemView;
@property(nonatomic) double height; // @synthesize height=_height;
- (void).cxx_destruct;

@end

