//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIImage, UIImageView, UIScrollView;

@interface OPCropImageViewController : UIViewController <UIScrollViewDelegate>
{
    _Bool _ovalClip;
    CDUnknownBlockType _finishCropImageBlock;
    CDUnknownBlockType _cancelCropImageBlock;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UIImage *_originalImage;
}

@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) CDUnknownBlockType cancelCropImageBlock; // @synthesize cancelCropImageBlock=_cancelCropImageBlock;
@property(copy, nonatomic) CDUnknownBlockType finishCropImageBlock; // @synthesize finishCropImageBlock=_finishCropImageBlock;
@property(nonatomic) _Bool ovalClip; // @synthesize ovalClip=_ovalClip;
- (void).cxx_destruct;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)centerContent;
- (id)cropImage;
- (void)doneBtnClick;
- (void)cancelBtnClick;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)userInterface;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

