//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPCSharePlugin.h"

@interface OPCShareTikTokPlugin : OPCSharePlugin
{
    _Bool _hasRegisterSDK;
}

+ (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
+ (id)pluginType;
- (void)fetchAccessTokenComplete:(CDUnknownBlockType)arg1;
- (void)fetchShareIdComplete:(CDUnknownBlockType)arg1;
- (void)shareWithAssetId:(id)arg1 hastag:(id)arg2 shareId:(id)arg3 completed:(CDUnknownBlockType)arg4;
- (void)shareForceGetShareIdThenAssetId:(id)arg1 hastag:(id)arg2 completed:(CDUnknownBlockType)arg3;
- (void)registerTiktokOpenIfNeed;
- (void)shareWithAssetId:(id)arg1 hastag:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)postData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)status;
- (id)init;

@end

