//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

#import "OPCInteractUserSubscribedObserver-Protocol.h"

@class NSDictionary, NSString, OPUserProfile;

@interface OPCSubscriptionButton : UIButton <OPCInteractUserSubscribedObserver>
{
    _Bool _onlyDoSubcribed;
    OPUserProfile *_userProfile;
    NSString *_spmUrl;
    NSDictionary *_info;
    CDUnknownBlockType _subscriptionStatusDidChanged;
}

@property(copy, nonatomic) CDUnknownBlockType subscriptionStatusDidChanged; // @synthesize subscriptionStatusDidChanged=_subscriptionStatusDidChanged;
@property(copy, nonatomic) NSDictionary *info; // @synthesize info=_info;
@property(copy, nonatomic) NSString *spmUrl; // @synthesize spmUrl=_spmUrl;
@property(nonatomic) _Bool onlyDoSubcribed; // @synthesize onlyDoSubcribed=_onlyDoSubcribed;
@property(retain, nonatomic) OPUserProfile *userProfile; // @synthesize userProfile=_userProfile;
- (void).cxx_destruct;
- (void)statClickFollowWithSpmUrl:(id)arg1 withFollowAction:(_Bool)arg2;
- (void)onClick;
- (struct CGSize)folowButtonSize;
- (void)updateFollowStatus:(long long)arg1;
- (void)updateStatus;
- (void)subscriptionFailed:(id)arg1 userId:(id)arg2 followStatus:(long long)arg3;
- (void)subscriptionStatusChanged:(unsigned long long)arg1 userId:(id)arg2 followStatus:(long long)arg3;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withUserProfile:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

