//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "OPSNavigationModalPresentViewControllerProtocol-Protocol.h"

@class NSDictionary, NSMutableArray, NSNumber, NSString, OPCShareData, UIView;

@interface OPCShareViewController : UIViewController <OPSNavigationModalPresentViewControllerProtocol>
{
    UIView *_contentView;
    UIView *_backgroundView;
    OPCShareData *_shareData;
    CDUnknownBlockType _canStartShare;
    CDUnknownBlockType _startShare;
    CDUnknownBlockType _didFinishShare;
    long long _statType;
    NSString *_statScene;
    NSNumber *_statIsOwner;
    NSDictionary *_statInfo;
    NSMutableArray *_avalidPlugins;
}

+ (void)onShareCompleted:(_Bool)arg1 response:(id)arg2 plugin:(id)arg3;
+ (void)onShareWillStart;
@property(retain, nonatomic) NSMutableArray *avalidPlugins; // @synthesize avalidPlugins=_avalidPlugins;
@property(copy, nonatomic) NSDictionary *statInfo; // @synthesize statInfo=_statInfo;
@property(copy, nonatomic) NSNumber *statIsOwner; // @synthesize statIsOwner=_statIsOwner;
@property(copy, nonatomic) NSString *statScene; // @synthesize statScene=_statScene;
@property(nonatomic) long long statType; // @synthesize statType=_statType;
@property(copy, nonatomic) CDUnknownBlockType didFinishShare; // @synthesize didFinishShare=_didFinishShare;
@property(copy, nonatomic) CDUnknownBlockType startShare; // @synthesize startShare=_startShare;
@property(copy, nonatomic) CDUnknownBlockType canStartShare; // @synthesize canStartShare=_canStartShare;
@property(retain, nonatomic) OPCShareData *shareData; // @synthesize shareData=_shareData;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)statClickPlugin:(id)arg1;
- (void)statPV;
- (_Bool)needDimissWhenShareStart;
- (void)bgCancel;
- (void)makeContentViewEffect;
- (void)viewDidLoad;
- (void)startShare:(id)arg1;
- (id)plugins;
- (void)viewDidAppear:(_Bool)arg1;
- (id)pluginKeysWithType:(unsigned long long)arg1;
- (id)initWithData:(id)arg1 withPluginType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

