//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPCUploadOSSTokenService : NSObject
{
}

- (void)uploadToken:(CDUnknownBlockType)arg1;
- (id)signWithApp:(id)arg1 tm:(id)arg2;
- (id)timeStamp;
- (id)app;
- (id)finalRequestUrl;
- (id)addrPath;

@end

