//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIImage, UIImageView;
@protocol OPUserProfileProtocol;

@interface OPCUserAvatarView : UIControl
{
    _Bool _showVip;
    _Bool _showBorder;
    _Bool _hasLoadAvatarImage;
    UIImageView *_avatarView;
    UIImageView *_vipView;
    UIImage *_avatarDefaultImage;
    id <OPUserProfileProtocol> _userItem;
    double _borderWidth;
    CDUnknownBlockType _loadNetImageComplete;
    struct CGSize _loadAvatarSize;
}

@property(nonatomic) _Bool hasLoadAvatarImage; // @synthesize hasLoadAvatarImage=_hasLoadAvatarImage;
@property(copy, nonatomic) CDUnknownBlockType loadNetImageComplete; // @synthesize loadNetImageComplete=_loadNetImageComplete;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) _Bool showBorder; // @synthesize showBorder=_showBorder;
@property(nonatomic) _Bool showVip; // @synthesize showVip=_showVip;
@property(nonatomic) struct CGSize loadAvatarSize; // @synthesize loadAvatarSize=_loadAvatarSize;
@property(retain, nonatomic) id <OPUserProfileProtocol> userItem; // @synthesize userItem=_userItem;
@property(retain, nonatomic) UIImage *avatarDefaultImage; // @synthesize avatarDefaultImage=_avatarDefaultImage;
@property(retain, nonatomic) UIImageView *vipView; // @synthesize vipView=_vipView;
@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (void)loadAvatarImage;
@property(readonly, nonatomic) UIImage *avatarImage;
- (void)updateVipView;
- (void)updateBorderStatus;
- (void)layoutSubviews;
- (void)initContentView;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

