//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

#import "OPCUserBlockManagerObserver-Protocol.h"

@class NSString, OPUserProfile;

@interface OPCUserBlockButton : UIButton <OPCUserBlockManagerObserver>
{
    _Bool _canShowFailedTips;
    OPUserProfile *_userProfile;
    NSString *_spmUrl;
}

@property(nonatomic) _Bool canShowFailedTips; // @synthesize canShowFailedTips=_canShowFailedTips;
@property(copy, nonatomic) NSString *spmUrl; // @synthesize spmUrl=_spmUrl;
@property(retain, nonatomic) OPUserProfile *userProfile; // @synthesize userProfile=_userProfile;
- (void).cxx_destruct;
- (void)onClick;
- (void)updateStatus;
- (void)unBlockUser:(id)arg1 completed:(_Bool)arg2 error:(id)arg3;
- (void)blockUser:(id)arg1 completed:(_Bool)arg2 error:(id)arg3;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withUserProfile:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

