//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"
#import "NSURLSessionDownloadDelegate-Protocol.h"

@class NSLock, NSMutableDictionary, NSString, NSURLSession;

@interface OPDownloadManager : NSObject <NSURLSessionDelegate, NSURLSessionDownloadDelegate>
{
    CDUnknownBlockType _backgroundTransferCompletionHandler;
    NSURLSession *_session;
    NSMutableDictionary *_downloads;
    NSLock *_downloadsLock;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSLock *downloadsLock; // @synthesize downloadsLock=_downloadsLock;
@property(retain, nonatomic) NSMutableDictionary *downloads; // @synthesize downloads=_downloads;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(copy, nonatomic) CDUnknownBlockType backgroundTransferCompletionHandler; // @synthesize backgroundTransferCompletionHandler=_backgroundTransferCompletionHandler;
- (void).cxx_destruct;
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(id)arg1;
- (void)cleanTmpDirectory;
- (void)cleanDirectoryNamed:(id)arg1;
- (_Bool)deleteFileWithName:(id)arg1 inDirectory:(id)arg2;
- (_Bool)deleteFileWithName:(id)arg1;
- (_Bool)deleteFileForUrl:(id)arg1 inDirectory:(id)arg2;
- (_Bool)deleteFileForUrl:(id)arg1;
- (_Bool)fileExistsWithName:(id)arg1;
- (_Bool)fileExistsWithName:(id)arg1 inCustomDirectoryFilePath:(id)arg2;
- (_Bool)fileExistsWithName:(id)arg1 inDirectory:(id)arg2;
- (_Bool)fileExistsForUrl:(id)arg1 inDirectory:(id)arg2;
- (_Bool)fileExistsForUrl:(id)arg1;
- (id)localPathForFile:(id)arg1 inDirectory:(id)arg2;
- (id)localPathForFile:(id)arg1;
- (_Bool)isFileDownloadingForUrl:(id)arg1 withProgressBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (_Bool)isFileDownloadingForUrl:(id)arg1 withProgressBlock:(CDUnknownBlockType)arg2;
- (_Bool)isFileDownloadingForUrl:(id)arg1;
- (id)cachesDirectoryUrlPath;
- (_Bool)createCustomDirectoryNamed:(id)arg1;
- (_Bool)createDirectoryNamed:(id)arg1;
- (double)remainingTimeForDownload:(id)arg1 bytesTransferred:(long long)arg2 totalBytesExpectedToWrite:(long long)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (id)currentDownloads;
- (void)cancelAllDownloads;
- (void)cancelDownloadForUrl:(id)arg1;
- (void)downloadFileForURL:(id)arg1 withName:(id)arg2 withFileDirectoryPath:(id)arg3 inDirectoryNamed:(id)arg4 friendlyName:(id)arg5 progressBlock:(CDUnknownBlockType)arg6 remainingTime:(CDUnknownBlockType)arg7 completionBlock:(CDUnknownBlockType)arg8;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

