//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIImageView;

@interface OPMicrophoneAnimationView : UIView
{
    _Bool _mute;
    UIColor *_voiceColor;
    double _voice;
    UIImageView *_microShellView;
    UIView *_voiceFillView;
    UIView *_voiceAnimationView;
}

@property(retain, nonatomic) UIView *voiceAnimationView; // @synthesize voiceAnimationView=_voiceAnimationView;
@property(retain, nonatomic) UIView *voiceFillView; // @synthesize voiceFillView=_voiceFillView;
@property(retain, nonatomic) UIImageView *microShellView; // @synthesize microShellView=_microShellView;
@property(nonatomic) _Bool mute; // @synthesize mute=_mute;
@property(nonatomic) double voice; // @synthesize voice=_voice;
@property(retain, nonatomic) UIColor *voiceColor; // @synthesize voiceColor=_voiceColor;
- (void).cxx_destruct;
- (void)layoutAnimationView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

