//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor, UIImage;

@interface OPNotificationItem : NSObject
{
    _Bool _tapDismiss;
    _Bool _needToLocalPush;
    _Bool _needToInAppNotification;
    NSString *_itemID;
    double _createTime;
    double _dismissTimeInterval;
    NSString *_iconURL;
    UIImage *_placeHolderIcon;
    UIColor *_iconBorderColor;
    double _iconBorderWidth;
    NSString *_title;
    NSString *_subTitle;
    NSString *_soundID;
    NSString *_url;
    Class _styleVCClass;
    unsigned long long _priority;
    CDUnknownBlockType _dismissBlock;
    CDUnknownBlockType _iconTapBlock;
    CDUnknownBlockType _tapBlock;
    CDUnknownBlockType _notificationDidPresentBlock;
    CDUnknownBlockType _appBecomeActiveBlock;
}

@property(copy, nonatomic) CDUnknownBlockType appBecomeActiveBlock; // @synthesize appBecomeActiveBlock=_appBecomeActiveBlock;
@property(copy, nonatomic) CDUnknownBlockType notificationDidPresentBlock; // @synthesize notificationDidPresentBlock=_notificationDidPresentBlock;
@property(nonatomic) _Bool needToInAppNotification; // @synthesize needToInAppNotification=_needToInAppNotification;
@property(nonatomic) _Bool needToLocalPush; // @synthesize needToLocalPush=_needToLocalPush;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(nonatomic) _Bool tapDismiss; // @synthesize tapDismiss=_tapDismiss;
@property(copy, nonatomic) CDUnknownBlockType iconTapBlock; // @synthesize iconTapBlock=_iconTapBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(nonatomic) Class styleVCClass; // @synthesize styleVCClass=_styleVCClass;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *soundID; // @synthesize soundID=_soundID;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double iconBorderWidth; // @synthesize iconBorderWidth=_iconBorderWidth;
@property(retain, nonatomic) UIColor *iconBorderColor; // @synthesize iconBorderColor=_iconBorderColor;
@property(retain, nonatomic) UIImage *placeHolderIcon; // @synthesize placeHolderIcon=_placeHolderIcon;
@property(copy, nonatomic) NSString *iconURL; // @synthesize iconURL=_iconURL;
@property(nonatomic) double dismissTimeInterval; // @synthesize dismissTimeInterval=_dismissTimeInterval;
@property(readonly, nonatomic) double createTime; // @synthesize createTime=_createTime;
@property(readonly, copy, nonatomic) NSString *itemID; // @synthesize itemID=_itemID;
- (void).cxx_destruct;
- (id)init;

@end

