//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary, UIWindow;

@interface OPNotificationManager : NSObject
{
    _Bool _enable;
    NSMutableArray *_vcs;
    NSMutableDictionary *_backgroundItemDic;
    NSMutableArray *_notificationItemsWhenDisable;
    UIWindow *_overlayWindow;
    double _overLayWindowLevel;
}

+ (_Bool)isNeedToSendLocalPush;
+ (id)shareManager;
@property(nonatomic) double overLayWindowLevel; // @synthesize overLayWindowLevel=_overLayWindowLevel;
@property(retain, nonatomic) UIWindow *overlayWindow; // @synthesize overlayWindow=_overlayWindow;
@property(retain, nonatomic) NSMutableArray *notificationItemsWhenDisable; // @synthesize notificationItemsWhenDisable=_notificationItemsWhenDisable;
@property(retain, nonatomic) NSMutableDictionary *backgroundItemDic; // @synthesize backgroundItemDic=_backgroundItemDic;
@property(retain, nonatomic) NSMutableArray *vcs; // @synthesize vcs=_vcs;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (void)showStoreItem;
- (void)storeItemWhenDisable:(id)arg1;
- (void)enableShowOPNotification:(_Bool)arg1;
- (void)dismissViewController:(id)arg1;
- (void)showSystemBackgroundNotification:(id)arg1;
- (void)showOPNotification:(id)arg1;
- (void)createOverLayWindow;
- (id)init;
- (void)appActiveWithItemID:(id)arg1;
- (void)showOPNotificationWithItemID:(id)arg1;

@end

