//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPNotificationItem.h"

@class NSString;

@interface OPNotificationInvitedItem : OPNotificationItem
{
    CDUnknownBlockType _acceptBlock;
    CDUnknownBlockType _denyBlock;
    NSString *_statType;
}

@property(copy, nonatomic) NSString *statType; // @synthesize statType=_statType;
@property(copy, nonatomic) CDUnknownBlockType denyBlock; // @synthesize denyBlock=_denyBlock;
@property(copy, nonatomic) CDUnknownBlockType acceptBlock; // @synthesize acceptBlock=_acceptBlock;
- (void).cxx_destruct;
- (id)init;

@end

