//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, OPCircleProgressView, OPLoadingIndicator, UIButton, UILabel;

@interface OPProgressHUD : UIView
{
    long long _progressType;
    CDUnknownBlockType _dimissedCallbackBlock;
    UIView *_contentView;
    UIView *_topContentView;
    OPLoadingIndicator *_loadingView;
    OPCircleProgressView *_progressBarView;
    UILabel *_titleLabel;
    UIButton *_cancelButton;
    UIButton *_confirmButton;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) OPCircleProgressView *progressBarView; // @synthesize progressBarView=_progressBarView;
@property(retain, nonatomic) OPLoadingIndicator *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIView *topContentView; // @synthesize topContentView=_topContentView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) CDUnknownBlockType dimissedCallbackBlock; // @synthesize dimissedCallbackBlock=_dimissedCallbackBlock;
@property(nonatomic) long long progressType; // @synthesize progressType=_progressType;
- (void).cxx_destruct;
@property(nonatomic) double progress;
@property(readonly, nonatomic) _Bool showing;
- (void)setFrame:(struct CGRect)arg1;
- (void)onButtonClicked:(id)arg1;
- (void)dismissWithIndex:(long long)arg1 animated:(_Bool)arg2 type:(long long)arg3;
- (void)dismiss:(_Bool)arg1;
- (void)showInView:(id)arg1 animated:(_Bool)arg2 dismissAfterSeconds:(double)arg3 afterPresented:(CDUnknownBlockType)arg4;
- (void)showInView:(id)arg1 animated:(_Bool)arg2 dismissAfterSeconds:(double)arg3;
- (id)initWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 confirmButtonTitle:(id)arg3;
- (void)dealloc;

@end

