//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, NSTimer, OPTouchBounceButton, UILabel, UITextField, UIView;

@interface OPRAccountVerifyMobileViewController : OPRBaseViewController <UITextFieldDelegate>
{
    _Bool _isCountDown;
    CDUnknownBlockType _completedHandler;
    CDUnknownBlockType _cancelHandler;
    NSString *_mobile;
    NSString *_smsRequestId;
    UIView *_checkCodeContainer;
    UITextField *_codeInput;
    OPTouchBounceButton *_getCodeBtn;
    UILabel *_codeReceiveTips;
    OPTouchBounceButton *_nextBtn;
    NSTimer *_timer;
    long long _restTime;
}

+ (id)lastSmsRequestId;
+ (void)updateLastSmsRequestId:(id)arg1;
+ (void)updateLastGetTime:(id)arg1;
+ (long long)timeFromLastGet;
@property(nonatomic) long long restTime; // @synthesize restTime=_restTime;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool isCountDown; // @synthesize isCountDown=_isCountDown;
@property(retain, nonatomic) OPTouchBounceButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(retain, nonatomic) UILabel *codeReceiveTips; // @synthesize codeReceiveTips=_codeReceiveTips;
@property(retain, nonatomic) OPTouchBounceButton *getCodeBtn; // @synthesize getCodeBtn=_getCodeBtn;
@property(retain, nonatomic) UITextField *codeInput; // @synthesize codeInput=_codeInput;
@property(retain, nonatomic) UIView *checkCodeContainer; // @synthesize checkCodeContainer=_checkCodeContainer;
@property(copy, nonatomic) NSString *smsRequestId; // @synthesize smsRequestId=_smsRequestId;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) CDUnknownBlockType cancelHandler; // @synthesize cancelHandler=_cancelHandler;
@property(copy, nonatomic) CDUnknownBlockType completedHandler; // @synthesize completedHandler=_completedHandler;
- (void).cxx_destruct;
- (void)statPageToLogserver:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)updateCountDownStatus;
- (void)onTimerToCountDown;
- (void)stopToCountDown;
- (void)startToCountDown:(long long)arg1;
- (void)onNextBtnClick;
- (void)onGetCodeBtnClick;
- (void)onBackButtonClick;
- (void)onBackgroundClick;
- (void)setupCheckCodeView:(id)arg1;
- (void)setupContentView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (id)initWithMobile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

