//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, CALayer, CAShapeLayer;

@interface OPRAudioEditPreviewViewBGView : UIView
{
    CALayer *_shadowLayer;
    CAGradientLayer *_bgLayer;
    CAShapeLayer *_maskLayer;
    CAGradientLayer *_borderLayer;
}

@property(nonatomic) __weak CAGradientLayer *borderLayer; // @synthesize borderLayer=_borderLayer;
@property(nonatomic) __weak CAShapeLayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(nonatomic) __weak CAGradientLayer *bgLayer; // @synthesize bgLayer=_bgLayer;
@property(nonatomic) __weak CALayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
- (void).cxx_destruct;
- (void)updateBorderLayer;
- (void)updateMaskLayer;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

