//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPTouchBounceButton.h"

@class CAGradientLayer, CALayer, UILabel, UIView;

@interface OPRAudioEditAudioTrackItemView : OPTouchBounceButton
{
    CDUnknownBlockType _clickAction;
    CAGradientLayer *_gradientLayer;
    CAGradientLayer *_centerCircleLayer;
    CALayer *_shadowLayer;
    UILabel *_tipsLabel;
    double _circleWidth;
    UIView *_tagView;
}

@property(nonatomic) __weak UIView *tagView; // @synthesize tagView=_tagView;
@property(nonatomic) double circleWidth; // @synthesize circleWidth=_circleWidth;
@property(nonatomic) __weak UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(nonatomic) __weak CALayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
@property(nonatomic) __weak CAGradientLayer *centerCircleLayer; // @synthesize centerCircleLayer=_centerCircleLayer;
@property(nonatomic) __weak CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(copy, nonatomic) CDUnknownBlockType clickAction; // @synthesize clickAction=_clickAction;
- (void).cxx_destruct;
- (void)updateTipsLabelLayout;
- (void)updateTipsNum:(id)arg1;
- (void)updateImageAndTextFrame;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

