//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRWebViewController.h"

@class NSString;

@interface OPRAccountBindMobileViewController : OPRWebViewController
{
    _Bool _isRebinding;
    CDUnknownBlockType _completedHandler;
    CDUnknownBlockType _cancelHandler;
    NSString *_entry;
}

+ (void)statToLogserver:(id)arg1 ct:(id)arg2 ac:(id)arg3;
+ (void)statPageToLogserver:(id)arg1;
+ (_Bool)alertForBindingMobileIfNeed:(id)arg1 cancelHandler:(CDUnknownBlockType)arg2 completedHandler:(CDUnknownBlockType)arg3;
+ (_Bool)canBindByAccountCenter;
+ (unsigned long long)debugSwitchBindPhone;
@property(nonatomic) _Bool isRebinding; // @synthesize isRebinding=_isRebinding;
@property(copy, nonatomic) NSString *entry; // @synthesize entry=_entry;
@property(copy, nonatomic) CDUnknownBlockType cancelHandler; // @synthesize cancelHandler=_cancelHandler;
@property(copy, nonatomic) CDUnknownBlockType completedHandler; // @synthesize completedHandler=_completedHandler;
- (void).cxx_destruct;
- (void)onBackButtonClick;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2;
- (id)title;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithIsRebinding:(_Bool)arg1 st:(id)arg2;
- (id)initWithRebinding;
- (id)initWithBindingEntry:(id)arg1;

@end

