//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPRAudioPostContentStat : NSObject
{
}

+ (void)statClickPushForCommentMessageForeground:(_Bool)arg1;
+ (void)statClickPushForLikeMessageForeground:(_Bool)arg1;
+ (void)statClickAudioPostContentLikeListAvatarWithScene:(id)arg1;
+ (void)statClickAudioPostContentAuthorAvatarWithScene:(id)arg1;
+ (void)statClickAudioPostContentShareWithScene:(id)arg1;
+ (void)statClickSameSingWithSongInfo:(id)arg1 withEnrty:(id)arg2;
+ (void)statPVForAudioPostContentCommentReplyPageWithEnrty:(id)arg1;
+ (void)statPVForAudioPostContentWithEnrty:(id)arg1 withSongInfo:(id)arg2;

@end

