//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewLayoutAttributes.h>

@class UIColor;

@interface OPRAudioEditABPOLayoutAttributes : UICollectionViewLayoutAttributes
{
    unsigned long long _corners;
    double _cornerRadius;
    UIColor *_backgroundColor;
}

+ (id)layoutAttributesForDecorationViewOfKind:(id)arg1 withIndexPath:(id)arg2;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) unsigned long long corners; // @synthesize corners=_corners;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;

@end

