//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIButton, UIColor;

@interface OPRAudioEditBaseSliderTitleCell : UICollectionViewCell
{
    _Bool _needHighLightSelected;
    UIButton *_titleButton;
    UIColor *_themeColor;
}

@property(nonatomic) _Bool needHighLightSelected; // @synthesize needHighLightSelected=_needHighLightSelected;
@property(retain, nonatomic) UIColor *themeColor; // @synthesize themeColor=_themeColor;
@property(nonatomic) __weak UIButton *titleButton; // @synthesize titleButton=_titleButton;
- (void).cxx_destruct;
- (void)bindStyleButton:(id)arg1 status:(_Bool)arg2;

@end

