//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, OPRAudioEditBaseSlideView, UIView;

@protocol OPRAudioEditBaseSlideViewDelegate <NSObject>
- (NSString *)opr_ae_base_sliderView:(OPRAudioEditBaseSlideView *)arg1 titleForItemAtIndex:(long long)arg2;
- (UIView *)opr_ae_base_sliderView:(OPRAudioEditBaseSlideView *)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsInOPRAudioEditBaseSlideView:(OPRAudioEditBaseSlideView *)arg1;

@optional
- (void)opr_ae_base_slideViewSwitchedToIndex:(long long)arg1;
- (long long)initialzeIndexForOPRAudioEditBaseSlideView:(OPRAudioEditBaseSlideView *)arg1;
@end

