//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPCInteractContentItem.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSString, OPRSongExtendData, OPRSongPlayInstrumentRecordData, OPRSoundEffectRecordData, OPUserProfile;

@interface OPRAudioContentItem : OPCInteractContentItem <NSCoding>
{
    _Bool _isEnsemble;
    _Bool _canEnsemble;
    _Bool _canRecord;
    _Bool _recorded;
    OPUserProfile *_user;
    NSString *_audioId;
    NSString *_ossId;
    NSString *_audioUrl;
    NSNumber *_audioDuration;
    NSString *_publishTime;
    NSNumber *_originalSing;
    NSString *_audioFilterType;
    NSNumber *_ugcStatus;
    NSString *_segmentId;
    NSString *_songName;
    NSString *_lyric;
    NSString *_artist;
    NSNumber *_segmentDuration;
    NSNumber *_audioCount;
    NSNumber *_clipType;
    NSNumber *_segmentReviewResult;
    OPUserProfile *_segmentAuthor;
    NSString *_songListId;
    OPRSongExtendData *_extendData;
    OPRSongPlayInstrumentRecordData *_chordRecordData;
    OPRSongPlayInstrumentRecordData *_beatRecordData;
    OPRSoundEffectRecordData *_effectRecordData;
    NSString *_audioDesc;
    NSString *_audioDescWithTopic;
    NSArray *_topicIds;
    NSNumber *_ugcType;
    NSNumber *_ensembleScore;
    OPRAudioContentItem *_ensembleLeadingItem;
    NSString *_displayText;
    NSString *_recordEnsembleId;
    OPUserProfile *_recordEnsembleUser;
    OPRAudioContentItem *_recordEnsembleItem;
    NSString *_cursor;
    NSString *_recommendId;
    NSNumber *_recommendStrategy;
    NSDictionary *_otherStatInfo;
}

+ (id)itemInTopicClipWithData:(id)arg1;
+ (id)itemWithClipAndUserInfoData:(id)arg1 sycFollowStatus:(_Bool)arg2;
+ (id)itemWithClipAndUserInfoData:(id)arg1;
@property(retain, nonatomic) NSDictionary *otherStatInfo; // @synthesize otherStatInfo=_otherStatInfo;
@property(copy, nonatomic) NSNumber *recommendStrategy; // @synthesize recommendStrategy=_recommendStrategy;
@property(copy, nonatomic) NSString *recommendId; // @synthesize recommendId=_recommendId;
@property(copy, nonatomic) NSString *cursor; // @synthesize cursor=_cursor;
@property(retain, nonatomic) OPRAudioContentItem *recordEnsembleItem; // @synthesize recordEnsembleItem=_recordEnsembleItem;
@property(retain, nonatomic) OPUserProfile *recordEnsembleUser; // @synthesize recordEnsembleUser=_recordEnsembleUser;
@property(retain, nonatomic) NSString *recordEnsembleId; // @synthesize recordEnsembleId=_recordEnsembleId;
@property(nonatomic) _Bool recorded; // @synthesize recorded=_recorded;
@property(nonatomic) _Bool canRecord; // @synthesize canRecord=_canRecord;
@property(retain, nonatomic) NSString *displayText; // @synthesize displayText=_displayText;
@property(nonatomic) _Bool canEnsemble; // @synthesize canEnsemble=_canEnsemble;
@property(retain, nonatomic) OPRAudioContentItem *ensembleLeadingItem; // @synthesize ensembleLeadingItem=_ensembleLeadingItem;
@property(retain, nonatomic) NSNumber *ensembleScore; // @synthesize ensembleScore=_ensembleScore;
@property(nonatomic) _Bool isEnsemble; // @synthesize isEnsemble=_isEnsemble;
@property(retain, nonatomic) NSNumber *ugcType; // @synthesize ugcType=_ugcType;
@property(copy, nonatomic) NSArray *topicIds; // @synthesize topicIds=_topicIds;
@property(copy, nonatomic) NSString *audioDescWithTopic; // @synthesize audioDescWithTopic=_audioDescWithTopic;
@property(copy, nonatomic) NSString *audioDesc; // @synthesize audioDesc=_audioDesc;
@property(retain, nonatomic) OPRSoundEffectRecordData *effectRecordData; // @synthesize effectRecordData=_effectRecordData;
@property(retain, nonatomic) OPRSongPlayInstrumentRecordData *beatRecordData; // @synthesize beatRecordData=_beatRecordData;
@property(retain, nonatomic) OPRSongPlayInstrumentRecordData *chordRecordData; // @synthesize chordRecordData=_chordRecordData;
@property(retain, nonatomic) OPRSongExtendData *extendData; // @synthesize extendData=_extendData;
@property(copy, nonatomic) NSString *songListId; // @synthesize songListId=_songListId;
@property(retain, nonatomic) OPUserProfile *segmentAuthor; // @synthesize segmentAuthor=_segmentAuthor;
@property(retain, nonatomic) NSNumber *segmentReviewResult; // @synthesize segmentReviewResult=_segmentReviewResult;
@property(retain, nonatomic) NSNumber *clipType; // @synthesize clipType=_clipType;
@property(retain, nonatomic) NSNumber *audioCount; // @synthesize audioCount=_audioCount;
@property(retain, nonatomic) NSNumber *segmentDuration; // @synthesize segmentDuration=_segmentDuration;
@property(copy, nonatomic) NSString *artist; // @synthesize artist=_artist;
@property(copy, nonatomic) NSString *lyric; // @synthesize lyric=_lyric;
@property(copy, nonatomic) NSString *songName; // @synthesize songName=_songName;
@property(copy, nonatomic) NSString *segmentId; // @synthesize segmentId=_segmentId;
@property(retain, nonatomic) NSNumber *ugcStatus; // @synthesize ugcStatus=_ugcStatus;
@property(copy, nonatomic) NSString *audioFilterType; // @synthesize audioFilterType=_audioFilterType;
@property(retain, nonatomic) NSNumber *originalSing; // @synthesize originalSing=_originalSing;
@property(copy, nonatomic) NSString *publishTime; // @synthesize publishTime=_publishTime;
@property(retain, nonatomic) NSNumber *audioDuration; // @synthesize audioDuration=_audioDuration;
@property(copy, nonatomic) NSString *audioUrl; // @synthesize audioUrl=_audioUrl;
@property(copy, nonatomic) NSString *ossId; // @synthesize ossId=_ossId;
@property(copy, nonatomic) NSString *audioId; // @synthesize audioId=_audioId;
@property(retain, nonatomic) OPUserProfile *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithClipData:(id)arg1 sycFollowStatus:(_Bool)arg2;
- (id)initWithClipData:(id)arg1;
@property(readonly, nonatomic) _Bool isRecord;
@property(readonly, nonatomic) _Bool isLeadingUGCAvailable;
@property(readonly, nonatomic) _Bool isAvailableForEffectPlayback;
@property(readonly, nonatomic) _Bool isAvailableForChordPlayback;
@property(readonly, nonatomic) _Bool isValidEnsembleType;
- (void)setFollowStatus:(long long)arg1;
- (long long)followStatus;
- (id)backgroundUrl;
- (id)avatarUrl;
- (unsigned long long)gender;
- (id)nickname;
- (id)userId;
- (id)logExt;
- (id)ugcType_interact;
- (id)recoid_interact;
- (id)strategy_interact;
- (id)segmentID_interact;
- (id)autorID_interact;
- (id)itemID_interact;
- (id)playStatInfoWithSongListId:(id)arg1 sequence:(long long)arg2;
@property(readonly, nonatomic) NSDictionary *audioStatInfo;

@end

