//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class OPRAudioDraftInfo;

@interface OPRAudioDraftManager : NSObject
{
    _Bool _showingBox;
    OPRAudioDraftInfo *_unfinishedInfo;
    OPRAudioDraftInfo *_currentInfo;
}

+ (id)defaultManager;
@property(nonatomic) _Bool showingBox; // @synthesize showingBox=_showingBox;
@property(retain, nonatomic) OPRAudioDraftInfo *currentInfo; // @synthesize currentInfo=_currentInfo;
@property(retain, nonatomic) OPRAudioDraftInfo *unfinishedInfo; // @synthesize unfinishedInfo=_unfinishedInfo;
- (void).cxx_destruct;
- (void)setBoxShow:(_Bool)arg1;
- (void)alertDidClose;
- (_Bool)showEditAutoSaveDataBox:(CDUnknownBlockType)arg1;
- (void)showExitEditVerifyBox:(CDUnknownBlockType)arg1;
- (id)audioEditControllerWithDraftInfo:(id)arg1;
- (id)draftInfoList;
- (long long)draftInfoListCount;
- (_Bool)autoSaveDraftInfoToLocal:(id)arg1;
- (_Bool)isCurrentDraftAutoSave;
- (_Bool)isDraftFull;
- (_Bool)isDraftEnable;
- (_Bool)finishDraft:(id)arg1 isSave:(_Bool)arg2;
- (_Bool)finishCurrentDraftEdit:(_Bool)arg1;
- (void)updateFilePath:(id)arg1 newFile:(id)arg2 remove:(_Bool)arg3;
- (void)updateDraftFile:(id)arg1 withNewContext:(id)arg2;
- (_Bool)saveDraftWithSegment:(id)arg1 withContext:(id)arg2;
- (id)init;

@end

