//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIScrollView;

@interface OPRAudioEditAudioVolumeView : UIView
{
    UIView *_contentView;
    UIScrollView *_parentScrollView;
}

@property(nonatomic) __weak UIScrollView *parentScrollView; // @synthesize parentScrollView=_parentScrollView;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)updateVolume:(float)arg1 withItemTitle:(id)arg2;
- (void)enableItem:(_Bool)arg1 withItemTitle:(id)arg2;
- (void)sizeToFit;
- (id)initWithFrame:(struct CGRect)arg1 items:(id)arg2;
- (void)didMoveToWindow;
- (void)removeFromSuperview;
- (void)dealloc;

@end

