//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface OPRAudioBPMData : NSObject <NSCopying, NSCoding>
{
    _Bool _isMessyBPM;
    _Bool _detectBPMSucceed;
    _Bool _didShowMessyBPMTips;
    _Bool _useRecommendBPMTips;
    NSArray *_recommendBeatOnsets;
    NSArray *_recommendDiffBeatOnsets;
    NSArray *_originalBPMs;
    NSArray *_optimizedBPMs;
    NSString *_detectBPMResultDataJsonStr;
}

+ (id)dataWithJsonStr:(id)arg1;
@property(nonatomic) _Bool useRecommendBPMTips; // @synthesize useRecommendBPMTips=_useRecommendBPMTips;
@property(nonatomic) _Bool didShowMessyBPMTips; // @synthesize didShowMessyBPMTips=_didShowMessyBPMTips;
@property(nonatomic) _Bool detectBPMSucceed; // @synthesize detectBPMSucceed=_detectBPMSucceed;
@property(nonatomic) _Bool isMessyBPM; // @synthesize isMessyBPM=_isMessyBPM;
@property(copy, nonatomic) NSString *detectBPMResultDataJsonStr; // @synthesize detectBPMResultDataJsonStr=_detectBPMResultDataJsonStr;
@property(retain, nonatomic) NSArray *optimizedBPMs; // @synthesize optimizedBPMs=_optimizedBPMs;
@property(retain, nonatomic) NSArray *originalBPMs; // @synthesize originalBPMs=_originalBPMs;
@property(retain, nonatomic) NSArray *recommendDiffBeatOnsets; // @synthesize recommendDiffBeatOnsets=_recommendDiffBeatOnsets;
@property(retain, nonatomic) NSArray *recommendBeatOnsets; // @synthesize recommendBeatOnsets=_recommendBeatOnsets;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

