//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString, OPRContentGeneratingContext, OPRSongSegmentData;

@interface OPRAudioDraftInfo : NSObject
{
    _Bool _isAutoSave;
    NSString *_infoId;
    NSDate *_lastModifyTime;
    OPRSongSegmentData *_segmentData;
    OPRContentGeneratingContext *_generatingContext;
}

@property(retain, nonatomic) OPRContentGeneratingContext *generatingContext; // @synthesize generatingContext=_generatingContext;
@property(retain, nonatomic) OPRSongSegmentData *segmentData; // @synthesize segmentData=_segmentData;
@property(nonatomic) _Bool isAutoSave; // @synthesize isAutoSave=_isAutoSave;
@property(retain, nonatomic) NSDate *lastModifyTime; // @synthesize lastModifyTime=_lastModifyTime;
@property(retain, nonatomic) NSString *infoId; // @synthesize infoId=_infoId;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

