//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface OPRAudioBPMDetectFeedbackData : NSObject
{
    _Bool _isMessyBPM;
    NSArray *_beatOnset;
    NSArray *_diffBeatOnset;
    NSArray *_originalBPMs;
    NSArray *_optimizedBPMs;
    NSString *_feedbackDataJsonStr;
}

@property(copy, nonatomic) NSString *feedbackDataJsonStr; // @synthesize feedbackDataJsonStr=_feedbackDataJsonStr;
@property(nonatomic) _Bool isMessyBPM; // @synthesize isMessyBPM=_isMessyBPM;
@property(retain, nonatomic) NSArray *optimizedBPMs; // @synthesize optimizedBPMs=_optimizedBPMs;
@property(retain, nonatomic) NSArray *originalBPMs; // @synthesize originalBPMs=_originalBPMs;
@property(retain, nonatomic) NSArray *diffBeatOnset; // @synthesize diffBeatOnset=_diffBeatOnset;
@property(retain, nonatomic) NSArray *beatOnset; // @synthesize beatOnset=_beatOnset;
- (void).cxx_destruct;

@end

