//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, UIScrollView;

@interface OPRAudioEditAudioTrackEditView : UIView
{
    double _maxContentHeight;
    UIView *_contentView;
    UILabel *_titleLabel;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double maxContentHeight; // @synthesize maxContentHeight=_maxContentHeight;
- (void).cxx_destruct;
- (void)updateTipsNum:(id)arg1 withItemIndex:(unsigned long long)arg2;
- (void)sizeToFit;
- (id)initWithFrame:(struct CGRect)arg1 items:(id)arg2;
- (void)dealloc;

@end

