//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString, OPRAggregationSegmentFeedbackData, OPRAggregationSingerInfo;

@interface OPRAggregationFeedbackData : NSObject
{
    _Bool _moreParticipant;
    NSString *_roomId;
    NSNumber *_roomType;
    NSNumber *_roomState;
    NSNumber *_currentRound;
    NSNumber *_currentTurn;
    NSNumber *_totalTurn;
    double _startTimeInteval;
    double _countTimeInteval;
    unsigned long long _participantCount;
    NSString *_roomOwner;
    NSArray *_participants;
    OPRAggregationSingerInfo *_singerInfo;
    NSArray *_albumList;
    OPRAggregationSegmentFeedbackData *_currentSegmentInfo;
}

@property(retain, nonatomic) OPRAggregationSegmentFeedbackData *currentSegmentInfo; // @synthesize currentSegmentInfo=_currentSegmentInfo;
@property(retain, nonatomic) NSArray *albumList; // @synthesize albumList=_albumList;
@property(retain, nonatomic) OPRAggregationSingerInfo *singerInfo; // @synthesize singerInfo=_singerInfo;
@property(retain, nonatomic) NSArray *participants; // @synthesize participants=_participants;
@property(copy, nonatomic) NSString *roomOwner; // @synthesize roomOwner=_roomOwner;
@property(nonatomic) unsigned long long participantCount; // @synthesize participantCount=_participantCount;
@property(nonatomic) _Bool moreParticipant; // @synthesize moreParticipant=_moreParticipant;
@property(nonatomic) double countTimeInteval; // @synthesize countTimeInteval=_countTimeInteval;
@property(nonatomic) double startTimeInteval; // @synthesize startTimeInteval=_startTimeInteval;
@property(retain, nonatomic) NSNumber *totalTurn; // @synthesize totalTurn=_totalTurn;
@property(retain, nonatomic) NSNumber *currentTurn; // @synthesize currentTurn=_currentTurn;
@property(retain, nonatomic) NSNumber *currentRound; // @synthesize currentRound=_currentRound;
@property(retain, nonatomic) NSNumber *roomState; // @synthesize roomState=_roomState;
@property(retain, nonatomic) NSNumber *roomType; // @synthesize roomType=_roomType;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
- (void).cxx_destruct;

@end

