//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface OPRChordInstrumentSubItem : NSObject <NSCoding, NSCopying>
{
    _Bool _shareUnlock;
    _Bool _isDefault;
    _Bool _isEnsembleDefault;
    _Bool _enableClap;
    _Bool _autoDownload;
    _Bool _isNew;
    NSString *_instrumentId;
    NSString *_name;
    NSString *_icon;
    NSNumber *_scene;
    NSArray *_playStyle;
}

@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
@property(retain, nonatomic) NSArray *playStyle; // @synthesize playStyle=_playStyle;
@property(retain, nonatomic) NSNumber *scene; // @synthesize scene=_scene;
@property(nonatomic) _Bool autoDownload; // @synthesize autoDownload=_autoDownload;
@property(nonatomic) _Bool enableClap; // @synthesize enableClap=_enableClap;
@property(nonatomic) _Bool isEnsembleDefault; // @synthesize isEnsembleDefault=_isEnsembleDefault;
@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(nonatomic) _Bool shareUnlock; // @synthesize shareUnlock=_shareUnlock;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *instrumentId; // @synthesize instrumentId=_instrumentId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

