//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface OPRCreateRoomFeedbackData : NSObject
{
    NSString *_roomId;
    NSNumber *_roomType;
    NSNumber *_roomState;
    NSString *_roomName;
    NSNumber *_userState;
    NSNumber *_roomRole;
    NSNumber *_currentRound;
    NSNumber *_inviteMode;
    double _startTimeInteval;
    double _countTimeInteval;
}

@property(nonatomic) double countTimeInteval; // @synthesize countTimeInteval=_countTimeInteval;
@property(nonatomic) double startTimeInteval; // @synthesize startTimeInteval=_startTimeInteval;
@property(retain, nonatomic) NSNumber *inviteMode; // @synthesize inviteMode=_inviteMode;
@property(retain, nonatomic) NSNumber *currentRound; // @synthesize currentRound=_currentRound;
@property(retain, nonatomic) NSNumber *roomRole; // @synthesize roomRole=_roomRole;
@property(retain, nonatomic) NSNumber *userState; // @synthesize userState=_userState;
@property(copy, nonatomic) NSString *roomName; // @synthesize roomName=_roomName;
@property(retain, nonatomic) NSNumber *roomState; // @synthesize roomState=_roomState;
@property(retain, nonatomic) NSNumber *roomType; // @synthesize roomType=_roomType;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
- (void).cxx_destruct;

@end

