//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface OPRContentGeneratingAnalysisAudioContext : NSObject <NSCoding>
{
    unsigned long long _playChordScore;
    NSString *_chordLevelText;
    NSString *_chordPromptText;
    unsigned long long _analysisResultType;
}

@property(nonatomic) unsigned long long analysisResultType; // @synthesize analysisResultType=_analysisResultType;
@property(copy, nonatomic) NSString *chordPromptText; // @synthesize chordPromptText=_chordPromptText;
@property(copy, nonatomic) NSString *chordLevelText; // @synthesize chordLevelText=_chordLevelText;
@property(nonatomic) unsigned long long playChordScore; // @synthesize playChordScore=_playChordScore;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

