//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPAccountManagerObserver-Protocol.h"

@class NSHashTable, NSString, NSTimer, OPRFollowFeedUnReadMsgItem, OPRUserFollowFeedService;

@interface OPRFollowFeedUnReadMsgManager : NSObject <OPAccountManagerObserver>
{
    OPRFollowFeedUnReadMsgItem *_unReadMsgItem;
    NSHashTable *_observerTable;
    OPRUserFollowFeedService *_queryUnReadMsgInfoService;
    NSTimer *_queryMsgTimer;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSTimer *queryMsgTimer; // @synthesize queryMsgTimer=_queryMsgTimer;
@property(retain, nonatomic) OPRUserFollowFeedService *queryUnReadMsgInfoService; // @synthesize queryUnReadMsgInfoService=_queryUnReadMsgInfoService;
@property(retain, nonatomic) NSHashTable *observerTable; // @synthesize observerTable=_observerTable;
@property(retain, nonatomic) OPRFollowFeedUnReadMsgItem *unReadMsgItem; // @synthesize unReadMsgItem=_unReadMsgItem;
- (void).cxx_destruct;
- (void)accountManager:(id)arg1 logerStatusChanged:(unsigned long long)arg2;
- (void)resetUnReadData;
- (void)didReadMsg;
- (void)refresh;
- (void)dispatchUnReadMsgDidRead;
- (void)dispatchUnReadMsgDidUpdate;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)init;
- (void)activeQueryMsgTimer;
- (void)setup;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

