//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface OPRFollowFeedUnReadMsgItem : NSObject
{
    NSNumber *_unReadMsgCount;
    NSArray *_unReadMsgUserAvatars;
    NSString *_theNewestUnReadMsgRelationId;
}

@property(retain, nonatomic) NSString *theNewestUnReadMsgRelationId; // @synthesize theNewestUnReadMsgRelationId=_theNewestUnReadMsgRelationId;
@property(retain, nonatomic) NSArray *unReadMsgUserAvatars; // @synthesize unReadMsgUserAvatars=_unReadMsgUserAvatars;
@property(retain, nonatomic) NSNumber *unReadMsgCount; // @synthesize unReadMsgCount=_unReadMsgCount;
- (void).cxx_destruct;

@end

