//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseViewController.h"

#import "YYTextViewDelegate-Protocol.h"

@class NSString, OPRTextField, YYTextView;

@interface OPRFeedbackViewController : OPRBaseViewController <YYTextViewDelegate>
{
    YYTextView *_inputView;
    OPRTextField *_contactField;
}

@property(retain, nonatomic) OPRTextField *contactField; // @synthesize contactField=_contactField;
@property(retain, nonatomic) YYTextView *inputView; // @synthesize inputView=_inputView;
- (void).cxx_destruct;
- (void)onMenuButtonClick:(id)arg1;
- (id)title;
- (void)saveContactWay;
- (id)getContactWay;
- (void)updateTextState:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

