//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface OPRInstrumentUseCellItem : NSObject
{
    long long _indentifer;
    id _data;
    NSString *_title;
    NSString *_value;
    NSNumber *_cellHeight;
}

@property(retain, nonatomic) NSNumber *cellHeight; // @synthesize cellHeight=_cellHeight;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(nonatomic) long long indentifer; // @synthesize indentifer=_indentifer;
- (void).cxx_destruct;

@end

