//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPRJsHandlerRequestModel : NSObject
{
    NSString *_msgId;
    NSString *_methodName;
    id _queryParams;
}

@property(copy, nonatomic) id queryParams; // @synthesize queryParams=_queryParams;
@property(copy, nonatomic) NSString *methodName; // @synthesize methodName=_methodName;
@property(copy, nonatomic) NSString *msgId; // @synthesize msgId=_msgId;
- (void).cxx_destruct;
- (id)initWithMessage:(id)arg1;

@end

