//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface OPRJoinRoomData : NSObject
{
    NSString *_upaasVid;
    NSString *_roomId;
    NSString *_joinType;
    NSNumber *_canJoinRace;
    NSString *_source;
    NSNumber *_hasFollow;
}

@property(retain, nonatomic) NSNumber *hasFollow; // @synthesize hasFollow=_hasFollow;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSNumber *canJoinRace; // @synthesize canJoinRace=_canJoinRace;
@property(copy, nonatomic) NSString *joinType; // @synthesize joinType=_joinType;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(copy, nonatomic) NSString *upaasVid; // @synthesize upaasVid=_upaasVid;
- (void).cxx_destruct;

@end

