//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString, OPUserProfile;

@interface OPRLeadingSingerInfoItem : NSObject <NSCoding, NSCopying>
{
    OPUserProfile *_user;
    NSString *_acapellaId;
    NSString *_audioId;
    NSString *_ossId;
    NSNumber *_strategy;
}

@property(copy, nonatomic) NSNumber *strategy; // @synthesize strategy=_strategy;
@property(copy, nonatomic) NSString *ossId; // @synthesize ossId=_ossId;
@property(copy, nonatomic) NSString *audioId; // @synthesize audioId=_audioId;
@property(copy, nonatomic) NSString *acapellaId; // @synthesize acapellaId=_acapellaId;
@property(retain, nonatomic) OPUserProfile *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)avatar;
- (id)name;
- (id)userId;

@end

