//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPRMVServiceQueryData : NSObject
{
    NSString *_audioId;
    NSString *_templateId;
    NSString *_renderVersion;
}

@property(copy, nonatomic) NSString *renderVersion; // @synthesize renderVersion=_renderVersion;
@property(copy, nonatomic) NSString *templateId; // @synthesize templateId=_templateId;
@property(copy, nonatomic) NSString *audioId; // @synthesize audioId=_audioId;
- (void).cxx_destruct;

@end

