//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseTableViewController.h"

#import "OPRMessageBoxContentCellDelegate-Protocol.h"

@class NSMutableArray, NSString, OPRMessageFolderItem, OPRMessageService;

@interface OPRMessageBoxContentViewController : OPRBaseTableViewController <OPRMessageBoxContentCellDelegate>
{
    _Bool _hasMore;
    _Bool _hasNew;
    _Bool _hasEnd;
    OPRMessageFolderItem *_folder;
    OPRMessageService *_service;
    NSMutableArray *_contentList;
    long long _offset;
}

@property(nonatomic) _Bool hasEnd; // @synthesize hasEnd=_hasEnd;
@property(nonatomic) _Bool hasNew; // @synthesize hasNew=_hasNew;
@property(nonatomic) long long offset; // @synthesize offset=_offset;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableArray *contentList; // @synthesize contentList=_contentList;
@property(retain, nonatomic) OPRMessageService *service; // @synthesize service=_service;
@property(retain, nonatomic) OPRMessageFolderItem *folder; // @synthesize folder=_folder;
- (void).cxx_destruct;
- (void)statControlToLogserver:(id)arg1;
- (void)statPageToLogserver:(id)arg1;
- (void)contentCell:(id)arg1 clickSender:(id)arg2;
- (void)showContentEmptyView:(_Bool)arg1;
- (void)loadMoreMessage;
- (void)refreshMessage;
- (void)appendContentList:(id)arg1 refresh:(_Bool)arg2;
- (_Bool)enableLoadMore;
- (_Bool)enableRefresh;
- (id)title;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithFolder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

