//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRMessageBoxContentCell.h"

@class OPCUserAvatarView, OPRMessageContentItem, UIImageView, UILabel;

@interface OPRMessageBoxContentNormalCell : OPRMessageBoxContentCell
{
    OPCUserAvatarView *_avatarView;
    UILabel *_nameLabel;
    UILabel *_timeLabel;
    UILabel *_infoLabel;
    UIImageView *_rightImage;
    OPRMessageContentItem *_contentItem;
}

+ (struct CGSize)_preferedTextSizeForAttributeText:(id)arg1 constrainedSize:(struct CGSize)arg2 maxLine:(unsigned long long)arg3;
+ (double)preferredTextHeight:(id)arg1 font:(id)arg2 widthLimit:(double)arg3 maxLine:(unsigned long long)arg4;
+ (_Bool)canMatchItem:(id)arg1;
+ (id)cellIdentifier;
+ (double)cellHightWithMaxWidth:(double)arg1 withItem:(id)arg2;
@property(retain, nonatomic) OPRMessageContentItem *contentItem; // @synthesize contentItem=_contentItem;
@property(retain, nonatomic) UIImageView *rightImage; // @synthesize rightImage=_rightImage;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) OPCUserAvatarView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (void)onAvatarClick:(id)arg1;
- (void)updateLayout;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

