//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRSingingCardPlayerListCellItem.h"

@interface OPROnlineUserListCellItem : OPRSingingCardPlayerListCellItem
{
    double _invitedTime;
    double _inviteDuration;
    unsigned long long _userStatus;
}

@property(nonatomic) unsigned long long userStatus; // @synthesize userStatus=_userStatus;
@property(nonatomic) double inviteDuration; // @synthesize inviteDuration=_inviteDuration;
@property(nonatomic) double invitedTime; // @synthesize invitedTime=_invitedTime;

@end

