//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPRUpassRmbBizObserver-Protocol.h"
#import "OPRWebSocketObserver-Protocol.h"

@class NSMutableDictionary, NSString, OPRWebSocketService, OPUpassRmbBiz;
@protocol OPROnlineUserSignalingDelegate;

@interface OPROnlineUserSignalingMananger : NSObject <OPRUpassRmbBizObserver, OPRWebSocketObserver>
{
    id <OPROnlineUserSignalingDelegate> _delegate;
    OPUpassRmbBiz *_upassBiz;
    OPRWebSocketService *_webSocketService;
    NSMutableDictionary *_recivedMsg;
}

@property(retain, nonatomic) NSMutableDictionary *recivedMsg; // @synthesize recivedMsg=_recivedMsg;
@property(retain, nonatomic) OPRWebSocketService *webSocketService; // @synthesize webSocketService=_webSocketService;
@property(retain, nonatomic) OPUpassRmbBiz *upassBiz; // @synthesize upassBiz=_upassBiz;
@property(nonatomic) __weak id <OPROnlineUserSignalingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)webSocketDidConnect;
- (void)webSocketDidDisconnect;
- (void)webSocketDidUpdateSocketStatus;
- (void)webSocketDidReciveMessage:(id)arg1;
- (void)initWithSocketIO;
- (void)didReceivedUppasMessage:(id)arg1;
- (void)initWithUpassBiz;
- (void)didReceivedMessage:(id)arg1;
- (id)initWithDeleagate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

