//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface OPROnlineUserGuideToSingView : UIView
{
    CDUnknownBlockType _startToSingHandler;
    CDUnknownBlockType _closeHandler;
    UIImageView *_yazi;
    UILabel *_tips;
    UIButton *_start;
    UIButton *_close;
}

@property(retain, nonatomic) UIButton *close; // @synthesize close=_close;
@property(retain, nonatomic) UIButton *start; // @synthesize start=_start;
@property(retain, nonatomic) UILabel *tips; // @synthesize tips=_tips;
@property(retain, nonatomic) UIImageView *yazi; // @synthesize yazi=_yazi;
@property(copy, nonatomic) CDUnknownBlockType closeHandler; // @synthesize closeHandler=_closeHandler;
@property(copy, nonatomic) CDUnknownBlockType startToSingHandler; // @synthesize startToSingHandler=_startToSingHandler;
- (void).cxx_destruct;
- (void)onCloseClick;
- (void)onStartClick;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

