//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class NSString, NSTimer, OPRPlayEnsembleScoreViewInfo, UIButton, UIImageView, UILabel;

@interface OPRPlayEnsembleScoreView : UIView <CAAnimationDelegate>
{
    UIView *_contentView;
    UIView *_bgView;
    UIView *_animationContentView;
    UIView *_playerContentView;
    UIView *_playerIconAnimatedBorderView;
    UIImageView *_playerIconView;
    UIView *_leadingSingerContentView;
    UIView *_leadingSingerIconAnimatedBorderView;
    UIImageView *_leadingSingerIconView;
    UIButton *_scoreTitleView;
    UILabel *_scoreLabel;
    UILabel *_scoreDescLabel;
    NSTimer *_scoreAnimationTimer;
    OPRPlayEnsembleScoreViewInfo *_viewInfo;
    CDUnknownBlockType _viewDidDisappearBlock;
}

+ (id)scoreDescWithScore:(float)arg1;
+ (void)showAtView:(id)arg1 withInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType viewDidDisappearBlock; // @synthesize viewDidDisappearBlock=_viewDidDisappearBlock;
@property(retain, nonatomic) OPRPlayEnsembleScoreViewInfo *viewInfo; // @synthesize viewInfo=_viewInfo;
@property(nonatomic) __weak NSTimer *scoreAnimationTimer; // @synthesize scoreAnimationTimer=_scoreAnimationTimer;
@property(nonatomic) __weak UILabel *scoreDescLabel; // @synthesize scoreDescLabel=_scoreDescLabel;
@property(nonatomic) __weak UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(nonatomic) __weak UIButton *scoreTitleView; // @synthesize scoreTitleView=_scoreTitleView;
@property(nonatomic) __weak UIImageView *leadingSingerIconView; // @synthesize leadingSingerIconView=_leadingSingerIconView;
@property(nonatomic) __weak UIView *leadingSingerIconAnimatedBorderView; // @synthesize leadingSingerIconAnimatedBorderView=_leadingSingerIconAnimatedBorderView;
@property(nonatomic) __weak UIView *leadingSingerContentView; // @synthesize leadingSingerContentView=_leadingSingerContentView;
@property(nonatomic) __weak UIImageView *playerIconView; // @synthesize playerIconView=_playerIconView;
@property(nonatomic) __weak UIView *playerIconAnimatedBorderView; // @synthesize playerIconAnimatedBorderView=_playerIconAnimatedBorderView;
@property(nonatomic) __weak UIView *playerContentView; // @synthesize playerContentView=_playerContentView;
@property(nonatomic) __weak UIView *animationContentView; // @synthesize animationContentView=_animationContentView;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)startHideAniamtion;
- (void)startShowAnimation;
- (void)layoutSelfView;
- (void)layoutSubviews;
- (void)setupSelfView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withInfo:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

