//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseViewController.h"

#import "OPRSingingScreenRecorderDelegate-Protocol.h"
#import "OPSNavigationTransitioning-Protocol.h"
#import "UIViewControllerOPContainerProtocol-Protocol.h"

@class AEAudioFilePlayerModule, NSMutableArray, NSMutableDictionary, NSNumber, NSString, NSTimer, OPProgressHUD, OPRAudioSpectrumPlayChordsRecordData, OPREnsembleAddService, OPRPlaySoundContentView, OPRPlaySoundContext, OPRPlaySoundDataInfo, OPRSingingAudioController, OPRSingingCardResultControlItemView, OPRSingingGuideView, OPRSingingScreenRecorder, OPRSingingStateButton, OPRSoundResInfo, OPRSoundSpectrumView, UIButton, UIImageView, UISwitch, UIView;

@interface OPRPlaySoundViewController : OPRBaseViewController <OPSNavigationTransitioning, OPRSingingScreenRecorderDelegate, UIViewControllerOPContainerProtocol>
{
    _Bool _disableShowOPNotificationOnViewDismiss;
    _Bool _enableScreenRecord;
    _Bool _isRecording;
    _Bool _playAfterSeek;
    _Bool _hasShowFirstFinishedTips;
    _Bool _isShowingLongPressAlert;
    _Bool _hasReportEnsemble;
    CDUnknownBlockType _viewControllerDidDismiss;
    CDUnknownBlockType _finishRecording;
    CDUnknownBlockType _ensembleDidBeginPlay;
    NSString *_entry;
    OPRPlaySoundDataInfo *_audioInfo;
    OPRPlaySoundContext *_playContext;
    NSString *_recordFilePath;
    double _baseAudioBeginPlayTs;
    UIView *_audioSpectrumContentView;
    UIButton *_settingBtn;
    UIButton *_settingContentView;
    UISwitch *_beatsTipsOnShowSwitch;
    UIView *_beatsTipsStyleSelectContentView;
    UIView *_singControlContentView;
    OPRSingingStateButton *_singBtn;
    OPRSingingCardResultControlItemView *_rePlayItemView;
    OPRSingingCardResultControlItemView *_nextStepItemView;
    UIView *_screenRecordContentView;
    UIButton *_screenRecordTipsView;
    OPRSingingScreenRecorder *_screenRecorder;
    OPRSingingAudioController *_audioController;
    OPRSoundSpectrumView *_audioSpectrumView;
    OPRPlaySoundContentView *_audioKeyboardView;
    NSMutableArray *_recordList;
    double _startRecordTime;
    AEAudioFilePlayerModule *_baseAudioFilePlayerModule;
    double _soundVolume;
    double _otherSoundVolume;
    OPRAudioSpectrumPlayChordsRecordData *_audioSpectrumPlayChordsRecordData;
    OPProgressHUD *_progressHUD;
    NSTimer *_audioTimer;
    double _lastCallback;
    AEAudioFilePlayerModule *_lastModule;
    OPRSoundResInfo *_lastRecordInfo;
    NSMutableDictionary *_volumeDict;
    NSMutableDictionary *_typeDict;
    UIButton *_typeNumberBtn;
    UIImageView *_typeNumberImage;
    OPRSingingGuideView *_pageGuideView;
    OPREnsembleAddService *_ensembleAddService;
    NSNumber *_viewBeginShowTs;
}

+ (double)headerViewHeight;
+ (_Bool)shouldHiddenStatusBar;
@property(retain, nonatomic) NSNumber *viewBeginShowTs; // @synthesize viewBeginShowTs=_viewBeginShowTs;
@property(nonatomic) _Bool hasReportEnsemble; // @synthesize hasReportEnsemble=_hasReportEnsemble;
@property(retain, nonatomic) OPREnsembleAddService *ensembleAddService; // @synthesize ensembleAddService=_ensembleAddService;
@property(nonatomic) __weak OPRSingingGuideView *pageGuideView; // @synthesize pageGuideView=_pageGuideView;
@property(nonatomic) _Bool isShowingLongPressAlert; // @synthesize isShowingLongPressAlert=_isShowingLongPressAlert;
@property(retain, nonatomic) UIImageView *typeNumberImage; // @synthesize typeNumberImage=_typeNumberImage;
@property(retain, nonatomic) UIButton *typeNumberBtn; // @synthesize typeNumberBtn=_typeNumberBtn;
@property(retain, nonatomic) NSMutableDictionary *typeDict; // @synthesize typeDict=_typeDict;
@property(nonatomic) _Bool hasShowFirstFinishedTips; // @synthesize hasShowFirstFinishedTips=_hasShowFirstFinishedTips;
@property(retain, nonatomic) NSMutableDictionary *volumeDict; // @synthesize volumeDict=_volumeDict;
@property(nonatomic) __weak OPRSoundResInfo *lastRecordInfo; // @synthesize lastRecordInfo=_lastRecordInfo;
@property(nonatomic) __weak AEAudioFilePlayerModule *lastModule; // @synthesize lastModule=_lastModule;
@property(nonatomic) double lastCallback; // @synthesize lastCallback=_lastCallback;
@property(nonatomic) _Bool playAfterSeek; // @synthesize playAfterSeek=_playAfterSeek;
@property(retain, nonatomic) NSTimer *audioTimer; // @synthesize audioTimer=_audioTimer;
@property(retain, nonatomic) OPProgressHUD *progressHUD; // @synthesize progressHUD=_progressHUD;
@property(retain, nonatomic) OPRAudioSpectrumPlayChordsRecordData *audioSpectrumPlayChordsRecordData; // @synthesize audioSpectrumPlayChordsRecordData=_audioSpectrumPlayChordsRecordData;
@property(nonatomic) double otherSoundVolume; // @synthesize otherSoundVolume=_otherSoundVolume;
@property(nonatomic) double soundVolume; // @synthesize soundVolume=_soundVolume;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(nonatomic) __weak AEAudioFilePlayerModule *baseAudioFilePlayerModule; // @synthesize baseAudioFilePlayerModule=_baseAudioFilePlayerModule;
@property(nonatomic) double startRecordTime; // @synthesize startRecordTime=_startRecordTime;
@property(retain, nonatomic) NSMutableArray *recordList; // @synthesize recordList=_recordList;
@property(retain, nonatomic) OPRPlaySoundContentView *audioKeyboardView; // @synthesize audioKeyboardView=_audioKeyboardView;
@property(retain, nonatomic) OPRSoundSpectrumView *audioSpectrumView; // @synthesize audioSpectrumView=_audioSpectrumView;
@property(retain, nonatomic) OPRSingingAudioController *audioController; // @synthesize audioController=_audioController;
@property(nonatomic) __weak OPRSingingScreenRecorder *screenRecorder; // @synthesize screenRecorder=_screenRecorder;
@property(retain, nonatomic) UIButton *screenRecordTipsView; // @synthesize screenRecordTipsView=_screenRecordTipsView;
@property(retain, nonatomic) UIView *screenRecordContentView; // @synthesize screenRecordContentView=_screenRecordContentView;
@property(nonatomic) _Bool enableScreenRecord; // @synthesize enableScreenRecord=_enableScreenRecord;
@property(nonatomic) __weak OPRSingingCardResultControlItemView *nextStepItemView; // @synthesize nextStepItemView=_nextStepItemView;
@property(nonatomic) __weak OPRSingingCardResultControlItemView *rePlayItemView; // @synthesize rePlayItemView=_rePlayItemView;
@property(nonatomic) __weak OPRSingingStateButton *singBtn; // @synthesize singBtn=_singBtn;
@property(nonatomic) __weak UIView *singControlContentView; // @synthesize singControlContentView=_singControlContentView;
@property(nonatomic) __weak UIView *beatsTipsStyleSelectContentView; // @synthesize beatsTipsStyleSelectContentView=_beatsTipsStyleSelectContentView;
@property(nonatomic) __weak UISwitch *beatsTipsOnShowSwitch; // @synthesize beatsTipsOnShowSwitch=_beatsTipsOnShowSwitch;
@property(nonatomic) __weak UIButton *settingContentView; // @synthesize settingContentView=_settingContentView;
@property(nonatomic) __weak UIButton *settingBtn; // @synthesize settingBtn=_settingBtn;
@property(nonatomic) __weak UIView *audioSpectrumContentView; // @synthesize audioSpectrumContentView=_audioSpectrumContentView;
@property(nonatomic) double baseAudioBeginPlayTs; // @synthesize baseAudioBeginPlayTs=_baseAudioBeginPlayTs;
@property(retain, nonatomic) NSString *recordFilePath; // @synthesize recordFilePath=_recordFilePath;
@property(retain, nonatomic) OPRPlaySoundContext *playContext; // @synthesize playContext=_playContext;
@property(retain, nonatomic) OPRPlaySoundDataInfo *audioInfo; // @synthesize audioInfo=_audioInfo;
@property(retain, nonatomic) NSString *entry; // @synthesize entry=_entry;
@property(copy, nonatomic) CDUnknownBlockType ensembleDidBeginPlay; // @synthesize ensembleDidBeginPlay=_ensembleDidBeginPlay;
@property(copy, nonatomic) CDUnknownBlockType finishRecording; // @synthesize finishRecording=_finishRecording;
@property(copy, nonatomic) CDUnknownBlockType viewControllerDidDismiss; // @synthesize viewControllerDidDismiss=_viewControllerDidDismiss;
@property(nonatomic) _Bool disableShowOPNotificationOnViewDismiss; // @synthesize disableShowOPNotificationOnViewDismiss=_disableShowOPNotificationOnViewDismiss;
- (void).cxx_destruct;
- (void)statPlayTime;
- (void)screenRecorderDidFinishRecording:(id)arg1 withPresentRecordingPreviewWithController:(id)arg2;
- (void)screenRecorderBeginRecording:(id)arg1;
- (void)screenRecorder:(id)arg1 recordingDidFailWithSystemError:(id)arg2 withBizError:(unsigned long long)arg3;
- (void)audioInterruptionHappen:(id)arg1;
- (void)applicationBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (_Bool)controlStatusBarAppearance;
- (long long)interactiveTransitionSupportType;
- (void)showPageGuideIfNeed;
- (void)updateBeatMarkInfosWithAudioFilePath:(id)arg1;
- (void)downloadLeadingSingerAudioFile:(CDUnknownBlockType)arg1;
- (unsigned long long)countDownSecond;
- (void)enableOPNotification:(_Bool)arg1;
- (void)showCommonSetting:(_Bool)arg1;
- (void)endRecord:(CDUnknownBlockType)arg1;
- (void)resetRecord;
- (void)playRecordAtTime:(double)arg1;
- (void)updatePlayState;
- (void)startProcessTime;
- (void)beginRecordDo;
- (void)initAudioSpectrumPlayChordsRecordDataIfNeed;
- (void)reMarkRecord;
- (void)hideView:(id)arg1;
- (void)setupAudioSpectrumContentView:(double)arg1;
- (double)gapHeight;
- (double)screenHeight;
- (void)beginRecord;
- (void)pause:(_Bool)arg1;
- (void)onSingBtnClick;
- (void)onRecordVideoClick;
- (void)showVideoTeachPage;
- (void)resetLastStep;
- (void)onSoundPlayMoreViewClick;
- (void)onBackButtonClick;
- (void)updateMyEffectSoundList;
- (void)enableNextStepItemView:(_Bool)arg1;
- (void)updateScreenRecorderTips:(_Bool)arg1;
- (void)setupSingControlContentView;
- (void)showImpactFeedback;
- (void)setupKeyboardContentView;
- (void)setupSelfView;
- (void)setupHeaderView;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)initNotifications;
- (void)updateTypeNumberBtn;
- (void)setUpdateTypeDict:(id)arg1 count:(long long)arg2;
- (void)setUpdateTypeDict:(id)arg1 count:(long long)arg2 updateUI:(_Bool)arg3;
- (void)initSoundList;
- (id)initWithInfo:(id)arg1 withEntry:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

