//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "OPRQuerySoundResManagerObserver-Protocol.h"

@class NSArray, NSDictionary, NSString, OPRPlaySoundKeyboard, OPRSoundKindInfo, OPRSoundResStateView, OPTouchBounceButton, UIScrollView;

@interface OPRPlaySoundContentView : UIView <OPRQuerySoundResManagerObserver>
{
    CDUnknownBlockType _keyboardDidClick;
    CDUnknownBlockType _keyboardDidLongPress;
    CDUnknownBlockType _keyboardTypeChanged;
    CDUnknownBlockType _keyboardKindChanged;
    CDUnknownBlockType _menuDidClick;
    NSDictionary *_chordDict;
    NSArray *_soundReslist;
    OPTouchBounceButton *_selectedKindBtn;
    OPRSoundKindInfo *_selectedKindInfo;
    UIView *_tagView;
    NSArray *_tagBtn;
    UIScrollView *_kindView;
    OPRPlaySoundKeyboard *_keyboard;
    UIView *_tagMark;
    OPRSoundResStateView *_stateView;
}

@property(retain, nonatomic) OPRSoundResStateView *stateView; // @synthesize stateView=_stateView;
@property(retain, nonatomic) UIView *tagMark; // @synthesize tagMark=_tagMark;
@property(retain, nonatomic) OPRPlaySoundKeyboard *keyboard; // @synthesize keyboard=_keyboard;
@property(retain, nonatomic) UIScrollView *kindView; // @synthesize kindView=_kindView;
@property(retain, nonatomic) NSArray *tagBtn; // @synthesize tagBtn=_tagBtn;
@property(retain, nonatomic) UIView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) OPRSoundKindInfo *selectedKindInfo; // @synthesize selectedKindInfo=_selectedKindInfo;
@property(retain, nonatomic) OPTouchBounceButton *selectedKindBtn; // @synthesize selectedKindBtn=_selectedKindBtn;
@property(retain, nonatomic) NSArray *soundReslist; // @synthesize soundReslist=_soundReslist;
@property(copy, nonatomic) NSDictionary *chordDict; // @synthesize chordDict=_chordDict;
@property(copy, nonatomic) CDUnknownBlockType menuDidClick; // @synthesize menuDidClick=_menuDidClick;
@property(copy, nonatomic) CDUnknownBlockType keyboardKindChanged; // @synthesize keyboardKindChanged=_keyboardKindChanged;
@property(copy, nonatomic) CDUnknownBlockType keyboardTypeChanged; // @synthesize keyboardTypeChanged=_keyboardTypeChanged;
@property(copy, nonatomic) CDUnknownBlockType keyboardDidLongPress; // @synthesize keyboardDidLongPress=_keyboardDidLongPress;
@property(copy, nonatomic) CDUnknownBlockType keyboardDidClick; // @synthesize keyboardDidClick=_keyboardDidClick;
- (void).cxx_destruct;
- (void)updateViewWithGapHeight:(double)arg1;
- (double)contentHeight;
- (void)kindInfoFinishDownloading:(id)arg1 result:(_Bool)arg2;
- (void)updateKeyboarHintWithNode:(id)arg1 nextNode:(id)arg2 offset:(double)arg3;
- (void)updateMyEffectSoundList;
- (void)updateShowMelodyHint:(_Bool)arg1;
- (void)updateKeyBordTitleName;
- (void)selectKeyboardType:(unsigned long long)arg1;
- (void)updateKeyboardStatusView:(id)arg1 autoDownload:(_Bool)arg2;
- (void)kindBtnClicked:(id)arg1;
- (void)buildKindListViewWithList:(id)arg1;
- (unsigned long long)currentSelectedResType;
- (void)buildView;
- (void)buildData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

