//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPRPlayEnsembleEntry : NSObject
{
}

+ (void)showEnsembleEntry:(CDUnknownBlockType)arg1 withData:(id)arg2 entry:(id)arg3;
+ (void)showEnsembleEntry:(CDUnknownBlockType)arg1 withCancelBlock:(CDUnknownBlockType)arg2 withData:(id)arg3 entry:(id)arg4;
+ (void)showEnsembleEntry:(CDUnknownBlockType)arg1 cancelBlock:(CDUnknownBlockType)arg2 canPlay:(_Bool)arg3;

@end

