//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class LOTAnimationView, NSArray, NSDictionary, NSMutableArray, NSString, NSThread, NSTimer, OPRPlayEnsembleMusicScoreConfigInfo, OPRPlayEnsembleMusicScorePlayTipsItem, OPRPlayEnsemblePlayChordsRecordData, OPRPlayEnsembleScoreComputer, UIScrollView;

@interface OPRPlayEnsembleMusicScoreView : UIView <CAAnimationDelegate>
{
    float _effectiveClickDeviation;
    OPRPlayEnsemblePlayChordsRecordData *_musicScoreData;
    OPRPlayEnsemblePlayChordsRecordData *_playChordsRecordData;
    OPRPlayEnsemblePlayChordsRecordData *_beatTipsData;
    double _readySeconds;
    CDUnknownBlockType _didFigureOutScore;
    CDUnknownBlockType _currentPlayTimeInSecond;
    OPRPlayEnsembleMusicScoreConfigInfo *_configInfo;
    NSDictionary *_configItemDict;
    NSArray *_musicScoreItemViewInfos;
    NSArray *_beatItemViewInfos;
    NSMutableArray *_beatItemViewInfosForProgressAnimation;
    unsigned long long _shouldHitPlayedChordItemIndexForPlayBack;
    OPRPlayEnsembleMusicScorePlayTipsItem *_currentOnShowPlayTipsItem;
    NSArray *_comboMusicScoreChordItems;
    UIView *_contentView;
    UIView *_contentScrollViewBgView;
    UIScrollView *_contentScrollView;
    UIView *_musicScoreContentView;
    UIView *_playChordsRecordContentView;
    UIView *_beatTipsContentView;
    UIView *_cursorView;
    UIView *_beatsHitCursorContentView;
    UIView *_envAnimationContentView;
    UIView *_excellentAnimationContentView;
    UIView *_playedTipsAnimationContentView;
    UIView *_countDownView;
    LOTAnimationView *_countDownAnimationView;
    NSThread *_threadForProgressAnimationTimer;
    NSTimer *_progressAnimationTimer;
    OPRPlayEnsemblePlayChordsRecordData *_hiddenBeatTipsData;
    OPRPlayEnsembleScoreComputer *_scoreComputer;
}

+ (id)keyClickEnvImageNameWithIndex:(unsigned long long)arg1;
+ (id)beatColorHexValueWithIndex:(unsigned long long)arg1;
+ (id)perfectImageNameWithIndex:(unsigned long long)arg1;
@property(nonatomic) float effectiveClickDeviation; // @synthesize effectiveClickDeviation=_effectiveClickDeviation;
@property(retain, nonatomic) OPRPlayEnsembleScoreComputer *scoreComputer; // @synthesize scoreComputer=_scoreComputer;
@property(retain, nonatomic) OPRPlayEnsemblePlayChordsRecordData *hiddenBeatTipsData; // @synthesize hiddenBeatTipsData=_hiddenBeatTipsData;
@property(retain, nonatomic) NSTimer *progressAnimationTimer; // @synthesize progressAnimationTimer=_progressAnimationTimer;
@property(retain, nonatomic) NSThread *threadForProgressAnimationTimer; // @synthesize threadForProgressAnimationTimer=_threadForProgressAnimationTimer;
@property(nonatomic) __weak LOTAnimationView *countDownAnimationView; // @synthesize countDownAnimationView=_countDownAnimationView;
@property(nonatomic) __weak UIView *countDownView; // @synthesize countDownView=_countDownView;
@property(nonatomic) __weak UIView *playedTipsAnimationContentView; // @synthesize playedTipsAnimationContentView=_playedTipsAnimationContentView;
@property(nonatomic) __weak UIView *excellentAnimationContentView; // @synthesize excellentAnimationContentView=_excellentAnimationContentView;
@property(nonatomic) __weak UIView *envAnimationContentView; // @synthesize envAnimationContentView=_envAnimationContentView;
@property(nonatomic) __weak UIView *beatsHitCursorContentView; // @synthesize beatsHitCursorContentView=_beatsHitCursorContentView;
@property(nonatomic) __weak UIView *cursorView; // @synthesize cursorView=_cursorView;
@property(nonatomic) __weak UIView *beatTipsContentView; // @synthesize beatTipsContentView=_beatTipsContentView;
@property(nonatomic) __weak UIView *playChordsRecordContentView; // @synthesize playChordsRecordContentView=_playChordsRecordContentView;
@property(nonatomic) __weak UIView *musicScoreContentView; // @synthesize musicScoreContentView=_musicScoreContentView;
@property(nonatomic) __weak UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) __weak UIView *contentScrollViewBgView; // @synthesize contentScrollViewBgView=_contentScrollViewBgView;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSArray *comboMusicScoreChordItems; // @synthesize comboMusicScoreChordItems=_comboMusicScoreChordItems;
@property(retain, nonatomic) OPRPlayEnsembleMusicScorePlayTipsItem *currentOnShowPlayTipsItem; // @synthesize currentOnShowPlayTipsItem=_currentOnShowPlayTipsItem;
@property(nonatomic) unsigned long long shouldHitPlayedChordItemIndexForPlayBack; // @synthesize shouldHitPlayedChordItemIndexForPlayBack=_shouldHitPlayedChordItemIndexForPlayBack;
@property(retain, nonatomic) NSMutableArray *beatItemViewInfosForProgressAnimation; // @synthesize beatItemViewInfosForProgressAnimation=_beatItemViewInfosForProgressAnimation;
@property(retain, nonatomic) NSArray *beatItemViewInfos; // @synthesize beatItemViewInfos=_beatItemViewInfos;
@property(retain, nonatomic) NSArray *musicScoreItemViewInfos; // @synthesize musicScoreItemViewInfos=_musicScoreItemViewInfos;
@property(retain, nonatomic) NSDictionary *configItemDict; // @synthesize configItemDict=_configItemDict;
@property(retain, nonatomic) OPRPlayEnsembleMusicScoreConfigInfo *configInfo; // @synthesize configInfo=_configInfo;
@property(copy, nonatomic) CDUnknownBlockType currentPlayTimeInSecond; // @synthesize currentPlayTimeInSecond=_currentPlayTimeInSecond;
@property(copy, nonatomic) CDUnknownBlockType didFigureOutScore; // @synthesize didFigureOutScore=_didFigureOutScore;
@property(nonatomic) double readySeconds; // @synthesize readySeconds=_readySeconds;
@property(retain, nonatomic) OPRPlayEnsemblePlayChordsRecordData *beatTipsData; // @synthesize beatTipsData=_beatTipsData;
@property(retain, nonatomic) OPRPlayEnsemblePlayChordsRecordData *playChordsRecordData; // @synthesize playChordsRecordData=_playChordsRecordData;
@property(retain, nonatomic) OPRPlayEnsemblePlayChordsRecordData *musicScoreData; // @synthesize musicScoreData=_musicScoreData;
- (void).cxx_destruct;
- (void)cancelCountDown;
- (void)beginCountDown:(unsigned long long)arg1 withFinishBlock:(CDUnknownBlockType)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)showPlayedTips:(id)arg1 textColor:(id)arg2 isScore:(_Bool)arg3;
- (void)showPlayedTips:(id)arg1 isScore:(_Bool)arg2;
- (void)showBeatHitCursorAnimationIfNeedWithSecond:(float)arg1;
- (void)showKeyClickAnimationWithConfigItem:(id)arg1;
- (void)showCursorLineAniamtionWithConfigItem:(id)arg1;
- (void)showClickGoodAnimationWithConfigItem:(id)arg1;
- (void)showClickExcellentAnimationWithConfigItem:(id)arg1;
- (void)showAnimationIfNeedWithSeconds:(double)arg1 withItemId:(id)arg2 withKeyArea:(unsigned long long)arg3 shouldMarkForScore:(_Bool)arg4;
- (void)initComboMusicScoreChordItems;
- (void)resetScoreComputerIfNeed;
- (void)initScoreComputer;
- (void)analysisStateWithNote:(id)arg1 withTagId:(id)arg2 withSeconds:(float)arg3 withLastHitItem:(id)arg4 complete:(CDUnknownBlockType)arg5;
- (_Bool)showPlayedRecordAnimationIfNeedWithSecond:(float)arg1;
- (void)progressAnimatingDo;
- (void)updateHiddenBeatTipsDataWithOriginalBeatItemViewInfos:(id)arg1;
- (void)drawBeatTips;
- (void)drawPlayChordsRecord;
- (void)drawMusicScore;
- (void)updateProgressWithSecond:(double)arg1;
- (void)stopProgressAnimation;
- (void)stopTimer;
- (void)createTimer;
- (void)startProgressAnimation;
- (void)startShowAnimation;
- (double)musicScoreItemViewHeight:(id)arg1;
- (double)musicScoreItemViewHeadHeight:(id)arg1;
- (double)musicScoreItemViewTailHeight;
- (double)distancePerSecond;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutContentView;
- (void)layoutSubviews;
- (void)setupSelfView;
- (void)removeFromSuperview;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withMusicScoreConfigInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

