//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString, OPRSongExtendDataAudioAttributes;

@interface OPRPostUgcClipData : NSObject
{
    NSString *_segmentId;
    NSString *_ossId;
    NSNumber *_audioDuration;
    NSNumber *_notPassAcrAudit;
    NSString *_audioFilterType;
    NSString *_originOssId;
    NSString *_chord;
    NSString *_beat;
    NSString *_effect;
    NSString *_audioDesc;
    NSString *_audioDescWithTopic;
    NSArray *_topicIds;
    NSArray *_atUserIds;
    NSString *_detectBPMData;
    NSNumber *_useRecommendBPMTips;
    NSString *_beatSpectrumID;
    OPRSongExtendDataAudioAttributes *_audioAttributes;
    NSArray *_singers;
    NSString *_songName;
    NSString *_lyric;
    NSNumber *_clipType;
    NSString *_originalClipId;
    NSString *_parentAudioId;
    NSNumber *_ugcType;
    NSNumber *_syncRate;
}

@property(retain, nonatomic) NSNumber *syncRate; // @synthesize syncRate=_syncRate;
@property(retain, nonatomic) NSNumber *ugcType; // @synthesize ugcType=_ugcType;
@property(copy, nonatomic) NSString *parentAudioId; // @synthesize parentAudioId=_parentAudioId;
@property(copy, nonatomic) NSString *originalClipId; // @synthesize originalClipId=_originalClipId;
@property(copy, nonatomic) NSNumber *clipType; // @synthesize clipType=_clipType;
@property(copy, nonatomic) NSString *lyric; // @synthesize lyric=_lyric;
@property(copy, nonatomic) NSString *songName; // @synthesize songName=_songName;
@property(copy, nonatomic) NSArray *singers; // @synthesize singers=_singers;
@property(retain, nonatomic) OPRSongExtendDataAudioAttributes *audioAttributes; // @synthesize audioAttributes=_audioAttributes;
@property(copy, nonatomic) NSString *beatSpectrumID; // @synthesize beatSpectrumID=_beatSpectrumID;
@property(copy, nonatomic) NSNumber *useRecommendBPMTips; // @synthesize useRecommendBPMTips=_useRecommendBPMTips;
@property(copy, nonatomic) NSString *detectBPMData; // @synthesize detectBPMData=_detectBPMData;
@property(copy, nonatomic) NSArray *atUserIds; // @synthesize atUserIds=_atUserIds;
@property(copy, nonatomic) NSArray *topicIds; // @synthesize topicIds=_topicIds;
@property(copy, nonatomic) NSString *audioDescWithTopic; // @synthesize audioDescWithTopic=_audioDescWithTopic;
@property(copy, nonatomic) NSString *audioDesc; // @synthesize audioDesc=_audioDesc;
@property(copy, nonatomic) NSString *effect; // @synthesize effect=_effect;
@property(copy, nonatomic) NSString *beat; // @synthesize beat=_beat;
@property(copy, nonatomic) NSString *chord; // @synthesize chord=_chord;
@property(copy, nonatomic) NSString *originOssId; // @synthesize originOssId=_originOssId;
@property(copy, nonatomic) NSString *audioFilterType; // @synthesize audioFilterType=_audioFilterType;
@property(retain, nonatomic) NSNumber *notPassAcrAudit; // @synthesize notPassAcrAudit=_notPassAcrAudit;
@property(retain, nonatomic) NSNumber *audioDuration; // @synthesize audioDuration=_audioDuration;
@property(copy, nonatomic) NSString *ossId; // @synthesize ossId=_ossId;
@property(copy, nonatomic) NSString *segmentId; // @synthesize segmentId=_segmentId;
- (void).cxx_destruct;

@end

