//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPRPlaySoundAlertFactory : NSObject
{
}

+ (void)showCustomGuideAlertWithConfirmclick:(CDUnknownBlockType)arg1;
+ (void)showEffectDeleteActionSheetWithReNameclick:(CDUnknownBlockType)arg1 deleteClick:(CDUnknownBlockType)arg2 cancelClick:(CDUnknownBlockType)arg3;
+ (void)showSoundPlayMoreViewWithResetClick:(CDUnknownBlockType)arg1 resetEnabled:(_Bool)arg2 videoTeachClick:(CDUnknownBlockType)arg3 recordVideoClick:(CDUnknownBlockType)arg4 autoAlignClick:(CDUnknownBlockType)arg5 volumeClick:(CDUnknownBlockType)arg6 melodyTipClick:(CDUnknownBlockType)arg7 keyBoardTypeClick:(CDUnknownBlockType)arg8 cancelClick:(CDUnknownBlockType)arg9;
+ (void)showSaveNewEffectAlertWithTitle:(id)arg1 Confirmclick:(CDUnknownBlockType)arg2 cancelClick:(CDUnknownBlockType)arg3;
+ (void)showAudioSampleEntryWithSoundRecorded:(CDUnknownBlockType)arg1 customSampleClick:(CDUnknownBlockType)arg2 cancelClick:(CDUnknownBlockType)arg3;

@end

