//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "CAAnimationDelegate-Protocol.h"

@class CAGradientLayer, NSString, OPRPlayBeatSynthKeyboardItem, OPTouchBounceView, UIImageView, UILabel, UIView;

@interface OPRPlayBeatSynthKeyboardCell : UICollectionViewCell <CAAnimationDelegate>
{
    _Bool _simulatingTouch;
    OPTouchBounceView *_bgView;
    UIImageView *_bgImageView;
    UIView *_keyLabelBgView;
    UILabel *_keyLabel;
    UIView *_gradientView;
    CAGradientLayer *_gradientLayer;
    OPRPlayBeatSynthKeyboardItem *_item;
    UIView *_scaleAnimationViewBgView;
    UIView *_touchView;
    CDUnknownBlockType _touchBeginBlock;
}

@property(copy, nonatomic) CDUnknownBlockType touchBeginBlock; // @synthesize touchBeginBlock=_touchBeginBlock;
@property(nonatomic) _Bool simulatingTouch; // @synthesize simulatingTouch=_simulatingTouch;
@property(nonatomic) __weak UIView *touchView; // @synthesize touchView=_touchView;
@property(nonatomic) __weak UIView *scaleAnimationViewBgView; // @synthesize scaleAnimationViewBgView=_scaleAnimationViewBgView;
@property(nonatomic) __weak OPRPlayBeatSynthKeyboardItem *item; // @synthesize item=_item;
@property(nonatomic) __weak CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(nonatomic) __weak UIView *gradientView; // @synthesize gradientView=_gradientView;
@property(nonatomic) __weak UILabel *keyLabel; // @synthesize keyLabel=_keyLabel;
@property(nonatomic) __weak UIView *keyLabelBgView; // @synthesize keyLabelBgView=_keyLabelBgView;
@property(nonatomic) __weak UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(nonatomic) __weak OPTouchBounceView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)showTouchAnimation:(id)arg1;
- (void)updateIconWithImageView:(id)arg1 withIconPath:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

