//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class OPRPlayerListFreeStyleHeadModel, UIImageView, UIView, YYLabel;

@interface OPRPlayerListFreeStyleHead : UICollectionReusableView
{
    YYLabel *_descLabel;
    UIView *_emptyBomView;
    UIImageView *_emptyTipsView;
    UIView *_emptyLeft;
    UIView *_emptyRight;
    OPRPlayerListFreeStyleHeadModel *_model;
}

@property(retain, nonatomic) OPRPlayerListFreeStyleHeadModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIView *emptyRight; // @synthesize emptyRight=_emptyRight;
@property(retain, nonatomic) UIView *emptyLeft; // @synthesize emptyLeft=_emptyLeft;
@property(retain, nonatomic) UIImageView *emptyTipsView; // @synthesize emptyTipsView=_emptyTipsView;
@property(retain, nonatomic) UIView *emptyBomView; // @synthesize emptyBomView=_emptyBomView;
@property(retain, nonatomic) YYLabel *descLabel; // @synthesize descLabel=_descLabel;
- (void).cxx_destruct;
- (void)updateDesc:(id)arg1;
- (void)layoutSubviews;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

