//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber;

@interface OPRPlayEnsemblePlayChordsRecordData : NSObject
{
    NSNumber *_playChordsBeginTS;
    NSArray *_chordItems;
}

@property(retain, nonatomic) NSArray *chordItems; // @synthesize chordItems=_chordItems;
@property(retain, nonatomic) NSNumber *playChordsBeginTS; // @synthesize playChordsBeginTS=_playChordsBeginTS;
- (void).cxx_destruct;

@end

