//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, OPRAudioBPMData, OPRAudioEditAudioTrackList;

@interface OPRPlayBeatDataInfo : NSObject
{
    _Bool _recommendBeatTipsOnShow;
    NSString *_audioFileName;
    NSNumber *_audioDurationInMSecond;
    OPRAudioEditAudioTrackList *_tracks;
    NSString *_albumId;
    NSString *_segmentId;
    NSString *_audioFileUploadId;
    OPRAudioBPMData *_audioBPMData;
    unsigned long long _maxAddAudioTrackNum;
}

@property(nonatomic) unsigned long long maxAddAudioTrackNum; // @synthesize maxAddAudioTrackNum=_maxAddAudioTrackNum;
@property(nonatomic) _Bool recommendBeatTipsOnShow; // @synthesize recommendBeatTipsOnShow=_recommendBeatTipsOnShow;
@property(copy, nonatomic) OPRAudioBPMData *audioBPMData; // @synthesize audioBPMData=_audioBPMData;
@property(copy, nonatomic) NSString *audioFileUploadId; // @synthesize audioFileUploadId=_audioFileUploadId;
@property(copy, nonatomic) NSString *segmentId; // @synthesize segmentId=_segmentId;
@property(copy, nonatomic) NSString *albumId; // @synthesize albumId=_albumId;
@property(retain, nonatomic) OPRAudioEditAudioTrackList *tracks; // @synthesize tracks=_tracks;
@property(retain, nonatomic) NSNumber *audioDurationInMSecond; // @synthesize audioDurationInMSecond=_audioDurationInMSecond;
@property(copy, nonatomic) NSString *audioFileName; // @synthesize audioFileName=_audioFileName;
- (void).cxx_destruct;

@end

