//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface OPRPostContentPostInfo : NSObject
{
    NSString *_text;
    NSString *_opAttributeText;
    NSArray *_selectedTopicIds;
    NSArray *_selectedAtIds;
}

@property(retain, nonatomic) NSArray *selectedAtIds; // @synthesize selectedAtIds=_selectedAtIds;
@property(retain, nonatomic) NSArray *selectedTopicIds; // @synthesize selectedTopicIds=_selectedTopicIds;
@property(copy, nonatomic) NSString *opAttributeText; // @synthesize opAttributeText=_opAttributeText;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;

@end

