//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPRPrivacyAlert : NSObject
{
}

+ (void)statPVPrivacyAlert;
+ (void)statClickPrivacyAlertWithSpm:(id)arg1;
+ (void)statClickPrivacy_agreement;
+ (void)statClickUser_agreement;
+ (void)statClickSencondPrivacyAlertIsConfirmed:(_Bool)arg1;
+ (void)statClickPrivacyAlertIsConfirmed:(_Bool)arg1;
+ (void)showPrivacyVC;
+ (void)showTermsVC;
+ (id)rejectTips;
+ (id)tips;
+ (id)textAttributes;
+ (id)heightLightColor;
+ (id)alertTitle;
+ (void)alertDidCanceled;
+ (void)alertDidConfirmed;
+ (void)presentPrivacyRejectAlert;
+ (void)presentPrivacyAlert;
+ (void)showAlert;
+ (void)saveConfirmed;
+ (_Bool)hasConfirmedAlready;
+ (_Bool)checkAndShowAlertIfNeed;
+ (_Bool)checkAndShowAlertWithHoldVC;

@end

