//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface OPRPlayEnsembleScoreComputer : NSObject
{
    _Bool _isForBeat;
    float _totalScore;
    float _duplicateRatio;
    float _oneClickCountScore;
    float _multiClickCountScore;
    float _oneVariousKeyRatio;
    float _twiceVariousKeyRatio;
    float _multiVariousKeyRatio;
    float _cheatRuleMarkDeviation;
    float _cheatRuleRatio;
    float _extraScoreStdDeviation;
    CDUnknownBlockType _didFigureOutScore;
    unsigned long long _totalBeatOnsetsCount;
    NSMutableArray *_markItems;
    NSArray *_scoreSections;
    NSMutableArray *_tempScoreSections;
    long long _cheatRuleCount;
}

@property(nonatomic) float extraScoreStdDeviation; // @synthesize extraScoreStdDeviation=_extraScoreStdDeviation;
@property(nonatomic) float cheatRuleRatio; // @synthesize cheatRuleRatio=_cheatRuleRatio;
@property(nonatomic) long long cheatRuleCount; // @synthesize cheatRuleCount=_cheatRuleCount;
@property(nonatomic) float cheatRuleMarkDeviation; // @synthesize cheatRuleMarkDeviation=_cheatRuleMarkDeviation;
@property(nonatomic) float multiVariousKeyRatio; // @synthesize multiVariousKeyRatio=_multiVariousKeyRatio;
@property(nonatomic) float twiceVariousKeyRatio; // @synthesize twiceVariousKeyRatio=_twiceVariousKeyRatio;
@property(nonatomic) float oneVariousKeyRatio; // @synthesize oneVariousKeyRatio=_oneVariousKeyRatio;
@property(nonatomic) float multiClickCountScore; // @synthesize multiClickCountScore=_multiClickCountScore;
@property(nonatomic) float oneClickCountScore; // @synthesize oneClickCountScore=_oneClickCountScore;
@property(nonatomic) float duplicateRatio; // @synthesize duplicateRatio=_duplicateRatio;
@property(nonatomic) float totalScore; // @synthesize totalScore=_totalScore;
@property(retain, nonatomic) NSMutableArray *tempScoreSections; // @synthesize tempScoreSections=_tempScoreSections;
@property(retain, nonatomic) NSArray *scoreSections; // @synthesize scoreSections=_scoreSections;
@property(retain, nonatomic) NSMutableArray *markItems; // @synthesize markItems=_markItems;
@property(nonatomic) _Bool isForBeat; // @synthesize isForBeat=_isForBeat;
@property(nonatomic) unsigned long long totalBeatOnsetsCount; // @synthesize totalBeatOnsetsCount=_totalBeatOnsetsCount;
@property(copy, nonatomic) CDUnknownBlockType didFigureOutScore; // @synthesize didFigureOutScore=_didFigureOutScore;
- (void).cxx_destruct;
- (void)computePlayedScoreWithSecond:(float)arg1;
- (id)allAddedMarkItem;
- (void)addMarkItem:(id)arg1;
- (void)reset;
- (void)removeAllMarkItems;
- (void)initRatio;
- (id)initWithScoreSections:(id)arg1;

@end

