//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseService.h"

@class NSString;

@interface OPRQueryCommentListService : OPRBaseService
{
    _Bool _isQuery;
    NSString *_itemId;
    NSString *_itemUserId;
}

@property(copy, nonatomic) NSString *itemUserId; // @synthesize itemUserId=_itemUserId;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(nonatomic) _Bool isQuery; // @synthesize isQuery=_isQuery;
- (void).cxx_destruct;
- (_Bool)dataNeedGZipCompress;
- (_Bool)dataNeedSGDecrypt;
- (id)parseCommentItemsWithDictArr:(id)arg1;
- (id)parseDataWithDict:(id)arg1;
- (id)serviceTaskWithData:(id)arg1 withURLParamData:(id)arg2;

@end

