//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface OPRQueryChordResFeedBackData : NSObject
{
    _Bool _shouldShowChordVideoGuide;
    _Bool _shouldShowMessyBPMToast;
    _Bool _shouldHighlightActiveChordKey;
    NSArray *_chordInstruments;
    NSArray *_beatInstruments;
    NSArray *_beatSpectrums;
}

@property(nonatomic) _Bool shouldHighlightActiveChordKey; // @synthesize shouldHighlightActiveChordKey=_shouldHighlightActiveChordKey;
@property(nonatomic) _Bool shouldShowMessyBPMToast; // @synthesize shouldShowMessyBPMToast=_shouldShowMessyBPMToast;
@property(nonatomic) _Bool shouldShowChordVideoGuide; // @synthesize shouldShowChordVideoGuide=_shouldShowChordVideoGuide;
@property(retain, nonatomic) NSArray *beatSpectrums; // @synthesize beatSpectrums=_beatSpectrums;
@property(retain, nonatomic) NSArray *beatInstruments; // @synthesize beatInstruments=_beatInstruments;
@property(retain, nonatomic) NSArray *chordInstruments; // @synthesize chordInstruments=_chordInstruments;
- (void).cxx_destruct;

@end

