//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPRQuerySegmentDetailQueryData : NSObject
{
    NSString *_ids;
    long long _source;
}

@property(nonatomic) long long source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *ids; // @synthesize ids=_ids;
- (void).cxx_destruct;
- (id)initWithDataIDs:(id)arg1;

@end

