//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPRUpassRmbBizObserver-Protocol.h"
#import "OPRWebSocketObserver-Protocol.h"

@class NSString, OPRWebSocketService, OPUpassRmbBiz;
@protocol OPRSingingRoomIntercatCommandDelegate;

@interface OPRRoomInteractSignalingManager : NSObject <OPRUpassRmbBizObserver, OPRWebSocketObserver>
{
    id <OPRSingingRoomIntercatCommandDelegate> _delegate;
    NSString *_currentRoomID;
    long long _currentSeqNo;
    unsigned long long _connetStateMask;
    OPUpassRmbBiz *_upassBiz;
    OPRWebSocketService *_webSocketService;
}

@property(retain, nonatomic) OPRWebSocketService *webSocketService; // @synthesize webSocketService=_webSocketService;
@property(retain, nonatomic) OPUpassRmbBiz *upassBiz; // @synthesize upassBiz=_upassBiz;
@property(nonatomic) unsigned long long connetStateMask; // @synthesize connetStateMask=_connetStateMask;
@property(nonatomic) long long currentSeqNo; // @synthesize currentSeqNo=_currentSeqNo;
@property(retain, nonatomic) NSString *currentRoomID; // @synthesize currentRoomID=_currentRoomID;
@property(nonatomic) __weak id <OPRSingingRoomIntercatCommandDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)webSocketDidReciveMessage:(id)arg1;
- (void)initWithSocketIO;
- (void)didReceivedUppasMessage:(id)arg1;
- (void)initWithUpassBiz;
- (void)leaveRoom;
- (void)joinRoom:(id)arg1;
- (void)didReceivedMessage:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

