//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIView;

@interface OPRRoomLikeEffectLottieItem : NSObject
{
    UIView *_parentView;
    UIView *_belowAtView;
    NSString *_uuid;
    double _animationDelayTime;
    struct CGRect _frame;
}

@property(nonatomic) double animationDelayTime; // @synthesize animationDelayTime=_animationDelayTime;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) __weak UIView *belowAtView; // @synthesize belowAtView=_belowAtView;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
- (void).cxx_destruct;

@end

