//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPCUserAvatarView.h"

@class OPRSingingRoomUser, UIImageView, UIView;

@interface OPRRoomUserAvatarView : OPCUserAvatarView
{
    UIView *_coverView;
    double _specialCoverLength;
    UIImageView *_specialView;
    UIView *_circleView;
}

@property(retain, nonatomic) UIView *circleView; // @synthesize circleView=_circleView;
@property(retain, nonatomic) UIImageView *specialView; // @synthesize specialView=_specialView;
@property(nonatomic) double specialCoverLength; // @synthesize specialCoverLength=_specialCoverLength;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
- (void).cxx_destruct;
- (void)setUserItem:(id)arg1;
@property(retain, nonatomic) OPRSingingRoomUser *roomUser;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

