//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, OPRRoomCommandBaseInfoData;

@interface OPRRoomCommandData : NSObject
{
    long long _ver;
    unsigned long long _signalType;
    unsigned long long _command;
    long long _sequenceNo;
    OPRRoomCommandBaseInfoData *_baseInfo;
    NSDictionary *_extraData;
}

+ (id)dataWithMessage:(id)arg1;
@property(retain, nonatomic) NSDictionary *extraData; // @synthesize extraData=_extraData;
@property(retain, nonatomic) OPRRoomCommandBaseInfoData *baseInfo; // @synthesize baseInfo=_baseInfo;
@property(nonatomic) long long sequenceNo; // @synthesize sequenceNo=_sequenceNo;
@property(nonatomic) unsigned long long command; // @synthesize command=_command;
@property(nonatomic) unsigned long long signalType; // @synthesize signalType=_signalType;
@property(nonatomic) long long ver; // @synthesize ver=_ver;
- (void).cxx_destruct;

@end

