//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class OPRRoomCommentCellData, UIImageView, YYLabel;

@interface OPRRoomCommentCell : UICollectionViewCell
{
    OPRRoomCommentCellData *_data;
    CDUnknownBlockType _avatarTapBlock;
    UIImageView *_avatarView;
    UIImageView *_avatarCover;
    YYLabel *_commentLabel;
}

+ (struct CGSize)cellSize:(id)arg1;
+ (struct CGRect)commentLabelRect;
+ (id)contentText:(id)arg1;
@property(nonatomic) __weak YYLabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(nonatomic) __weak UIImageView *avatarCover; // @synthesize avatarCover=_avatarCover;
@property(nonatomic) __weak UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(copy, nonatomic) CDUnknownBlockType avatarTapBlock; // @synthesize avatarTapBlock=_avatarTapBlock;
@property(retain, nonatomic) OPRRoomCommentCellData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)avatarDidTap;
- (id)initWithFrame:(struct CGRect)arg1;

@end

