//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPRRaceMicData : NSObject
{
    NSString *_segmentId;
    NSString *_roomId;
    long long _turn;
}

@property(nonatomic) long long turn; // @synthesize turn=_turn;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(copy, nonatomic) NSString *segmentId; // @synthesize segmentId=_segmentId;
- (void).cxx_destruct;

@end

