//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRRoomUserRankingViewController.h"

@class NSArray, OPRQueryRoomResultCardItemData, OPRRoomFuncEndTabBar, UIView;

@interface OPRRoomFuncEndViewController : OPRRoomUserRankingViewController
{
    _Bool _currentRound;
    _Bool _hasCardItems;
    OPRQueryRoomResultCardItemData *_myCard;
    NSArray *_cardList;
    UIView *_emptyView;
    UIView *_alertView;
    OPRRoomFuncEndTabBar *_tabbar;
}

@property(retain, nonatomic) OPRRoomFuncEndTabBar *tabbar; // @synthesize tabbar=_tabbar;
@property(retain, nonatomic) UIView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) UIView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) NSArray *cardList; // @synthesize cardList=_cardList;
@property(retain, nonatomic) OPRQueryRoomResultCardItemData *myCard; // @synthesize myCard=_myCard;
@property(nonatomic) _Bool hasCardItems; // @synthesize hasCardItems=_hasCardItems;
@property(nonatomic) _Bool currentRound; // @synthesize currentRound=_currentRound;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)onMyCardAlertOKClick;
- (id)createMyCardAlertContentView:(id)arg1 hasMyCard:(_Bool)arg2;
- (_Bool)checkTheCard;
- (void)onTheFirstAlertOKClick;
- (id)createfirstAlertContentView:(id)arg1;
- (_Bool)checkTheFirst;
- (void)checkAlert;
- (void)checkEmpty;
- (void)onRefreshContentView;
- (void)onRefreshDataResult:(id)arg1;
- (void)onCreatedContentView;
- (void)viewDidLoad;
- (id)initWithRoomItem:(id)arg1 withCurrentRound:(_Bool)arg2;

@end

