//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "SDCycleScrollViewDelegate-Protocol.h"

@class NSString, OPRRoomModeListBannerItem, SDCycleScrollView;
@protocol OPRRoomModeListBannerCellDelegate;

@interface OPRRoomModeListBannerCell : UITableViewCell <SDCycleScrollViewDelegate>
{
    OPRRoomModeListBannerItem *_item;
    id <OPRRoomModeListBannerCellDelegate> _delegate;
    SDCycleScrollView *_bannerView;
}

+ (double)cellHeight:(double)arg1;
@property(retain, nonatomic) SDCycleScrollView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) __weak id <OPRRoomModeListBannerCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) OPRRoomModeListBannerItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (id)scrollCollectionView;
- (void)cycleScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

