//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface OPRRoomFlyView : UIView
{
    UIImageView *_imageView;
    UILabel *_contentLabel;
    double _originWidth;
}

@property(nonatomic) double originWidth; // @synthesize originWidth=_originWidth;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)hide;
- (void)showWithBGImage:(id)arg1 content:(id)arg2;
- (void)showWithBGImage:(id)arg1 attributeContent:(id)arg2;
- (void)_showWithBGImage:(id)arg1;
- (void)setBgImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

