//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "OPRQueryChordResManagerObserver-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString, UICollectionView;

@interface OPRSingingPlayStyleSelectView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, OPRQueryChordResManagerObserver>
{
    _Bool _isEnsemble;
    CDUnknownBlockType _selectNewPlayStyle;
    UIView *_bgView;
    UICollectionView *_collectionView;
    NSArray *_cellItems;
}

@property(retain, nonatomic) NSArray *cellItems; // @synthesize cellItems=_cellItems;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) _Bool isEnsemble; // @synthesize isEnsemble=_isEnsemble;
@property(copy, nonatomic) CDUnknownBlockType selectNewPlayStyle; // @synthesize selectNewPlayStyle=_selectNewPlayStyle;
- (void).cxx_destruct;
- (void)playStyleItemDidFinishDownloading:(id)arg1;
- (void)playStyleItemBeginDownloading:(id)arg1;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (unsigned long long)playStyleCount;
- (void)setInstrument:(id)arg1 withPlayStyleItem:(id)arg2;
- (void)layoutSubviews;
- (void)setupSelfView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

