//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSNumber, NSString, OPRSingingRoomContext, OPRSingingRoomStartTime, OPRSingingRoomUser;

@interface OPRSingingRoomItem : NSObject
{
    _Bool _starRoom;
    unsigned long long _roomType;
    NSString *_roomID;
    NSString *_name;
    unsigned long long _roundID;
    long long _inviteMode;
    OPRSingingRoomStartTime *_startTime;
    unsigned long long _myRole;
    OPRSingingRoomUser *_hoster;
    OPRSingingRoomUser *_me;
    NSArray *_albumList;
    NSArray *_players;
    unsigned long long _userCount;
    OPRSingingRoomContext *_context;
    NSDictionary *_extraInfo;
}

@property(retain, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(retain, nonatomic) OPRSingingRoomContext *context; // @synthesize context=_context;
@property(nonatomic) unsigned long long userCount; // @synthesize userCount=_userCount;
@property(retain, nonatomic) NSArray *players; // @synthesize players=_players;
@property(retain, nonatomic) NSArray *albumList; // @synthesize albumList=_albumList;
@property(retain, nonatomic) OPRSingingRoomUser *me; // @synthesize me=_me;
@property(retain, nonatomic) OPRSingingRoomUser *hoster; // @synthesize hoster=_hoster;
@property(nonatomic) unsigned long long myRole; // @synthesize myRole=_myRole;
@property(retain, nonatomic) OPRSingingRoomStartTime *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) long long inviteMode; // @synthesize inviteMode=_inviteMode;
@property(nonatomic) unsigned long long roundID; // @synthesize roundID=_roundID;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *roomID; // @synthesize roomID=_roomID;
@property(nonatomic) _Bool starRoom; // @synthesize starRoom=_starRoom;
@property(nonatomic) unsigned long long roomType; // @synthesize roomType=_roomType;
- (void).cxx_destruct;
- (id)init;
@property(readonly, copy, nonatomic) NSString *albumListString;
- (id)getUserWithID:(id)arg1;
@property(readonly, nonatomic) _Bool ext_starRoom;
@property(readonly, nonatomic) NSArray *ext_roomStrategy;
@property(readonly, copy, nonatomic) NSString *ext_activityId;
@property(readonly, copy, nonatomic) NSString *ext_preRoomId;
@property(readonly, nonatomic) unsigned long long ext_roomType;
@property(readonly, copy, nonatomic) NSString *ext_title;
@property(readonly, copy, nonatomic) NSNumber *ext_countTimeInteval;
@property(readonly, copy, nonatomic) NSNumber *ext_startTimeInteval;
@property(readonly, copy, nonatomic) NSString *ext_bgImage;

@end

