//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString, OPRAudioContentItem, OPRChordInstrumentPlayStyleItem, OPROriginCreateTempClip;

@interface OPRSingingInfo : NSObject
{
    _Bool _keyboardEnabled;
    _Bool _selectedCustomChordsDefaultIfNeed;
    _Bool _forceSelectDefaultChords;
    _Bool _forceOnSingMode;
    NSString *_lyric;
    NSNumber *_singMaxDuration;
    NSArray *_chords;
    NSArray *_customChords;
    OPRChordInstrumentPlayStyleItem *_forceUsePlayStyleItem;
    NSNumber *_pitchLevel;
    NSString *_segmentId;
    OPROriginCreateTempClip *_originClipData;
    OPRAudioContentItem *_audioItem;
}

@property(retain, nonatomic) OPRAudioContentItem *audioItem; // @synthesize audioItem=_audioItem;
@property(retain, nonatomic) OPROriginCreateTempClip *originClipData; // @synthesize originClipData=_originClipData;
@property(nonatomic) _Bool forceOnSingMode; // @synthesize forceOnSingMode=_forceOnSingMode;
@property(copy, nonatomic) NSString *segmentId; // @synthesize segmentId=_segmentId;
@property(retain, nonatomic) NSNumber *pitchLevel; // @synthesize pitchLevel=_pitchLevel;
@property(retain, nonatomic) OPRChordInstrumentPlayStyleItem *forceUsePlayStyleItem; // @synthesize forceUsePlayStyleItem=_forceUsePlayStyleItem;
@property(nonatomic) _Bool forceSelectDefaultChords; // @synthesize forceSelectDefaultChords=_forceSelectDefaultChords;
@property(nonatomic) _Bool selectedCustomChordsDefaultIfNeed; // @synthesize selectedCustomChordsDefaultIfNeed=_selectedCustomChordsDefaultIfNeed;
@property(retain, nonatomic) NSArray *customChords; // @synthesize customChords=_customChords;
@property(retain, nonatomic) NSArray *chords; // @synthesize chords=_chords;
@property(nonatomic) _Bool keyboardEnabled; // @synthesize keyboardEnabled=_keyboardEnabled;
@property(retain, nonatomic) NSNumber *singMaxDuration; // @synthesize singMaxDuration=_singMaxDuration;
@property(copy, nonatomic) NSString *lyric; // @synthesize lyric=_lyric;
- (void).cxx_destruct;

@end

