//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class OPRSingingRoomSonglistCVCellData, OPTouchBounceView, UIImageView, UILabel;
@protocol OPRSingingRoomSonglistCVCellDelegate;

@interface OPRSingingRoomSonglistCVCell : UICollectionViewCell
{
    id <OPRSingingRoomSonglistCVCellDelegate> _delegate;
    OPRSingingRoomSonglistCVCellData *_cellData;
    OPTouchBounceView *_bgView;
    UIImageView *_accessoryView;
    UILabel *_titleView;
}

+ (double)viewWidthWithData:(id)arg1;
@property(retain, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIImageView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) OPTouchBounceView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) OPRSingingRoomSonglistCVCellData *cellData; // @synthesize cellData=_cellData;
@property(nonatomic) __weak id <OPRSingingRoomSonglistCVCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewDidTap:(id)arg1;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

