//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, LOTAnimationView, OPRSingingGuideItemViewInfo, UIImageView, UILabel;

@interface OPRSingingGuideItemView : UIView
{
    OPRSingingGuideItemViewInfo *_viewInfo;
    UIView *_animationContentView;
    CALayer *_animationContentViewBgLayer;
    LOTAnimationView *_animationView;
    LOTAnimationView *_subAnimationView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIImageView *_imageView;
}

@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak LOTAnimationView *subAnimationView; // @synthesize subAnimationView=_subAnimationView;
@property(nonatomic) __weak LOTAnimationView *animationView; // @synthesize animationView=_animationView;
@property(nonatomic) __weak CALayer *animationContentViewBgLayer; // @synthesize animationContentViewBgLayer=_animationContentViewBgLayer;
@property(nonatomic) __weak UIView *animationContentView; // @synthesize animationContentView=_animationContentView;
@property(retain, nonatomic) OPRSingingGuideItemViewInfo *viewInfo; // @synthesize viewInfo=_viewInfo;
- (void).cxx_destruct;
- (void)playAnimation:(_Bool)arg1;
- (void)layoutSubViewWhenPureImage;
- (void)layoutAnimationView;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1 withItemInfo:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

