//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPTouchBounceView.h"

@class NSNumber, UIImageView, UILabel;

@interface OPRSingingCardResultControlItemView : OPTouchBounceView
{
    _Bool _customImageSize;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    NSNumber *_imageTitleMargin;
}

@property(retain, nonatomic) NSNumber *imageTitleMargin; // @synthesize imageTitleMargin=_imageTitleMargin;
@property(nonatomic) _Bool customImageSize; // @synthesize customImageSize=_customImageSize;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)sizeToFit;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

