//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, OPRInviteMyFollowService;

@interface OPRSingingRoomInviteMyFollowsManager : NSObject
{
    NSMutableDictionary *_inviteCache;
    OPRInviteMyFollowService *_inviteService;
}

+ (id)defaultManager;
@property(retain, nonatomic) OPRInviteMyFollowService *inviteService; // @synthesize inviteService=_inviteService;
@property(retain, nonatomic) NSMutableDictionary *inviteCache; // @synthesize inviteCache=_inviteCache;
- (void).cxx_destruct;
- (void)loadInvite;
- (void)storeInvite:(id)arg1;
- (double)inviteDuration;
- (_Bool)invite:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;

@end

