//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPCShareViewController.h"

@interface OPRShareBusinessCardViewController : OPCShareViewController
{
}

- (void)appWillTerminateWithNotification:(id)arg1;
- (_Bool)needDimissWhenShareStart;
- (void)onShareButtonClick:(id)arg1;
- (void)shareBtn:(id)arg1 applyPluginIndex:(unsigned long long)arg2;
- (id)shareBtn:(id)arg1 left:(double)arg2;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithBusinessCardData:(id)arg1;

@end

