//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRSingingChordItem.h"

#import "NSCoding-Protocol.h"

@class NSNumber, NSString;

@interface OPRSingingKeyPlayRecordItem : OPRSingingChordItem <NSCoding>
{
    _Bool _isExtraKey;
    _Bool _micEnable;
    _Bool _markForBiz;
    NSNumber *_produceTS;
    NSString *_type;
    NSString *_playStyle;
    NSString *_toneType;
    NSNumber *_tempoLevel;
    NSNumber *_pitchLevel;
    unsigned long long _clickKeyArea;
}

@property(nonatomic) _Bool markForBiz; // @synthesize markForBiz=_markForBiz;
@property(nonatomic) _Bool micEnable; // @synthesize micEnable=_micEnable;
@property(nonatomic) unsigned long long clickKeyArea; // @synthesize clickKeyArea=_clickKeyArea;
@property(nonatomic) _Bool isExtraKey; // @synthesize isExtraKey=_isExtraKey;
@property(retain, nonatomic) NSNumber *pitchLevel; // @synthesize pitchLevel=_pitchLevel;
@property(retain, nonatomic) NSNumber *tempoLevel; // @synthesize tempoLevel=_tempoLevel;
@property(copy, nonatomic) NSString *toneType; // @synthesize toneType=_toneType;
@property(copy, nonatomic) NSString *playStyle; // @synthesize playStyle=_playStyle;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSNumber *produceTS; // @synthesize produceTS=_produceTS;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

