//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseViewController.h"

#import "OPRSonglistMangerProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSArray, NSMutableArray, NSString, OPRSonglistData, OPRSonglistManger, OPRSonglistNormalCVCell, UICollectionView;

@interface OPRSonglistViewController : OPRBaseViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, OPRSonglistMangerProtocol>
{
    CDUnknownBlockType _confirmBlock;
    UICollectionView *_collectionView;
    OPRSonglistManger *_manager;
    NSMutableArray *_selectedSonglists;
    NSArray *_oriSelectedSonglists;
    unsigned long long _maxSelectedCount;
    unsigned long long _queryDataPageCount;
    NSString *_lastItemCursor;
    unsigned long long _viewStyle;
    OPRSonglistData *_lastSelectedData;
    OPRSonglistNormalCVCell *_lastSelectedCell;
}

@property(nonatomic) __weak OPRSonglistNormalCVCell *lastSelectedCell; // @synthesize lastSelectedCell=_lastSelectedCell;
@property(nonatomic) __weak OPRSonglistData *lastSelectedData; // @synthesize lastSelectedData=_lastSelectedData;
@property(nonatomic) unsigned long long viewStyle; // @synthesize viewStyle=_viewStyle;
@property(copy, nonatomic) NSString *lastItemCursor; // @synthesize lastItemCursor=_lastItemCursor;
@property(nonatomic) unsigned long long queryDataPageCount; // @synthesize queryDataPageCount=_queryDataPageCount;
@property(nonatomic) unsigned long long maxSelectedCount; // @synthesize maxSelectedCount=_maxSelectedCount;
@property(retain, nonatomic) NSArray *oriSelectedSonglists; // @synthesize oriSelectedSonglists=_oriSelectedSonglists;
@property(retain, nonatomic) NSMutableArray *selectedSonglists; // @synthesize selectedSonglists=_selectedSonglists;
@property(retain, nonatomic) OPRSonglistManger *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(copy, nonatomic) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock=_confirmBlock;
- (void).cxx_destruct;
- (void)songListmanager:(id)arg1 cancelLoadMore:(_Bool)arg2;
- (void)songListmanager:(id)arg1 responseWithSucceed:(_Bool)arg2 withLoadMore:(_Bool)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)onMenuButtonClick:(id)arg1;
- (void)refresh;
- (void)updateSelectedSonglist;
- (void)loadData;
- (void)initData;
- (long long)preferredStatusBarStyle;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)initWithManager:(id)arg1 seletedSonglists:(id)arg2 maxSelectCount:(unsigned long long)arg3 viewStyle:(unsigned long long)arg4;
- (id)initWithSonglists:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

