//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface OPRSingingChordItem : NSObject <NSCopying, NSCoding>
{
    NSString *_note;
    NSString *_showNote;
    NSNumber *_number;
    struct _NSRange _chordRange;
}

+ (id)showNote:(id)arg1 withPitchLevel:(unsigned long long)arg2;
+ (id)note:(id)arg1 withPitchLevel:(unsigned long long)arg2;
+ (id)singingChordItemFromSongChordItem:(id)arg1;
@property(retain, nonatomic) NSNumber *number; // @synthesize number=_number;
@property(copy, nonatomic) NSString *showNote; // @synthesize showNote=_showNote;
@property(copy, nonatomic) NSString *note; // @synthesize note=_note;
@property(nonatomic) struct _NSRange chordRange; // @synthesize chordRange=_chordRange;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

