//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface OPRShareInviteData : NSObject
{
    _Bool _isFunc;
    NSString *_sender;
    NSString *_roomId;
    NSArray *_songsList;
    NSString *_hostID;
    NSString *_isHost;
}

@property(copy, nonatomic) NSString *isHost; // @synthesize isHost=_isHost;
@property(copy, nonatomic) NSString *hostID; // @synthesize hostID=_hostID;
@property(nonatomic) _Bool isFunc; // @synthesize isFunc=_isFunc;
@property(copy, nonatomic) NSArray *songsList; // @synthesize songsList=_songsList;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
- (void).cxx_destruct;

@end

