//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CALayer, CAShapeLayer, UIColor;

@interface OPRSingingStateButton : UIButton
{
    _Bool _enableInnerLayerAniamtionOnReadyToSingState;
    UIColor *_progressCircleBgColor;
    UIColor *_progressCircleColor;
    double _innerLayerPadding;
    UIColor *_innterLayerColor;
    UIColor *_titleColorOnNotReadyToSingState;
    unsigned long long _singState;
    double _timeout;
    double _progress;
    CAShapeLayer *_progressBgLayer;
    CALayer *_innerBgLayer;
    CAShapeLayer *_progressAnimationLayer;
}

@property(nonatomic) __weak CAShapeLayer *progressAnimationLayer; // @synthesize progressAnimationLayer=_progressAnimationLayer;
@property(nonatomic) __weak CALayer *innerBgLayer; // @synthesize innerBgLayer=_innerBgLayer;
@property(nonatomic) __weak CAShapeLayer *progressBgLayer; // @synthesize progressBgLayer=_progressBgLayer;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) _Bool enableInnerLayerAniamtionOnReadyToSingState; // @synthesize enableInnerLayerAniamtionOnReadyToSingState=_enableInnerLayerAniamtionOnReadyToSingState;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(nonatomic) unsigned long long singState; // @synthesize singState=_singState;
@property(retain, nonatomic) UIColor *titleColorOnNotReadyToSingState; // @synthesize titleColorOnNotReadyToSingState=_titleColorOnNotReadyToSingState;
@property(retain, nonatomic) UIColor *innterLayerColor; // @synthesize innterLayerColor=_innterLayerColor;
@property(nonatomic) double innerLayerPadding; // @synthesize innerLayerPadding=_innerLayerPadding;
@property(retain, nonatomic) UIColor *progressCircleColor; // @synthesize progressCircleColor=_progressCircleColor;
@property(retain, nonatomic) UIColor *progressCircleBgColor; // @synthesize progressCircleBgColor=_progressCircleBgColor;
- (void).cxx_destruct;
- (void)resumeLayer:(id)arg1;
- (void)pauseLayer:(id)arg1;
- (void)pause:(_Bool)arg1;
- (void)updateSingState;
- (void)showInnerLayerAniamtion:(_Bool)arg1;
- (void)startAnimation;
- (void)startAnimationAt:(double)arg1;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

