//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "CAAnimationDelegate-Protocol.h"

@class CAGradientLayer, NSString, OPRSingingSynthKeyboardItem, OPTouchBounceView, UILabel, UIView;

@interface OPRSingingSynthKeyboardCell : UICollectionViewCell <CAAnimationDelegate>
{
    _Bool _simulatingTouch;
    OPTouchBounceView *_bgView;
    UIView *_bgViewGradientLayerView;
    CAGradientLayer *_bgViewGradientLayer;
    UIView *_keyLabelBgView;
    UILabel *_keyLabel;
    UIView *_areaSeparatorView;
    OPRSingingSynthKeyboardItem *_item;
    CDUnknownBlockType _touchBeginBlock;
    CDUnknownBlockType _touchMoveBlock;
    unsigned long long _clickKeyArea;
    UIView *_animationViewBgView;
    UIView *_touchView;
    unsigned long long _cellIndex;
    UIView *_progressAnimationView;
}

+ (id)animationColorHexValueWithIndex:(unsigned long long)arg1;
@property(nonatomic) _Bool simulatingTouch; // @synthesize simulatingTouch=_simulatingTouch;
@property(nonatomic) __weak UIView *progressAnimationView; // @synthesize progressAnimationView=_progressAnimationView;
@property(nonatomic) unsigned long long cellIndex; // @synthesize cellIndex=_cellIndex;
@property(nonatomic) __weak UIView *touchView; // @synthesize touchView=_touchView;
@property(retain, nonatomic) UIView *animationViewBgView; // @synthesize animationViewBgView=_animationViewBgView;
@property(nonatomic) unsigned long long clickKeyArea; // @synthesize clickKeyArea=_clickKeyArea;
@property(copy, nonatomic) CDUnknownBlockType touchMoveBlock; // @synthesize touchMoveBlock=_touchMoveBlock;
@property(copy, nonatomic) CDUnknownBlockType touchBeginBlock; // @synthesize touchBeginBlock=_touchBeginBlock;
@property(nonatomic) __weak OPRSingingSynthKeyboardItem *item; // @synthesize item=_item;
@property(nonatomic) __weak UIView *areaSeparatorView; // @synthesize areaSeparatorView=_areaSeparatorView;
@property(retain, nonatomic) UILabel *keyLabel; // @synthesize keyLabel=_keyLabel;
@property(retain, nonatomic) UIView *keyLabelBgView; // @synthesize keyLabelBgView=_keyLabelBgView;
@property(nonatomic) __weak CAGradientLayer *bgViewGradientLayer; // @synthesize bgViewGradientLayer=_bgViewGradientLayer;
@property(nonatomic) __weak UIView *bgViewGradientLayerView; // @synthesize bgViewGradientLayerView=_bgViewGradientLayerView;
@property(retain, nonatomic) OPTouchBounceView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)showComboAniamtionWithNum:(unsigned long long)arg1;
- (void)playProgressAnimation:(_Bool)arg1 duration:(double)arg2;
- (void)showHighlightMark:(_Bool)arg1 withTagSize:(struct CGSize)arg2 animated:(_Bool)arg3;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchDo:(id)arg1 withClickArea:(id)arg2;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

