//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSNumber;

@interface OPRSingingPlayChordDataRecorder : NSObject
{
    _Bool _currentSongChordItemsIsCustomChordItems;
    _Bool _didPlayNoromalChord;
    _Bool _didPlayExtraChord;
    NSNumber *_beginRecordTs;
    NSArray *_songChordItems;
    NSArray *_customChordItems;
    NSMutableArray *_playChordItems;
}

+ (id)shareInstance;
@property(nonatomic) _Bool didPlayExtraChord; // @synthesize didPlayExtraChord=_didPlayExtraChord;
@property(nonatomic) _Bool didPlayNoromalChord; // @synthesize didPlayNoromalChord=_didPlayNoromalChord;
@property(retain, nonatomic) NSMutableArray *playChordItems; // @synthesize playChordItems=_playChordItems;
@property(nonatomic) _Bool currentSongChordItemsIsCustomChordItems; // @synthesize currentSongChordItemsIsCustomChordItems=_currentSongChordItemsIsCustomChordItems;
@property(retain, nonatomic) NSArray *customChordItems; // @synthesize customChordItems=_customChordItems;
@property(retain, nonatomic) NSArray *songChordItems; // @synthesize songChordItems=_songChordItems;
@property(retain, nonatomic) NSNumber *beginRecordTs; // @synthesize beginRecordTs=_beginRecordTs;
- (void).cxx_destruct;
- (_Bool)didPlayChord;
- (void)removeAllPlayChordData;
- (id)playRecordData;
- (void)addKeyPlayRecordItem:(id)arg1;
- (void)beginRecord;
- (id)init;

@end

