//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class OPTouchBounceButton, UIButton, UILabel;

@interface OPRSingingCardPlayerListTopbar : UIView
{
    CDUnknownBlockType _backBlock;
    CDUnknownBlockType _orderTypeClick;
    unsigned long long _orderType;
    UIButton *_backButton;
    UILabel *_titleLabel;
    UIView *_btnContainer;
    UIView *_lineView;
    OPTouchBounceButton *_orderNewBtn;
    OPTouchBounceButton *_orderHotBtn;
    OPTouchBounceButton *_freeStyleBtn;
}

@property(retain, nonatomic) OPTouchBounceButton *freeStyleBtn; // @synthesize freeStyleBtn=_freeStyleBtn;
@property(retain, nonatomic) OPTouchBounceButton *orderHotBtn; // @synthesize orderHotBtn=_orderHotBtn;
@property(retain, nonatomic) OPTouchBounceButton *orderNewBtn; // @synthesize orderNewBtn=_orderNewBtn;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *btnContainer; // @synthesize btnContainer=_btnContainer;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) unsigned long long orderType; // @synthesize orderType=_orderType;
@property(copy, nonatomic) CDUnknownBlockType orderTypeClick; // @synthesize orderTypeClick=_orderTypeClick;
@property(copy, nonatomic) CDUnknownBlockType backBlock; // @synthesize backBlock=_backBlock;
- (void).cxx_destruct;
- (void)adJustLineView:(_Bool)arg1;
- (void)layoutSubviews;
- (void)onFreeStyleBtnClick:(id)arg1;
- (void)onOrderHotBtnClick:(id)arg1;
- (void)onOrderNewBtnClick:(id)arg1;
- (void)onButtonClicked:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

