//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class OPRSingingAudioController;

@interface OPRSoundTimeCutView : UIView
{
    UIView *_tagView;
    double _orginX;
    CDUnknownBlockType _touchMove;
    CDUnknownBlockType _touchEnd;
    OPRSingingAudioController *_audioController;
    struct CGPoint _startPoint;
}

@property(retain, nonatomic) OPRSingingAudioController *audioController; // @synthesize audioController=_audioController;
@property(copy, nonatomic) CDUnknownBlockType touchEnd; // @synthesize touchEnd=_touchEnd;
@property(copy, nonatomic) CDUnknownBlockType touchMove; // @synthesize touchMove=_touchMove;
@property(nonatomic) double orginX; // @synthesize orginX=_orginX;
@property(nonatomic) struct CGPoint startPoint; // @synthesize startPoint=_startPoint;
@property(retain, nonatomic) UIView *tagView; // @synthesize tagView=_tagView;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;

@end

