//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, OPRSingingScreenRecorder, UIViewController;

@protocol OPRSingingScreenRecorderDelegate <NSObject>

@optional
- (void)screenRecorder:(OPRSingingScreenRecorder *)arg1 recordingDidFailWithSystemError:(NSError *)arg2 withBizError:(unsigned long long)arg3;
- (void)screenRecorderDidFinishRecording:(OPRSingingScreenRecorder *)arg1 withPresentRecordingPreviewWithController:(UIViewController *)arg2;
- (void)screenRecorderBeginRecording:(OPRSingingScreenRecorder *)arg1;
@end

