//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "OPRAudioPlayItemReceiverProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CAGradientLayer, NSString, NSTimer, OPCUserAvatarView, OPRAudioDescLabel, OPRSingCardBackgroundView, OPRSingCardMusicBarView, OPRSingingCardItem, OPRSingingCardSingButton, OPRSingingCardSingResultView, OPRSongPlayInstrumentRecordData, OPTouchBounceButton, UIButton, UIFont, UIImageView, UILabel, UIView, YYTextView;
@protocol OPRSingingCardContentCellDelegate, OPRSingingCardContentCellQueryDelegate;

@interface OPRSingingCardContentCell : UICollectionViewCell <UIGestureRecognizerDelegate, OPRAudioPlayItemReceiverProtocol>
{
    _Bool _pauseByUser;
    id <OPRSingingCardContentCellDelegate> _delegate;
    id <OPRSingingCardContentCellQueryDelegate> _queryDelegate;
    OPRSingingCardItem *_item;
    OPRSongPlayInstrumentRecordData *_chordRecordData;
    OPRSongPlayInstrumentRecordData *_beatRecordData;
    UIImageView *_contentContainer;
    OPRSingCardBackgroundView *_backgroundColorsView;
    UIView *_headerView;
    UIButton *_menuBtn;
    UIView *_controlContentView;
    UIView *_buttonsContainerView;
    OPRSingingCardSingButton *_singBtn;
    OPTouchBounceButton *_likeBtn;
    OPTouchBounceButton *_ensembleBtn;
    OPTouchBounceButton *_commentBtn;
    UILabel *_commentCount;
    OPTouchBounceButton *_shareBtn;
    UIView *_userInfoContentView;
    UIView *_userIconShadowView;
    OPCUserAvatarView *_userIconViewLeft;
    OPCUserAvatarView *_userIconViewRight;
    OPRSingCardMusicBarView *_musicWaveLeft;
    OPRSingCardMusicBarView *_musicWaveRight;
    UIButton *_audioDescView;
    OPRAudioDescLabel *_audioDescLabel;
    UILabel *_playedUserCountLabel;
    UIView *_songInfoContentView;
    UILabel *_songTitle;
    UILabel *_singOriginalTag;
    UIView *_lyricViewContainer;
    YYTextView *_lyricView;
    CAGradientLayer *_songLyrLayer;
    UIButton *_pauseBtn;
    double _lyricLineHeight;
    UIFont *_lyricFont;
    unsigned long long _lastChordIndex;
    UIView *_moreMenuView;
    OPRSingingCardSingResultView *_singResultView;
    UIView *_guideContentView;
    UIView *_noUserPlayedUserInfoContainer;
    UIImageView *_noUserPlayedIcon;
    UILabel *_noUserPlayedLabel;
    NSTimer *_noUserPlayedTimer;
    double _startPlayTimePoint;
    double _hasPlayedTime;
}

+ (double)cellUIScale;
@property(nonatomic) double hasPlayedTime; // @synthesize hasPlayedTime=_hasPlayedTime;
@property(nonatomic) double startPlayTimePoint; // @synthesize startPlayTimePoint=_startPlayTimePoint;
@property(retain, nonatomic) NSTimer *noUserPlayedTimer; // @synthesize noUserPlayedTimer=_noUserPlayedTimer;
@property(nonatomic) __weak UILabel *noUserPlayedLabel; // @synthesize noUserPlayedLabel=_noUserPlayedLabel;
@property(nonatomic) __weak UIImageView *noUserPlayedIcon; // @synthesize noUserPlayedIcon=_noUserPlayedIcon;
@property(nonatomic) __weak UIView *noUserPlayedUserInfoContainer; // @synthesize noUserPlayedUserInfoContainer=_noUserPlayedUserInfoContainer;
@property(nonatomic) __weak UIView *guideContentView; // @synthesize guideContentView=_guideContentView;
@property(nonatomic) _Bool pauseByUser; // @synthesize pauseByUser=_pauseByUser;
@property(nonatomic) __weak OPRSingingCardSingResultView *singResultView; // @synthesize singResultView=_singResultView;
@property(nonatomic) __weak UIView *moreMenuView; // @synthesize moreMenuView=_moreMenuView;
@property(nonatomic) unsigned long long lastChordIndex; // @synthesize lastChordIndex=_lastChordIndex;
@property(retain, nonatomic) UIFont *lyricFont; // @synthesize lyricFont=_lyricFont;
@property(nonatomic) double lyricLineHeight; // @synthesize lyricLineHeight=_lyricLineHeight;
@property(nonatomic) __weak UIButton *pauseBtn; // @synthesize pauseBtn=_pauseBtn;
@property(retain, nonatomic) CAGradientLayer *songLyrLayer; // @synthesize songLyrLayer=_songLyrLayer;
@property(nonatomic) __weak YYTextView *lyricView; // @synthesize lyricView=_lyricView;
@property(nonatomic) __weak UIView *lyricViewContainer; // @synthesize lyricViewContainer=_lyricViewContainer;
@property(nonatomic) __weak UILabel *singOriginalTag; // @synthesize singOriginalTag=_singOriginalTag;
@property(nonatomic) __weak UILabel *songTitle; // @synthesize songTitle=_songTitle;
@property(nonatomic) __weak UIView *songInfoContentView; // @synthesize songInfoContentView=_songInfoContentView;
@property(nonatomic) __weak UILabel *playedUserCountLabel; // @synthesize playedUserCountLabel=_playedUserCountLabel;
@property(nonatomic) __weak OPRAudioDescLabel *audioDescLabel; // @synthesize audioDescLabel=_audioDescLabel;
@property(nonatomic) __weak UIButton *audioDescView; // @synthesize audioDescView=_audioDescView;
@property(nonatomic) __weak OPRSingCardMusicBarView *musicWaveRight; // @synthesize musicWaveRight=_musicWaveRight;
@property(nonatomic) __weak OPRSingCardMusicBarView *musicWaveLeft; // @synthesize musicWaveLeft=_musicWaveLeft;
@property(nonatomic) __weak OPCUserAvatarView *userIconViewRight; // @synthesize userIconViewRight=_userIconViewRight;
@property(nonatomic) __weak OPCUserAvatarView *userIconViewLeft; // @synthesize userIconViewLeft=_userIconViewLeft;
@property(nonatomic) __weak UIView *userIconShadowView; // @synthesize userIconShadowView=_userIconShadowView;
@property(nonatomic) __weak UIView *userInfoContentView; // @synthesize userInfoContentView=_userInfoContentView;
@property(nonatomic) __weak OPTouchBounceButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(nonatomic) __weak UILabel *commentCount; // @synthesize commentCount=_commentCount;
@property(nonatomic) __weak OPTouchBounceButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(nonatomic) __weak OPTouchBounceButton *ensembleBtn; // @synthesize ensembleBtn=_ensembleBtn;
@property(nonatomic) __weak OPTouchBounceButton *likeBtn; // @synthesize likeBtn=_likeBtn;
@property(nonatomic) __weak OPRSingingCardSingButton *singBtn; // @synthesize singBtn=_singBtn;
@property(nonatomic) __weak UIView *buttonsContainerView; // @synthesize buttonsContainerView=_buttonsContainerView;
@property(nonatomic) __weak UIView *controlContentView; // @synthesize controlContentView=_controlContentView;
@property(nonatomic) __weak UIButton *menuBtn; // @synthesize menuBtn=_menuBtn;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak OPRSingCardBackgroundView *backgroundColorsView; // @synthesize backgroundColorsView=_backgroundColorsView;
@property(nonatomic) __weak UIImageView *contentContainer; // @synthesize contentContainer=_contentContainer;
@property(retain, nonatomic) OPRSongPlayInstrumentRecordData *beatRecordData; // @synthesize beatRecordData=_beatRecordData;
@property(retain, nonatomic) OPRSongPlayInstrumentRecordData *chordRecordData; // @synthesize chordRecordData=_chordRecordData;
@property(retain, nonatomic) OPRSingingCardItem *item; // @synthesize item=_item;
@property(nonatomic) __weak id <OPRSingingCardContentCellQueryDelegate> queryDelegate; // @synthesize queryDelegate=_queryDelegate;
@property(nonatomic) __weak id <OPRSingingCardContentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)playItemReceiverPlayPrevious;
- (void)playItemReceiverPlayNext;
- (_Bool)playItemReceiverCanAutoPlayNext;
- (void)onPanGestureChanged:(id)arg1;
- (void)onNoUserPlayedTimerCountDown:(id)arg1;
- (void)stopNoUserPlayedTimer;
- (void)startNoUserPlayedTimer:(double)arg1;
- (struct CGRect)frameOfTextRange:(struct _NSRange)arg1;
- (void)startAvatarScaleAnimation;
- (void)configlyricViewText;
- (void)updateLyrTextViewVisibleFrameWithItem:(id)arg1;
- (void)updatePlayingWithCurrentTime:(double)arg1 totalDuration:(double)arg2;
- (id)stretchLeftAndRightWithContainerSize:(struct CGSize)arg1 leftCapPercent:(double)arg2 topCapHeight:(double)arg3 image:(id)arg4;
- (void)onItemStateChanged;
- (void)updateUIForStateInit:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeItemObserver;
- (void)addItemObserver;
- (void)onMenuBtnClick;
- (void)onCollectBtnClick:(id)arg1;
- (void)onEnsembleBtnClick;
- (void)onCommentBtnClick;
- (void)onShareBtnClick;
- (void)updateNoUsedPlayerPausedStatus;
- (void)onPauseBtnClick;
- (void)onAudioDescClick;
- (void)onUserIconClick;
- (void)onLikeBtnClick;
- (void)onSureBtnClick;
- (void)onChangeSongListBtnClick;
- (void)onPlayerStopPlay;
- (void)onPlayerPlayPause:(_Bool)arg1;
- (void)onPlayerPlayComplete:(_Bool)arg1 error:(id)arg2;
- (void)onPlayerPlaying:(double)arg1 totalDuration:(double)arg2;
- (void)onPlayerStartPlay:(_Bool)arg1 duration:(double)arg2;
- (_Bool)playerIsStoping;
- (void)playerStopPlaying;
- (void)playerPause:(_Bool)arg1;
- (void)playerDealloc;
- (void)playerInit;
- (void)updateNoUserPlayedDisplay;
- (void)showAudioDesc:(_Bool)arg1;
- (void)updateDescription;
- (void)updateControlBtns;
- (void)updateUserContentView;
- (void)updateCommentBtnView;
- (void)updateLikeBtnView;
- (id)scene;
- (_Bool)isOwner;
- (void)resetResultViewAudioPlay;
- (void)playMedia;
- (void)showGuideTipsIfNeed;
- (void)updateSongInfoContentViewLayout;
- (void)playMusicWave:(_Bool)arg1;
- (void)setupSingResultView:(id)arg1;
- (void)showResultView:(_Bool)arg1;
- (void)setupSongContentView:(id)arg1 frame:(struct CGRect)arg2;
- (void)setupUserContentView:(id)arg1 frame:(struct CGRect)arg2;
- (void)setupControlView:(id)arg1;
- (void)setupHeaderView:(id)arg1;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

