//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString, OPRSongExtendDataAudioAttributeVolume;

@interface OPRSongExtendDataAudioAttributes : NSObject <NSCoding, NSCopying>
{
    NSNumber *_vocalDoubling;
    OPRSongExtendDataAudioAttributeVolume *_volume;
    NSString *_micPortType;
    NSNumber *_ensembleType;
    NSNumber *_volumeBalance;
}

@property(retain, nonatomic) NSNumber *volumeBalance; // @synthesize volumeBalance=_volumeBalance;
@property(retain, nonatomic) NSNumber *ensembleType; // @synthesize ensembleType=_ensembleType;
@property(copy, nonatomic) NSString *micPortType; // @synthesize micPortType=_micPortType;
@property(retain, nonatomic) OPRSongExtendDataAudioAttributeVolume *volume; // @synthesize volume=_volume;
@property(retain, nonatomic) NSNumber *vocalDoubling; // @synthesize vocalDoubling=_vocalDoubling;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

