//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "OPRSonglistBottombarViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSMutableArray, NSString, OPRSonglistBottombarView, UICollectionView;

@interface OPRSonglistEditView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, OPRSonglistBottombarViewDelegate>
{
    CDUnknownBlockType _confirmBlock;
    UIView *_parentView;
    UIView *_contentView;
    OPRSonglistBottombarView *_contentViewTopbar;
    UICollectionView *_collectionView;
    UIView *_backgroundView;
    unsigned long long _maxSelectedCount;
    NSMutableArray *_songlists;
    unsigned long long _viewStyle;
}

@property(nonatomic) unsigned long long viewStyle; // @synthesize viewStyle=_viewStyle;
@property(retain, nonatomic) NSMutableArray *songlists; // @synthesize songlists=_songlists;
@property(nonatomic) unsigned long long maxSelectedCount; // @synthesize maxSelectedCount=_maxSelectedCount;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) OPRSonglistBottombarView *contentViewTopbar; // @synthesize contentViewTopbar=_contentViewTopbar;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(copy, nonatomic) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock=_confirmBlock;
- (void).cxx_destruct;
- (unsigned long long)selectedItemsCountInSonglistBottomBar:(id)arg1;
- (unsigned long long)maxSelectedCountInSonglistBottomBar:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)onBackgroundViewClick;
- (void)hideWithAnimated:(_Bool)arg1;
- (void)showWithSonglists:(id)arg1 maxSelectCount:(unsigned long long)arg2 animated:(_Bool)arg3;
- (id)initWithParentView:(id)arg1 withViewStyle:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

