//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSHashTable, NSMutableArray, NSString, OPRSonglistDataQueryService;

@interface OPRSonglistManger : NSObject
{
    _Bool _noMoreData;
    _Bool _isRefresh;
    _Bool _isHot;
    NSHashTable *_observerTable;
    NSMutableArray *_dataList;
    OPRSonglistDataQueryService *_queryDataService;
    NSString *_lastItemCursor;
    NSMutableArray *_songlistIDs;
}

+ (id)songListManager;
+ (id)hotListManager;
@property(retain, nonatomic) NSMutableArray *songlistIDs; // @synthesize songlistIDs=_songlistIDs;
@property(nonatomic) _Bool isHot; // @synthesize isHot=_isHot;
@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(copy, nonatomic) NSString *lastItemCursor; // @synthesize lastItemCursor=_lastItemCursor;
@property(retain, nonatomic) OPRSonglistDataQueryService *queryDataService; // @synthesize queryDataService=_queryDataService;
@property(retain, nonatomic) NSMutableArray *dataList; // @synthesize dataList=_dataList;
@property(retain, nonatomic) NSHashTable *observerTable; // @synthesize observerTable=_observerTable;
@property(nonatomic) _Bool noMoreData; // @synthesize noMoreData=_noMoreData;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)queryCancel:(_Bool)arg1;
- (void)response:(_Bool)arg1 loadMore:(_Bool)arg2;
- (void)cancel;
- (_Bool)loadMore;
- (_Bool)refresh;
- (_Bool)querySonglistInfo;
@property(readonly, nonatomic) NSArray *songlists;
- (id)init;
- (id)initWithSonglistIDs:(id)arg1;

@end

