//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "OPRSingingCardItemProtocol-Protocol.h"

@class NSNumber, NSString, OPRAudioPlayItem, OPRContentGeneratingContext, OPROriginCreateTempClip, OPRSongSegmentData, OPRSonglistData;

@interface OPRSingingCardItem : NSObject <NSCoding, NSCopying, OPRSingingCardItemProtocol>
{
    _Bool _hideChangeSonglistFeature;
    unsigned long long _cardIndex;
    OPRSongSegmentData *_segment;
    OPRSonglistData *_songlist;
    unsigned long long _state;
    NSString *_firstPlayChordNote;
    NSNumber *_isEntryOwner;
    OPRAudioPlayItem *_playerItem;
    OPROriginCreateTempClip *_originCreateData;
    OPRContentGeneratingContext *_contentGeneratingContext;
}

@property(retain, nonatomic) OPRContentGeneratingContext *contentGeneratingContext; // @synthesize contentGeneratingContext=_contentGeneratingContext;
@property(retain, nonatomic) OPROriginCreateTempClip *originCreateData; // @synthesize originCreateData=_originCreateData;
@property(retain, nonatomic) OPRAudioPlayItem *playerItem; // @synthesize playerItem=_playerItem;
@property(copy, nonatomic) NSNumber *isEntryOwner; // @synthesize isEntryOwner=_isEntryOwner;
@property(copy, nonatomic) NSString *firstPlayChordNote; // @synthesize firstPlayChordNote=_firstPlayChordNote;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) OPRSonglistData *songlist; // @synthesize songlist=_songlist;
@property(retain, nonatomic) OPRSongSegmentData *segment; // @synthesize segment=_segment;
@property(nonatomic) _Bool hideChangeSonglistFeature; // @synthesize hideChangeSonglistFeature=_hideChangeSonglistFeature;
@property(nonatomic) unsigned long long cardIndex; // @synthesize cardIndex=_cardIndex;
- (void).cxx_destruct;
- (void)updateState:(unsigned long long)arg1;
- (void)showResultWithContext:(id)arg1 isEnsemble:(_Bool)arg2;
- (void)finishedPlay;
- (void)play;
- (void)reset;
@property(readonly, nonatomic) _Bool hasOriginalCreateData;
@property(readonly, nonatomic) _Bool noUserPlayed;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

