//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSNumber;

@interface OPRSingingPlayRecordData : NSObject <NSCoding>
{
    _Bool _isUserChord;
    NSNumber *_beginRecordTsWithOffset;
    NSNumber *_beginRecordTs;
    NSArray *_singingChordItems;
    NSArray *_playRecordItems;
}

+ (id)dataForPostWithRecordDataForPostList:(id)arg1;
+ (id)recordDataWithJsonStr:(id)arg1;
+ (id)dataForPostWithOriginalChordItems:(id)arg1 playChordItems:(id)arg2 withBeginRecordTs:(id)arg3 isUserChord:(_Bool)arg4;
@property(nonatomic) _Bool isUserChord; // @synthesize isUserChord=_isUserChord;
@property(retain, nonatomic) NSArray *playRecordItems; // @synthesize playRecordItems=_playRecordItems;
@property(retain, nonatomic) NSArray *singingChordItems; // @synthesize singingChordItems=_singingChordItems;
@property(retain, nonatomic) NSNumber *beginRecordTs; // @synthesize beginRecordTs=_beginRecordTs;
@property(retain, nonatomic) NSNumber *beginRecordTsWithOffset; // @synthesize beginRecordTsWithOffset=_beginRecordTsWithOffset;
- (void).cxx_destruct;
- (id)dataForPost:(_Bool)arg1;
- (id)dataForRecognize;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

