//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class OPRSingingRoomEndViewNormalCVCellData, UIImageView, UILabel, UIView;

@interface OPRSingingRoomEndViewNormalCVCell : UICollectionViewCell
{
    OPRSingingRoomEndViewNormalCVCellData *_cellData;
    UIView *_bgView;
    UILabel *_sortLabel;
    UIImageView *_userIconView;
    UILabel *_userNameLabel;
    UIImageView *_likeView;
    UILabel *_likeCountLabel;
}

+ (void)setMaxRank:(long long)arg1;
+ (double)minRankWith;
+ (void)setMaxLikeCount:(long long)arg1;
+ (double)minLikeCountWith;
@property(retain, nonatomic) UILabel *likeCountLabel; // @synthesize likeCountLabel=_likeCountLabel;
@property(retain, nonatomic) UIImageView *likeView; // @synthesize likeView=_likeView;
@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) UIImageView *userIconView; // @synthesize userIconView=_userIconView;
@property(retain, nonatomic) UILabel *sortLabel; // @synthesize sortLabel=_sortLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) OPRSingingRoomEndViewNormalCVCellData *cellData; // @synthesize cellData=_cellData;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

