//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, OPRTopicItem;

@interface OPRTopicHeaderViewItem : NSObject
{
    OPRTopicItem *_dataItem;
    NSNumber *_viewHeight;
}

@property(retain, nonatomic) NSNumber *viewHeight; // @synthesize viewHeight=_viewHeight;
@property(retain, nonatomic) OPRTopicItem *dataItem; // @synthesize dataItem=_dataItem;
- (void).cxx_destruct;

@end

