//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class OPCUserAvatarView, UIButton, UILabel;

@interface OPRTopicRankBottomInfoView : UIView
{
    CDUnknownBlockType _onClickUserIcon;
    CDUnknownBlockType _onClickRule;
    long long _ranking;
    UIView *_containerView;
    UIView *_separator;
    OPCUserAvatarView *_avatarView;
    UILabel *_infoLabel;
    UIButton *_ruleButton;
}

@property(retain, nonatomic) UIButton *ruleButton; // @synthesize ruleButton=_ruleButton;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) OPCUserAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) long long ranking; // @synthesize ranking=_ranking;
@property(copy, nonatomic) CDUnknownBlockType onClickRule; // @synthesize onClickRule=_onClickRule;
@property(copy, nonatomic) CDUnknownBlockType onClickUserIcon; // @synthesize onClickUserIcon=_onClickUserIcon;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

