//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseCollectionViewController.h"

@class NSArray, NSString, OPRTopicHeaderView, OPRTopicHeaderViewItem, OPRTopicRankBottomInfoView, UIButton, UIImageView, UIView;

@interface OPRTopicDetailViewController : OPRBaseCollectionViewController
{
    _Bool _hasRequestDetail;
    _Bool _hasRequestRanking;
    NSString *_spmUrl;
    OPRTopicHeaderViewItem *_item;
    NSArray *_contentList;
    NSArray *_recommentTabDataList;
    NSString *_nextCursor;
    unsigned long long _selectedTab;
    OPRTopicHeaderView *_topicHeaderView;
    UIImageView *_topicHeaderBgView;
    UIView *_topicContentBgView;
    UIButton *_topicContentEmptyView;
    UIButton *_joinButton;
    OPRTopicRankBottomInfoView *_rankBottomView;
}

@property(nonatomic) _Bool hasRequestRanking; // @synthesize hasRequestRanking=_hasRequestRanking;
@property(retain, nonatomic) OPRTopicRankBottomInfoView *rankBottomView; // @synthesize rankBottomView=_rankBottomView;
@property(nonatomic) _Bool hasRequestDetail; // @synthesize hasRequestDetail=_hasRequestDetail;
@property(retain, nonatomic) UIButton *joinButton; // @synthesize joinButton=_joinButton;
@property(retain, nonatomic) UIButton *topicContentEmptyView; // @synthesize topicContentEmptyView=_topicContentEmptyView;
@property(retain, nonatomic) UIView *topicContentBgView; // @synthesize topicContentBgView=_topicContentBgView;
@property(retain, nonatomic) UIImageView *topicHeaderBgView; // @synthesize topicHeaderBgView=_topicHeaderBgView;
@property(retain, nonatomic) OPRTopicHeaderView *topicHeaderView; // @synthesize topicHeaderView=_topicHeaderView;
@property(nonatomic) unsigned long long selectedTab; // @synthesize selectedTab=_selectedTab;
@property(retain, nonatomic) NSString *nextCursor; // @synthesize nextCursor=_nextCursor;
@property(copy, nonatomic) NSArray *recommentTabDataList; // @synthesize recommentTabDataList=_recommentTabDataList;
@property(retain, nonatomic) NSArray *contentList; // @synthesize contentList=_contentList;
@property(retain, nonatomic) OPRTopicHeaderViewItem *item; // @synthesize item=_item;
@property(copy, nonatomic) NSString *spmUrl; // @synthesize spmUrl=_spmUrl;
- (void).cxx_destruct;
- (_Bool)cms_feeds_refresh;
- (_Bool)isVaildTopic;
- (void)statControlToLogserver:(id)arg1;
- (void)statPageToLogserver:(id)arg1;
- (void)onCellClickPlay:(id)arg1;
- (void)showChordPlaybackPage:(id)arg1;
- (void)showContentPageWithAudioItem:(id)arg1 withCommentEntry:(_Bool)arg2;
- (void)showPersonalPage:(id)arg1 nickName:(id)arg2 avatarUrl:(id)arg3;
- (void)onMenuButtonClick:(id)arg1;
- (void)onBackButtonClick;
- (void)hideContentEmptyView;
- (void)updateLayoutAfterSetItem;
- (void)updateJoinButtonUI;
- (void)showContentEmptyView:(_Bool)arg1;
- (void)hideTopContentViews;
- (void)updateDetailUI;
- (void)checkTopicVaildStatus;
- (void)handleListData:(id)arg1 nextCursor:(id)arg2 isError:(_Bool)arg3 msg:(id)arg4 isRefresh:(_Bool)arg5 needFilter:(_Bool)arg6;
- (void)loadMoreMessage;
- (void)requestTopicDetail:(CDUnknownBlockType)arg1;
- (void)requestMyRank;
- (void)refreshMessage;
- (_Bool)enableLoadMore;
- (_Bool)enableRefresh;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)onAppWillResignActive:(id)arg1;
- (void)addNotification;
- (void)configMenuButton;
- (void)setupJoinButton;
- (_Bool)isRankTab;
- (void)setupHeadBgView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithTopicId:(id)arg1 withSpmUrl:(id)arg2;
- (void)dealloc;
- (id)initWithTopicItem:(id)arg1 withSpmUrl:(id)arg2;

@end

