//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "OPRAudioListBtnViewDelegate-Protocol.h"
#import "OPRAudioListTagViewDelegate-Protocol.h"

@class NSString, OPRAudioContentUGCTagView, OPRAudioDescLabel, OPRAudioListBtnView, OPRAudioListTagView, OPRSingingCardAudioPlayView, OPRUserPageUserPostListCVCellItem, UIButton, UILabel, UIView;

@interface OPRUserPageUserPostListCVCell : UICollectionViewCell <OPRAudioListBtnViewDelegate, OPRAudioListTagViewDelegate>
{
    UILabel *_audioTitleLabel;
    CDUnknownBlockType _onClickDelete;
    CDUnknownBlockType _onClickMore;
    CDUnknownBlockType _onClickShareBtn;
    CDUnknownBlockType _onClickCommentBtn;
    CDUnknownBlockType _onClickAudioPlay;
    CDUnknownBlockType _onClickDetailView;
    CDUnknownBlockType _onClickChordPlaybackBtn;
    CDUnknownBlockType _onClickTopicTag;
    CDUnknownBlockType _onClickAtTag;
    CDUnknownBlockType _onClickProductParamsTag;
    CDUnknownBlockType _onClickJoinEnsemble;
    CDUnknownBlockType _onClickEnsembleSwitch;
    OPRUserPageUserPostListCVCellItem *_cellItem;
    UIView *_bgView;
    UILabel *_postDateLabel;
    OPRAudioDescLabel *_audioDescLabel;
    UIView *_contentBgView;
    OPRAudioContentUGCTagView *_tagView;
    UIButton *_menuBtn;
    OPRSingingCardAudioPlayView *_audioPlayView;
    UIView *_separator;
    OPRAudioListBtnView *_stateBgView;
    OPRAudioListTagView *_tagsContentView;
    UIView *_editMenuViewBgView;
    UIView *_bottomSeparator;
}

@property(retain, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(retain, nonatomic) UIView *editMenuViewBgView; // @synthesize editMenuViewBgView=_editMenuViewBgView;
@property(nonatomic) __weak OPRAudioListTagView *tagsContentView; // @synthesize tagsContentView=_tagsContentView;
@property(retain, nonatomic) OPRAudioListBtnView *stateBgView; // @synthesize stateBgView=_stateBgView;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) OPRSingingCardAudioPlayView *audioPlayView; // @synthesize audioPlayView=_audioPlayView;
@property(retain, nonatomic) UIButton *menuBtn; // @synthesize menuBtn=_menuBtn;
@property(retain, nonatomic) OPRAudioContentUGCTagView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) UIView *contentBgView; // @synthesize contentBgView=_contentBgView;
@property(nonatomic) __weak OPRAudioDescLabel *audioDescLabel; // @synthesize audioDescLabel=_audioDescLabel;
@property(retain, nonatomic) UILabel *postDateLabel; // @synthesize postDateLabel=_postDateLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) OPRUserPageUserPostListCVCellItem *cellItem; // @synthesize cellItem=_cellItem;
@property(copy, nonatomic) CDUnknownBlockType onClickEnsembleSwitch; // @synthesize onClickEnsembleSwitch=_onClickEnsembleSwitch;
@property(copy, nonatomic) CDUnknownBlockType onClickJoinEnsemble; // @synthesize onClickJoinEnsemble=_onClickJoinEnsemble;
@property(copy, nonatomic) CDUnknownBlockType onClickProductParamsTag; // @synthesize onClickProductParamsTag=_onClickProductParamsTag;
@property(copy, nonatomic) CDUnknownBlockType onClickAtTag; // @synthesize onClickAtTag=_onClickAtTag;
@property(copy, nonatomic) CDUnknownBlockType onClickTopicTag; // @synthesize onClickTopicTag=_onClickTopicTag;
@property(copy, nonatomic) CDUnknownBlockType onClickChordPlaybackBtn; // @synthesize onClickChordPlaybackBtn=_onClickChordPlaybackBtn;
@property(copy, nonatomic) CDUnknownBlockType onClickDetailView; // @synthesize onClickDetailView=_onClickDetailView;
@property(copy, nonatomic) CDUnknownBlockType onClickAudioPlay; // @synthesize onClickAudioPlay=_onClickAudioPlay;
@property(copy, nonatomic) CDUnknownBlockType onClickCommentBtn; // @synthesize onClickCommentBtn=_onClickCommentBtn;
@property(copy, nonatomic) CDUnknownBlockType onClickShareBtn; // @synthesize onClickShareBtn=_onClickShareBtn;
@property(copy, nonatomic) CDUnknownBlockType onClickMore; // @synthesize onClickMore=_onClickMore;
@property(copy, nonatomic) CDUnknownBlockType onClickDelete; // @synthesize onClickDelete=_onClickDelete;
@property(retain, nonatomic) UILabel *audioTitleLabel; // @synthesize audioTitleLabel=_audioTitleLabel;
- (void).cxx_destruct;
- (void)onEnsembleBtnClick:(id)arg1;
- (void)onClickProductParamsItemBtn:(id)arg1;
- (void)onClickChordPlaybackBtn:(id)arg1;
- (void)onCommentBtnClick:(id)arg1;
- (void)onShareBtnClick:(id)arg1;
- (void)onLikeBtnClick:(id)arg1;
@property(readonly, nonatomic) double cellHeightAfterSetCellItem;
- (_Bool)isOwner;
- (void)reset;
- (void)showEditMenuView;
- (double)heightAfterLayoutWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setupSelfView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

