//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPRUserPageStat : NSObject
{
}

+ (void)statClickMyFav;
+ (void)statClickHonorRankEntry:(_Bool)arg1;
+ (void)statClickConfirmOnBusinessCardAlert;
+ (void)statShowBusinessCardAlert;
+ (void)statClickUserPageDeleteConfirmWithClipId:(id)arg1;
+ (void)statClickUserPageDeleteWithClipId:(id)arg1;
+ (void)statClickLikeListShareWithIsOwner:(_Bool)arg1 withClipId:(id)arg2;
+ (void)statClickUserPageShareWithIsOwner:(_Bool)arg1 withClipId:(id)arg2;
+ (void)statClickUserPageMoreWithIsOwner:(_Bool)arg1 withClipId:(id)arg2;
+ (void)statPVForFanlist;
+ (void)statPVForFollowinglist;
+ (void)statPVForOriginalCreateWithIsOwner:(_Bool)arg1 visitId:(id)arg2 entry:(id)arg3 withSongInfo:(id)arg4;
+ (void)statPVForLikeListWithIsOwner:(_Bool)arg1 visitId:(id)arg2 entry:(id)arg3 withSongInfo:(id)arg4;
+ (void)statPVForEnsembleWithIsOwner:(_Bool)arg1 visitId:(id)arg2 entry:(id)arg3 withSongInfo:(id)arg4;
+ (void)statPVForUserPageWithIsOwner:(_Bool)arg1 visitId:(id)arg2 entry:(id)arg3 withSongInfo:(id)arg4;

@end

