//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, OPRQueryUgcClipsItem;

@interface OPRUserPageUserPostListCVCellItem : NSObject
{
    NSNumber *_viewHeight;
    OPRQueryUgcClipsItem *_dataItem;
    unsigned long long _cellIndex;
}

@property(nonatomic) unsigned long long cellIndex; // @synthesize cellIndex=_cellIndex;
@property(retain, nonatomic) OPRQueryUgcClipsItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) NSNumber *viewHeight; // @synthesize viewHeight=_viewHeight;
- (void).cxx_destruct;

@end

