//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;

@interface OPRUserProductSegement : UIView
{
    unsigned long long _selectedIndex;
    CDUnknownBlockType _onSelectedChanged;
    NSArray *_titles;
    NSMutableArray *_butttonList;
    UIView *_selectView;
}

@property(retain, nonatomic) UIView *selectView; // @synthesize selectView=_selectView;
@property(retain, nonatomic) NSMutableArray *butttonList; // @synthesize butttonList=_butttonList;
@property(copy, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(copy, nonatomic) CDUnknownBlockType onSelectedChanged; // @synthesize onSelectedChanged=_onSelectedChanged;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (void)onBtnClick:(id)arg1;
- (id)createButtonWithTitle:(id)arg1 tag:(unsigned long long)arg2;
- (void)setupUI;
- (id)initWithTitles:(id)arg1;
- (void)layoutSubviews;

@end

