//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class OPRQueryUgcClipsItem, UILabel;

@interface OPRUserOriginCreateCell : UICollectionViewCell
{
    OPRQueryUgcClipsItem *_item;
    UILabel *_titleLabel;
    UILabel *_lyrlabel;
    UILabel *_tagLabel;
}

+ (double)itemHeight;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) UILabel *lyrlabel; // @synthesize lyrlabel=_lyrlabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) OPRQueryUgcClipsItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

