//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "OPSNavigationModalPresentViewControllerProtocol-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, UIView;

@interface OPRUserEditBackgroundViewController : UIViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, OPSNavigationModalPresentViewControllerProtocol>
{
    CDUnknownBlockType _previewSelectedImage;
    CDUnknownBlockType _cancelSelectedImage;
    UIView *_contentView;
    UIView *_backgroundView;
    struct CGSize _cropImageSize;
}

+ (void)uploadImage:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) CDUnknownBlockType cancelSelectedImage; // @synthesize cancelSelectedImage=_cancelSelectedImage;
@property(copy, nonatomic) CDUnknownBlockType previewSelectedImage; // @synthesize previewSelectedImage=_previewSelectedImage;
@property(nonatomic) struct CGSize cropImageSize; // @synthesize cropImageSize=_cropImageSize;
- (void).cxx_destruct;
- (void)uploadImageAndSave:(id)arg1;
- (void)onSelectedBtnClick;
- (void)bgCancel;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

