//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPUserProfile.h"

@class NSNumber, NSString;

@interface OPRUserFollowingListItem : OPUserProfile
{
    NSString *_cursor;
    NSNumber *_ts;
}

@property(retain, nonatomic) NSNumber *ts; // @synthesize ts=_ts;
@property(copy, nonatomic) NSString *cursor; // @synthesize cursor=_cursor;
- (void).cxx_destruct;

@end

