//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface OPRUpdateAlbumData : NSObject
{
    NSString *_roomId;
    NSArray *_albumIds;
}

@property(retain, nonatomic) NSArray *albumIds; // @synthesize albumIds=_albumIds;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
- (void).cxx_destruct;

@end

