//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPRBaseViewController.h"

#import "OPSNavigationTransitioning-Protocol.h"
#import "OPWebViewDelegate-Protocol.h"

@class NSString, NSURL, OPRWebViewJsHandler, OPRWebViewURLSchemeHandler, OPWebView, UIActivityIndicatorView, UIButton, UIColor;

@interface OPRWebViewController : OPRBaseViewController <OPSNavigationTransitioning, OPWebViewDelegate>
{
    _Bool _disableNativeErrorDisplay;
    _Bool _needURLSchemeHandler;
    _Bool _isHideTopbar;
    _Bool _banSwipe;
    _Bool _hasStatLoadingTime;
    _Bool _ignoreInnerBack;
    CDUnknownBlockType _didGetDataFromWebPage;
    CDUnknownBlockType _dismissHandler;
    CDUnknownBlockType _finishedLoadingBlock;
    long long _customStatusBarStyle;
    OPWebView *_webView;
    OPRWebViewJsHandler *_jsHandler;
    OPRWebViewURLSchemeHandler *_urlSchemeHandler;
    NSURL *_url;
    UIColor *_webBgColor;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_emptyClosedButton;
    double _startLoadTime;
}

+ (void)saveUserAgent:(id)arg1;
+ (void)initializeUserAgent;
@property(nonatomic) _Bool ignoreInnerBack; // @synthesize ignoreInnerBack=_ignoreInnerBack;
@property(nonatomic) double startLoadTime; // @synthesize startLoadTime=_startLoadTime;
@property(nonatomic) _Bool hasStatLoadingTime; // @synthesize hasStatLoadingTime=_hasStatLoadingTime;
@property(nonatomic) __weak UIButton *emptyClosedButton; // @synthesize emptyClosedButton=_emptyClosedButton;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIColor *webBgColor; // @synthesize webBgColor=_webBgColor;
@property(nonatomic) _Bool banSwipe; // @synthesize banSwipe=_banSwipe;
@property(nonatomic) _Bool isHideTopbar; // @synthesize isHideTopbar=_isHideTopbar;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) _Bool needURLSchemeHandler; // @synthesize needURLSchemeHandler=_needURLSchemeHandler;
@property(retain, nonatomic) OPRWebViewURLSchemeHandler *urlSchemeHandler; // @synthesize urlSchemeHandler=_urlSchemeHandler;
@property(retain, nonatomic) OPRWebViewJsHandler *jsHandler; // @synthesize jsHandler=_jsHandler;
@property(retain, nonatomic) OPWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool disableNativeErrorDisplay; // @synthesize disableNativeErrorDisplay=_disableNativeErrorDisplay;
@property(nonatomic) long long customStatusBarStyle; // @synthesize customStatusBarStyle=_customStatusBarStyle;
@property(copy, nonatomic) CDUnknownBlockType finishedLoadingBlock; // @synthesize finishedLoadingBlock=_finishedLoadingBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissHandler; // @synthesize dismissHandler=_dismissHandler;
@property(copy, nonatomic) CDUnknownBlockType didGetDataFromWebPage; // @synthesize didGetDataFromWebPage=_didGetDataFromWebPage;
- (void).cxx_destruct;
- (void)statWebViewLoadingIfNeed:(id)arg1;
- (long long)preferredStatusBarStyle;
- (void)onBackButtonClick;
- (void)webView:(id)arg1 showInput:(id)arg2 defaultText:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 showConfirm:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 showAlert:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)webViewLoadSucceed:(id)arg1;
- (void)webView:(id)arg1 loadFailed:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2;
- (void)webViewLoadingChanged:(id)arg1;
- (void)webViewTitleChanged:(id)arg1;
- (void)webViewProgressChanged:(id)arg1;
- (long long)interactiveTransitionSupportType;
- (void)onApplicationWillResign:(id)arg1;
- (void)addNotificationLister;
- (void)closeWebPage;
- (void)updateEmptyViewLayout;
- (void)addEmptyCloseView;
- (void)initWebView;
- (void)updateLayout;
- (_Bool)checkNeedUpdateIfNeed;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initURL:(id)arg1;
- (id)initURL:(id)arg1 needSchemeHandler:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

