//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPAccountManagerObserver-Protocol.h"
#import "UNUserNotificationCenterDelegate-Protocol.h"

@class NSString;

@interface OPSAliPushManager : NSObject <UNUserNotificationCenterDelegate, OPAccountManagerObserver>
{
    CDUnknownBlockType _backgoundBlock;
    CDUnknownBlockType _foregroundBlock;
}

+ (id)shareManager;
@property(copy, nonatomic) CDUnknownBlockType foregroundBlock; // @synthesize foregroundBlock=_foregroundBlock;
@property(copy, nonatomic) CDUnknownBlockType backgoundBlock; // @synthesize backgoundBlock=_backgoundBlock;
- (void).cxx_destruct;
- (void)sendLocalNotification:(id)arg1 body:(id)arg2 url:(id)arg3 info:(id)arg4 sound:(id)arg5 delay:(double)arg6 completed:(CDUnknownBlockType)arg7;
- (void)accountManager:(id)arg1 logerStatusChanged:(unsigned long long)arg2;
- (void)bindTPPushUser;
- (void)receiveTBPushAPS:(id)arg1;
- (void)uploadTBPushToken:(id)arg1;
- (void)startTBPushEngin;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)startUNRemote;
- (void)receiveLocalNotification:(id)arg1 isBackground:(_Bool)arg2;
- (void)receiveRemoteNotification:(id)arg1 isBackground:(_Bool)arg2;
- (void)uploadDeviceToken:(id)arg1;
- (void)start:(CDUnknownBlockType)arg1 fgReceiveHandler:(CDUnknownBlockType)arg2;
@property(nonatomic, getter=isDisableSound) _Bool disableSound;
- (void)WriteLog:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

