//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIImage, UIImageView, UIScrollView;

@interface OPSimpleImageBrowser : UIViewController <UIScrollViewDelegate>
{
    float targetX;
    float targetY;
    float targetWidth;
    float targetHeight;
    float photoWidth;
    float photoHeight;
    _Bool _viewDidAppear;
    UIImage *_photo;
    UIScrollView *_scrollView;
    UIImageView *_photoImageView;
    struct CGRect _photoOrginFrame;
}

@property(nonatomic) _Bool viewDidAppear; // @synthesize viewDidAppear=_viewDidAppear;
@property(retain, nonatomic) UIImageView *photoImageView; // @synthesize photoImageView=_photoImageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) struct CGRect photoOrginFrame; // @synthesize photoOrginFrame=_photoOrginFrame;
@property(retain, nonatomic) UIImage *photo; // @synthesize photo=_photo;
- (void).cxx_destruct;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)doubleTapEvent:(id)arg1;
- (void)oneTapEvent;
- (void)zoomPhotoToScreen;
- (void)showPhoto;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)prefersStatusBarHidden;
- (id)initWithImage:(id)arg1 lastPageFrame:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

