//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPSLocalization : NSObject
{
}

+ (void)languageDidChanged:(id)arg1;
+ (void)languageWillChange:(id)arg1;
+ (id)loadCurrentLanguageCodeWithSystemLanguage:(id)arg1;
+ (_Bool)changeLanguageCode:(id)arg1;
+ (void)initLanguageCode;
+ (void)localization;
+ (id)supportedRegions;
+ (id)regionInfoDictFromResource;
+ (id)regionFromDef:(id)arg1;
+ (id)languagesFromDefs:(id)arg1;

@end

