//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPSReachability : NSObject
{
}

+ (void)onNetworkChanged:(id)arg1;
+ (id)getSimpleNetworkType;
+ (id)getNetworkType;
+ (_Bool)isReachableViaWiFi;
+ (_Bool)isReachableViaWWAN;
+ (_Bool)isReachable;
+ (_Bool)startNotifier;
+ (id)reachability;
+ (void)initialize;

@end

