//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol OPSRuntimeDataProvider <NSObject>
- (NSString *)idfa;
- (NSString *)oslang;
- (NSString *)os;
- (NSString *)oem;
- (NSString *)pix;
- (NSString *)ss;
- (NSString *)cp;
- (NSString *)nation;
- (NSString *)btype;
- (NSString *)bmode;
- (NSString *)bid;
- (NSString *)ch;
- (NSString *)dataId;
- (NSString *)testId;
- (NSString *)sessionId;
- (NSString *)entry;
- (NSString *)language;
- (NSString *)loginST;
- (NSString *)userName;
- (NSString *)userId;
- (NSString *)utdid;
- (NSString *)pfid;
- (NSString *)prd;
- (NSString *)bseq;
- (NSString *)subver;
- (NSString *)ver;
- (NSString *)platform;
- (NSString *)app;
- (NSString *)package;
@end

