//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface OPSStatCoreService : NSObject
{
    _Bool _enable;
    CDUnknownBlockType _getUploadUrlHandler;
    NSMutableArray *_itemList;
    NSMutableArray *_taskList;
    unsigned long long _tryCount;
}

+ (id)shareInstance;
@property(nonatomic) unsigned long long tryCount; // @synthesize tryCount=_tryCount;
@property(retain, nonatomic) NSMutableArray *taskList; // @synthesize taskList=_taskList;
@property(retain, nonatomic) NSMutableArray *itemList; // @synthesize itemList=_itemList;
@property(copy, nonatomic) CDUnknownBlockType getUploadUrlHandler; // @synthesize getUploadUrlHandler=_getUploadUrlHandler;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (id)filePath:(_Bool)arg1;
- (_Bool)isSameDay:(id)arg1 Time2:(id)arg2;
- (void)saveData;
- (void)loadData;
- (void)startNewTask;
- (void)writeLog:(id)arg1;
- (_Bool)writeItems:(id)arg1;
- (_Bool)writeItem:(id)arg1;
- (void)statItems:(id)arg1;
- (void)statItem:(id)arg1;
- (void)stat:(id)arg1 ac:(id)arg2 ct:(id)arg3 lt:(id)arg4;
- (void)onApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

