//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface OPSShortURLTransCoder : NSObject
{
    NSMutableDictionary *_cacheShortURL;
}

+ (id)defaultUrlTranscoder;
@property(retain, nonatomic) NSMutableDictionary *cacheShortURL; // @synthesize cacheShortURL=_cacheShortURL;
- (void).cxx_destruct;
- (id)getSignKey:(id)arg1;
- (void)transUrl:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

