//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURL, UIApplication;

@interface OPSStartUpUrlInfo : NSObject
{
    UIApplication *_appdelegate;
    NSURL *_url;
    NSString *_sourceApplication;
    id _annotation;
    NSDictionary *_pushInfo;
}

@property(retain, nonatomic) NSDictionary *pushInfo; // @synthesize pushInfo=_pushInfo;
@property(retain, nonatomic) id annotation; // @synthesize annotation=_annotation;
@property(retain, nonatomic) NSString *sourceApplication; // @synthesize sourceApplication=_sourceApplication;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) __weak UIApplication *appdelegate; // @synthesize appdelegate=_appdelegate;
- (void).cxx_destruct;

@end

