//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class OPSStatWaService, OPSStatWaUpload;

@interface OPSStatWa : NSObject
{
    OPSStatWaService *_service;
    OPSStatWaUpload *_upload;
}

+ (_Bool)costTimeStatEnd:(CDUnknownBlockType)arg1;
+ (void)costTimeStatBegin:(long long)arg1;
+ (void)statItems:(id)arg1;
+ (void)statItem:(id)arg1;
+ (void)stat:(id)arg1 ac:(id)arg2 ct:(id)arg3;
+ (id)updateProperties:(id)arg1;
+ (void)appStart;
+ (void)turnDebug;
+ (void)turnLog;
+ (_Bool)enableTest;
+ (_Bool)enableLog;
+ (id)updateLt:(id)arg1;
+ (id)defaultLt;
+ (id)sharedInstance;
@property(retain, nonatomic) OPSStatWaUpload *upload; // @synthesize upload=_upload;
@property(retain, nonatomic) OPSStatWaService *service; // @synthesize service=_service;
- (void).cxx_destruct;

@end

