//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSURLSessionTask;

@interface OPSStatCoreTask : NSObject
{
    NSArray *_dataList;
    CDUnknownBlockType _completedHanlder;
    NSURLSessionTask *_task;
}

+ (id)params;
@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
@property(copy, nonatomic) CDUnknownBlockType completedHanlder; // @synthesize completedHanlder=_completedHanlder;
@property(retain, nonatomic) NSArray *dataList; // @synthesize dataList=_dataList;
- (void).cxx_destruct;
- (void)cancelTask;
- (_Bool)startTask:(id)arg1;
- (void)logCompleted:(unsigned long long)arg1;
- (void)logStart;
- (void)handlerTaskStatus:(unsigned long long)arg1;
- (id)uploadBody;
- (id)finalUploadUrl:(id)arg1;
- (id)buildItemData;
- (id)initWithData:(id)arg1 withCompleted:(CDUnknownBlockType)arg2;

@end

