//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPSStartUp : NSObject
{
}

+ (void)routerStart;
+ (void)onNetworkChangedNotification;
+ (void)cmsDoUpdate;
+ (void)cmsInit;
+ (_Bool)startFinished;
+ (void)startAfterHome;
+ (id)startCreateHomeWithOptions:(id)arg1;
+ (void)startBeforeHome;
+ (void)startInit;
+ (void)setEnv:(long long)arg1;

@end

