//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OPTestPeckerReportService : NSObject
{
}

+ (id)getDeviceResolution;
+ (id)getDevicePlatform;
+ (id)defaultService;
- (id)getExtensionWithItem:(id)arg1;
- (id)getFeedbackInfoWithItem:(id)arg1;
- (id)getReporterInfoWithEmail:(id)arg1;
- (id)getSystemInfo;
- (id)getCustomInfo;
- (id)getServerInfo;
- (id)uploadImagesData:(id)arg1;
- (void)upload:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (_Bool)isUploading;

@end

