//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OPTestPeckerReportServiceServer : NSObject
{
    NSString *_url;
    NSString *_projectId;
    NSString *_projectName;
}

+ (id)aoneServer;
@property(copy, nonatomic) NSString *projectName; // @synthesize projectName=_projectName;
@property(copy, nonatomic) NSString *projectId; // @synthesize projectId=_projectId;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

