//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class OPTipAnimating, OPTipDrawing, OPTipPositioning;

@interface OPTipPreferences : NSObject
{
    _Bool _shouldDismissOnTouchOutside;
    OPTipDrawing *_drawing;
    OPTipPositioning *_positioning;
    OPTipAnimating *_animating;
}

@property(nonatomic) _Bool shouldDismissOnTouchOutside; // @synthesize shouldDismissOnTouchOutside=_shouldDismissOnTouchOutside;
@property(retain, nonatomic) OPTipAnimating *animating; // @synthesize animating=_animating;
@property(retain, nonatomic) OPTipPositioning *positioning; // @synthesize positioning=_positioning;
@property(retain, nonatomic) OPTipDrawing *drawing; // @synthesize drawing=_drawing;
- (void).cxx_destruct;
- (id)initWithDefaultPreferences;

@end

