//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OPTouchBounceView.h"

#import "CAAnimationDelegate-Protocol.h"

@class NSArray, NSString, NSTimer, UIImageView, UILabel, UIView;

@interface OPTitleMarqueeButton : OPTouchBounceView <CAAnimationDelegate>
{
    CDUnknownBlockType _layoutDidUpdate;
    UIImageView *_leadIcon;
    UIView *_labelContainer;
    UILabel *_titleLabel;
    double _maxWidth;
    NSArray *_labelTitles;
    unsigned long long _nextTitleCount;
    NSTimer *_timer;
    double _animtionInterval;
}

@property(nonatomic) double animtionInterval; // @synthesize animtionInterval=_animtionInterval;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned long long nextTitleCount; // @synthesize nextTitleCount=_nextTitleCount;
@property(copy, nonatomic) NSArray *labelTitles; // @synthesize labelTitles=_labelTitles;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *labelContainer; // @synthesize labelContainer=_labelContainer;
@property(retain, nonatomic) UIImageView *leadIcon; // @synthesize leadIcon=_leadIcon;
@property(copy, nonatomic) CDUnknownBlockType layoutDidUpdate; // @synthesize layoutDidUpdate=_layoutDidUpdate;
- (void).cxx_destruct;
- (void)onTimerCountDown:(id)arg1;
- (void)stopTimer;
- (void)startAnimationTimer;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)removeAllAnimations;
- (void)startAnimationToHide:(_Bool)arg1;
- (void)updateNextTitle:(id)arg1;
- (void)resetTitles;
- (void)startAnimation;
- (void)updateFrame;
- (double)calculateMaxTextWidth;
- (id)createLabel;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

