//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OPUserProfileProtocol-Protocol.h"

@class NSArray, NSDate, NSNumber, NSString;
@protocol OPUserProfileExtendProtocol;

@interface OPUserProfile : NSObject <OPUserProfileProtocol>
{
    NSString *_uid;
    NSString *_name;
    NSString *_avatar;
    unsigned long long _gender;
    NSString *_phone;
    NSDate *_birthday;
    NSString *_about;
    NSString *_cityLiving;
    NSString *_cityBirth;
    NSString *_country;
    id <OPUserProfileExtendProtocol> _extend;
}

+ (id)userProfileWithUid:(id)arg1 name:(id)arg2 avatar:(id)arg3 gender:(unsigned long long)arg4;
+ (id)dateFromStr:(id)arg1;
+ (unsigned long long)genderFromStr:(id)arg1;
+ (id)genderToStr:(unsigned long long)arg1;
+ (id)userProfileWithDict:(id)arg1;
@property(retain, nonatomic) id <OPUserProfileExtendProtocol> extend; // @synthesize extend=_extend;
@property(copy, nonatomic) NSString *country; // @synthesize country=_country;
@property(copy, nonatomic) NSString *cityBirth; // @synthesize cityBirth=_cityBirth;
@property(copy, nonatomic) NSString *cityLiving; // @synthesize cityLiving=_cityLiving;
@property(copy, nonatomic) NSString *about; // @synthesize about=_about;
@property(retain, nonatomic) NSDate *birthday; // @synthesize birthday=_birthday;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(nonatomic) unsigned long long gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)initWithUid:(id)arg1 name:(id)arg2 avatar:(id)arg3 gender:(unsigned long long)arg4;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isSubscribedOrSubscribing;
- (_Bool)isSubscribedEachOrSubscribedEaching;
- (void)synSubscriptionStatus;
@property(readonly, nonatomic) unsigned long long subscriptionStatus;
- (void)setOhtersObject:(id)arg1 forKey:(id)arg2;
- (id)othersObjectForKey:(id)arg1;
@property(copy, nonatomic) NSArray *auths;
@property(copy, nonatomic) NSArray *gloryList;
@property(copy, nonatomic) NSString *backgroundUrl;
@property(copy, nonatomic) NSString *age;
@property(retain, nonatomic) NSNumber *todayVistorCount;
@property(retain, nonatomic) NSNumber *totalUgcCount;
@property(retain, nonatomic) NSNumber *totalLikeCount;
@property(retain, nonatomic) NSArray *medals;
@property(nonatomic) long long beLikedCount;
@property(nonatomic) long long likeCount;
@property(nonatomic) long long followerCount;
@property(nonatomic) long long followCount;
@property(nonatomic) long long publishCount;
@property(nonatomic) long long followStatus;
@property(readonly, nonatomic) _Bool isFollowed;
@property(nonatomic) _Bool needUpdateInfo;
@property(nonatomic) _Bool isRegister;
@property(nonatomic) unsigned long long userStatus;
@property(nonatomic) _Bool isNeedUploadAvatar;
- (id)userProfileExtend;
- (void)updateExtend:(id)arg1;
@property(copy, nonatomic) NSString *birthdayStr;
@property(copy, nonatomic) NSString *genderStr;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

