//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSDate, NSString;
@protocol OPUserProfileExtendProtocol;

@protocol OPUserProfileProtocol <NSObject, NSCoding, NSCopying>
@property(copy, nonatomic) NSString *avatar;
@property(copy, nonatomic) NSString *name;
@property(copy, nonatomic) NSString *uid;

@optional
@property(retain, nonatomic) id <OPUserProfileExtendProtocol> extend;
@property(copy, nonatomic) NSString *country;
@property(copy, nonatomic) NSString *cityBirth;
@property(copy, nonatomic) NSString *cityLiving;
@property(copy, nonatomic) NSString *about;
@property(retain, nonatomic) NSDate *birthday;
@property(copy, nonatomic) NSString *phone;
@property(nonatomic) unsigned long long gender;
@end

