//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSURL, NSURLRequest;
@protocol OPWebViewDelegate;

@protocol OPWebViewBaseProtocol <NSObject>
@property(nonatomic) __weak id <OPWebViewDelegate> delegate;
@property(readonly, copy, nonatomic) NSURL *URL;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) double estimatedProgress;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
- (void)stopLoading;
- (void)reload;
- (void)loadRequest:(NSURLRequest *)arg1;
@end

