//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMutableDictionary, NSMutableOrderedSet, NSString;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface OrangeUserDefault : NSObject
{
    NSObject<OS_dispatch_queue> *wFileSerialQueue;
    NSMutableDictionary *fileCacheDict;
    NSObject<OS_dispatch_semaphore> *_lock;
    NSMutableDictionary *_clientVersionDict;
    NSLock *_versionLock;
    NSString *_orangeConfigFolderPath;
    NSMutableOrderedSet *_pendingSaveNameOrderedSet;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableOrderedSet *pendingSaveNameOrderedSet; // @synthesize pendingSaveNameOrderedSet=_pendingSaveNameOrderedSet;
@property(copy, nonatomic) NSString *orangeConfigFolderPath; // @synthesize orangeConfigFolderPath=_orangeConfigFolderPath;
@property(retain, nonatomic) NSLock *versionLock; // @synthesize versionLock=_versionLock;
@property(retain, nonatomic) NSMutableDictionary *clientVersionDict; // @synthesize clientVersionDict=_clientVersionDict;
- (void).cxx_destruct;
- (void)synchronize;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)pathWithName:(id)arg1;
- (void)didReceivememoryWarning;
- (id)getByName:(id)arg1;
- (void)save:(id)arg1 name:(id)arg2;
- (void)_saveFile:(id)arg1 configName:(id)arg2;
- (void)didReceiveIdleNotification;
- (id)init;

@end

