//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface SystemPhotoHelperSaveItem : NSObject
{
    CDUnknownBlockType _syncCompletion;
    CDUnknownBlockType _asyncCompletion;
    UIImage *_image;
    NSString *_imageUrl;
}

+ (id)item;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) CDUnknownBlockType asyncCompletion; // @synthesize asyncCompletion=_asyncCompletion;
@property(copy, nonatomic) CDUnknownBlockType syncCompletion; // @synthesize syncCompletion=_syncCompletion;
- (void)dealloc;
- (id)init;

@end

