//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TBRestConfigData : NSObject
{
    NSString *_channel;
    NSString *_appkey;
    NSString *_secret;
    NSString *_userId;
    NSString *_usernick;
    NSString *_appVersion;
    NSString *_country;
    NSString *_dataUploadScheme;
    NSString *_dataUploadHost;
    NSString *_dataUploadUrl;
}

+ (id)defaultInstance;
@property(copy, nonatomic) NSString *dataUploadUrl; // @synthesize dataUploadUrl=_dataUploadUrl;
@property(copy, nonatomic) NSString *dataUploadHost; // @synthesize dataUploadHost=_dataUploadHost;
@property(copy, nonatomic) NSString *dataUploadScheme; // @synthesize dataUploadScheme=_dataUploadScheme;
@property(copy, nonatomic) NSString *country; // @synthesize country=_country;
@property(copy, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(copy, nonatomic) NSString *usernick; // @synthesize usernick=_usernick;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *secret; // @synthesize secret=_secret;
@property(copy, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;

@end

