//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ThumbnailImageHelper : NSObject
{
}

+ (id)getPathAppendDir:(id)arg1 dir:(id)arg2;
+ (_Bool)isDirectoryExist:(id)arg1;
+ (id)tempPath;
+ (id)createFolderIfNeed:(id)arg1 subPath:(id)arg2;

@end

