//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TikTokOpenSDKRSA : NSObject
{
}

+ (id)tiktok_decryptData:(id)arg1 publicKey:(id)arg2;
+ (id)tiktok_decryptString:(id)arg1 publicKey:(id)arg2;
+ (id)tiktok_encryptData:(id)arg1 publicKey:(id)arg2;
+ (id)tiktok_encryptString:(id)arg1 publicKey:(id)arg2;
+ (id)tiktok_decryptData:(id)arg1 privateKey:(id)arg2;
+ (id)tiktok_decryptString:(id)arg1 privateKey:(id)arg2;
+ (id)tiktok_decryptData:(id)arg1 withKeyRef:(struct __SecKey *)arg2;
+ (id)tiktok_encryptData:(id)arg1 privateKey:(id)arg2;
+ (id)tiktok_encryptString:(id)arg1 privateKey:(id)arg2;
+ (id)tiktok_encryptData:(id)arg1 withKeyRef:(struct __SecKey *)arg2 isSign:(_Bool)arg3;
+ (struct __SecKey *)tiktok_addPrivateKey:(id)arg1;
+ (struct __SecKey *)tiktok_addPublicKey:(id)arg1;
+ (id)tiktok_stripPrivateKeyHeader:(id)arg1;
+ (id)tiktok_stripPublicKeyHeader:(id)arg1;

@end

