//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface UCLLanguage : NSObject
{
    NSString *_name;
    NSString *_code;
    NSString *_localName;
    NSString *_parameterName;
    NSString *_localStringFilePath;
}

@property(copy, nonatomic) NSString *localStringFilePath; // @synthesize localStringFilePath=_localStringFilePath;
@property(copy, nonatomic) NSString *parameterName; // @synthesize parameterName=_parameterName;
@property(copy, nonatomic) NSString *localName; // @synthesize localName=_localName;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (id)initWithName:(id)arg1 withCode:(id)arg2 withLocal:(id)arg3 withParameter:(id)arg4 withPath:(id)arg5;

@end

