//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UCSGEncWrapper : NSObject
{
}

+ (void)handleSecureKeySwitch:(id)arg1;
+ (id)stringFromDecode:(id)arg1;
+ (id)dataFromDecode:(id)arg1;
+ (id)EncNSData:(id)arg1 exteranl:(_Bool)arg2;
+ (id)EncNSString:(id)arg1 base64:(_Bool)arg2 external:(_Bool)arg3;
+ (id)EncBase64String:(id)arg1 external:(_Bool)arg2;
+ (id)authCode;
+ (id)appKeyWithIsExteranl:(_Bool)arg1;
+ (void)setKeyIndex:(unsigned long long)arg1;
+ (void)initialzeWithSGKeys:(id)arg1 withAuthCode:(id)arg2 setIndex:(unsigned long long)arg3;
+ (void)initialzeWithIndexKey:(unsigned long long)arg1;

@end

