//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (UtilityEx)
+ (id)rawWepImageWithData:(struct WebPData)arg1;
+ (id)blendWebpImageWithOriginImage:(id)arg1 iterator:(struct WebPIterator)arg2;
+ (id)imageWithWebPData:(id)arg1;
+ (int)imageFormatForImageData:(id)arg1;
@end

