//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CNSecurityGuardWrapperDelegate-Protocol.h"
#import "CNUPaasManagerDelegate-Protocol.h"

@class NSHashTable, NSString;

@interface UpaasService : NSObject <CNSecurityGuardWrapperDelegate, CNUPaasManagerDelegate>
{
    _Bool _isDebug;
    _Bool _isInit;
    NSHashTable *_observerTable;
    long long _registerCount;
    CDUnknownBlockType _getDMDataHandler;
}

+ (id)defaultService;
@property(copy, nonatomic) CDUnknownBlockType getDMDataHandler; // @synthesize getDMDataHandler=_getDMDataHandler;
@property(nonatomic) long long registerCount; // @synthesize registerCount=_registerCount;
@property(retain, nonatomic) NSHashTable *observerTable; // @synthesize observerTable=_observerTable;
@property(nonatomic) _Bool isInit; // @synthesize isInit=_isInit;
@property(nonatomic) _Bool isDebug; // @synthesize isDebug=_isDebug;
- (void).cxx_destruct;
- (void)onNetworkStateChange:(id)arg1;
- (void)doCallbackDidChangeState:(int)arg1;
- (void)doCallbackDidGetServerUrl:(id)arg1;
- (void)doCallbackDidGetVid:(id)arg1;
- (void)doCallbackDidLoginSuccess;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)UPaasManagerStateDidChanged:(int)arg1;
- (void)UPaasManagerDidGetServerUrl:(id)arg1;
- (void)UPaasManagerDidLoginCompleted;
- (void)UPaasManagerDidFetchVid:(id)arg1;
- (id)securityGuardEncodeData:(id)arg1;
- (id)securityGuardDecodeData:(id)arg1;
- (id)securityGuardSignRequest:(id)arg1 requestType:(int)arg2;
- (void)tryToReconnectUpaas;
- (void)trySentHeartbeat;
- (int)getState;
- (id)getVid;
- (void)setupConnection:(CDUnknownBlockType)arg1;
- (void)setupHttpDNSService:(_Bool)arg1;
- (void)initializeCNNet;
- (void)setEnv:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

