//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WaServiceDelegate-Protocol.h"

@class NSString;
@protocol WaServiceDelegate;

@interface WaBridge : NSObject <WaServiceDelegate>
{
    id <WaServiceDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) id <WaServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (id)bodyHeader;
- (void)willUpload;
- (id)encodeBodyData:(id)arg1;
- (id)decodeStoreData:(id)arg1;
- (id)encodeStoreData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

