//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WatermarkOptions : NSObject
{
    _Bool _visibleInPreview;
    struct CGRect _positionInLandscapeMode;
    struct CGRect _positionInPortraitMode;
}

@property(nonatomic) struct CGRect positionInPortraitMode; // @synthesize positionInPortraitMode=_positionInPortraitMode;
@property(nonatomic) struct CGRect positionInLandscapeMode; // @synthesize positionInLandscapeMode=_positionInLandscapeMode;
@property(nonatomic) _Bool visibleInPreview; // @synthesize visibleInPreview=_visibleInPreview;

@end

