//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WPKMobiConfig : NSObject
{
    _Bool _intlDomain;
    NSString *_appName;
    NSString *_deviceUDID;
    NSString *_sn;
    NSString *_buildDate;
    NSString *_bid;
    NSString *_k_crash_ver;
    NSString *_appVersion;
    NSString *_UC_URL;
    NSString *_UC_DownloadBg;
    NSString *_UC_Extra;
    NSString *_UC_ExtraInfo;
    NSString *_UC_UserAction;
    NSString *_appGroupIdentifier;
}

+ (id)version;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *appGroupIdentifier; // @synthesize appGroupIdentifier=_appGroupIdentifier;
@property(copy, nonatomic) NSString *UC_UserAction; // @synthesize UC_UserAction=_UC_UserAction;
@property(copy, nonatomic) NSString *UC_ExtraInfo; // @synthesize UC_ExtraInfo=_UC_ExtraInfo;
@property(copy, nonatomic) NSString *UC_Extra; // @synthesize UC_Extra=_UC_Extra;
@property(copy, nonatomic) NSString *UC_DownloadBg; // @synthesize UC_DownloadBg=_UC_DownloadBg;
@property(copy, nonatomic) NSString *UC_URL; // @synthesize UC_URL=_UC_URL;
@property(nonatomic) _Bool intlDomain; // @synthesize intlDomain=_intlDomain;
@property(copy, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(copy, nonatomic) NSString *k_crash_ver; // @synthesize k_crash_ver=_k_crash_ver;
@property(copy, nonatomic) NSString *bid; // @synthesize bid=_bid;
@property(copy, nonatomic) NSString *buildDate; // @synthesize buildDate=_buildDate;
@property(copy, nonatomic) NSString *sn; // @synthesize sn=_sn;
@property(copy, nonatomic) NSString *deviceUDID; // @synthesize deviceUDID=_deviceUDID;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
- (void).cxx_destruct;
- (id)internalGetDeviceUDID;
- (id)toDict;
- (id)init;

@end

